<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Kaizer">

<title>Alex Kaizer - General Linear Hypothesis Testing (GLHT) and Matrices, Contrasts, and F-Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/size.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/academicons-1.9.1/css/academicons.css" rel="stylesheet">

<link rel="icon" type="image/png" href="./files/favicon.ico">

<script type="text/javascript">
function setBrand() {
document.getElementsByClassName("navbar-brand")[0].href="https://www.alexkaizer.com";
}
window.onload = setBrand;
</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5PBG7BL207"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5PBG7BL207');
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Alex Kaizer</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/research" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/publications" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/teaching" rel="" target="">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6618" rel="" target="">
 <span class="dropdown-text">BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6611" rel="" target="">
 <span class="dropdown-text">BIOS 6611</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/study_design_berd" rel="" target="">
 <span class="dropdown-text">BERD Study Design Short Course</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/adaptivetrials_sc" rel="" target="">
 <span class="dropdown-text">WNAR Adaptive and Bayesian Clinical Trial Design Short Course</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bios-6618" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">BIOS 6618</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bios-6618">    
        <li>
    <a class="dropdown-item" href="../../index.html" rel="" target="">
 <span class="dropdown-text">Home</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../bios_6618_materials" rel="" target="">
 <span class="dropdown-text">Materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../journal_of_bios_6618" rel="" target="">
 <span class="dropdown-text">Journal of BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../recitation" rel="" target="">
 <span class="dropdown-text">Recitation Questions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs" rel="" target="">
 <span class="dropdown-text">Labs and Practice Problems</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:alex.kaizer@cuanschutz.edu" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=ICpH74EAAAAJ&amp;hl=en" rel="" target="">
 <span class="menu-text"><i class="ai  ai-google-scholar ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="http://github.com/alexbiostats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/files/Alex_CV.pdf" rel="" target="">
 <span class="menu-text"><i class="ai  ai-cv ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/alex-kaizer/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#contrasts-and-general-linear-hypothesis-testing" id="toc-contrasts-and-general-linear-hypothesis-testing" class="nav-link active" data-scroll-target="#contrasts-and-general-linear-hypothesis-testing">Contrasts and General Linear Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#contrasts" id="toc-contrasts" class="nav-link" data-scroll-target="#contrasts">Contrasts</a>
  <ul class="collapse">
  <li><a href="#contrasts-example" id="toc-contrasts-example" class="nav-link" data-scroll-target="#contrasts-example">Contrasts Example</a></li>
  <li><a href="#contrasts-with-cell-means-models" id="toc-contrasts-with-cell-means-models" class="nav-link" data-scroll-target="#contrasts-with-cell-means-models">Contrasts with Cell Means Models</a></li>
  </ul></li>
  <li><a href="#general-linear-hypothesis-testing" id="toc-general-linear-hypothesis-testing" class="nav-link" data-scroll-target="#general-linear-hypothesis-testing">General Linear Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#testing-differences-other-than-0" id="toc-testing-differences-other-than-0" class="nav-link" data-scroll-target="#testing-differences-other-than-0">Testing Differences Other Than 0</a></li>
  <li><a href="#comparisons-with-sum-c_i-neq-0" id="toc-comparisons-with-sum-c_i-neq-0" class="nav-link" data-scroll-target="#comparisons-with-sum-c_i-neq-0">Comparisons with <span class="math inline">\(\sum c_i \neq 0\)</span></a></li>
  <li><a href="#more-complex-models" id="toc-more-complex-models" class="nav-link" data-scroll-target="#more-complex-models">More Complex Models</a></li>
  </ul></li>
  <li><a href="#joint-testing" id="toc-joint-testing" class="nav-link" data-scroll-target="#joint-testing">Joint Testing</a></li>
  <li><a href="#f-tests-with-matrices-versus-anova-and-connections-to-joint-testing" id="toc-f-tests-with-matrices-versus-anova-and-connections-to-joint-testing" class="nav-link" data-scroll-target="#f-tests-with-matrices-versus-anova-and-connections-to-joint-testing">F-tests with Matrices versus <code>anova</code> and Connections to Joint Testing</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">General Linear Hypothesis Testing (GLHT) and Matrices, Contrasts, and F-Tests</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Alex Kaizer </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Colorado-Anschutz Medical Campus
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<p>This page is part of the University of Colorado-Anschutz Medical Campus’ <a href="../../recitation/index.html">BIOS 6618 Recitation</a> collection. To view other questions, you can view the <a href="../../recitation/index.html">BIOS 6618 Recitation</a> collection page or use the search bar to look for keywords.</p>
<section id="contrasts-and-general-linear-hypothesis-testing" class="level1">
<h1>Contrasts and General Linear Hypothesis Testing</h1>
<p>We’ve discussed various ways we can compare different variables in our regression model:</p>
<ul>
<li>With categorical variables we can either change the reference category and refit the model to compare two groups if neither is the reference (e.g., never smokers as reference, with former and current smokers as the indicators included in the model). Or we can use the variance-covariance matrix to calculate these differences from the original model.</li>
<li>We can calculate the difference for more than a 1-unit change in a continuous predictor (e.g., what if <span class="math inline">\(X\)</span> increases by 5 units).</li>
</ul>
<p>As noted above, we could potentially refit the models the change the reference category or otherwise transform some aspect of the data/model to try and answer hypotheses that may stem from these questions:</p>
<ul>
<li>Is there a significant difference between former and heavy smokers?</li>
<li>Is the change for a 5-unit increase in <span class="math inline">\(X\)</span> significantly different from 0 (or any other null hypothesis)?</li>
</ul>
<p>Let’s examine some of these questions with our carotenoids data set:</p>
<p>On our homework you are given a dataset on a cross-sectional study was designed to investigate the relationship between personal characteristics, dietary factors, and plasma concentrations of retinol, beta-carotene and other carotenoids:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp) <span class="co"># package to load for contrasts/general linear hypothesis testing</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"../../.data/carotenoids.dat"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'age'</span>,<span class="st">'sex'</span>,<span class="st">'smoke'</span>,<span class="st">'bmi'</span>,<span class="st">'vitamins'</span>,<span class="st">'calories'</span>,<span class="st">'fat'</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'fiber'</span>,<span class="st">'alcohol'</span>,<span class="st">'chol'</span>,<span class="st">'betadiet'</span>,<span class="st">'retdiet'</span>,<span class="st">'betaplas'</span>,<span class="st">'retplas'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>AK_smoke_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Never'</span>,<span class="st">'Former'</span>,<span class="st">'Current'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="contrasts" class="level2">
<h2 class="anchored" data-anchor-id="contrasts">Contrasts</h2>
<p>In the most general sense, contrasts are differences between regression coefficients. Further, the comparison of coefficients must sum to 0: <span class="math inline">\(\sum c_i = 0\)</span>.</p>
<p>For example, if our regression model was comparing some outcome between never, former, and current smokers we might have:</p>
<p><span class="math display">\[ \hat{Y} = \hat{\beta}_{0} + \hat{\beta}_{\text{former}} I_{F} + \hat{\beta}_{\text{current}} I_{C} \]</span></p>
<p>If we wanted to compare (1) never and former or (2) never and current smokers we would be able to simply evaluate our output’s regression coefficient table and interpret the <span class="math inline">\(t\)</span>-test/p-value provided.</p>
<p>If we wanted to compare if the mean levels were the same between former and current smokers, we could propose a contrast: <span class="math inline">\((0, 1, -1)\)</span>. This would translate to <span class="math inline">\(H_0 \colon \hat{\beta}_{\text{former}} - \hat{\beta}_{\text{current}} = 0\)</span>.</p>
<p>We can make a more direct connection to the mean for each group if we recall:</p>
<ul>
<li><span class="math inline">\(\mu_{\text{never}} = \hat{\beta}_{0}\)</span></li>
<li><span class="math inline">\(\mu_{\text{former}} = \hat{\beta}_{0} + \hat{\beta}_{\text{former}}\)</span></li>
<li><span class="math inline">\(\mu_{\text{current}} = \hat{\beta}_{0} + \hat{\beta}_{\text{current}}\)</span></li>
</ul>
<p>Then we can see what is being compared for each pairwise comparison (and a more direct connection to ANOVA):</p>
<ul>
<li>Never vs.&nbsp;Former: <span class="math inline">\((\hat{\beta}_{0} + \hat{\beta}_{\text{former}}) - \hat{\beta}_{0} = \hat{\beta}_{\text{former}}\)</span></li>
<li>Never vs.&nbsp;Current: <span class="math inline">\((\hat{\beta}_{0} + \hat{\beta}_{\text{current}}) - \hat{\beta}_{0} = \hat{\beta}_{\text{current}}\)</span></li>
<li>Current vs.&nbsp;Former: <span class="math inline">\((\hat{\beta}_{0} + \hat{\beta}_{\text{former}}) - (\hat{\beta}_{0} + \hat{\beta}_{\text{current}}) = \hat{\beta}_{\text{former}} - \hat{\beta}_{\text{current}}\)</span></li>
</ul>
<p>Our default hypothesis test for each of these is that there is no difference (e.g., 0).</p>
<p>While this is meant to be a general comparison of regression coefficients, it is restricted in that the contrast must sum to 0. We are also restricted to testing if the difference is 0.</p>
<section id="contrasts-example" class="level3">
<h3 class="anchored" data-anchor-id="contrasts-example">Contrasts Example</h3>
<p>Let’s fit a reference cell model first between beta-carotene in the diet as our outcome and smoking status as our predictor:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f, <span class="at">data=</span>dat)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = betadiet ~ AK_smoke_f, data = dat)

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         2.1934     0.1168  18.771   &lt;2e-16 ***
AK_smoke_fFormer    0.1618     0.1797   0.901   0.3685    
AK_smoke_fCurrent  -0.4899     0.2520  -1.944   0.0528 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 2.143603)

    Null deviance: 682.12  on 314  degrees of freedom
Residual deviance: 668.80  on 312  degrees of freedom
AIC: 1139.1

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>We see from our output, that there is no statistically significant difference between never smokers and former or current smokers (p=0.3685, p=0.0528, respectively). However, if we wished to compare the former and current smokers we would need to specify our contrast:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow=</span><span class="dv">1</span> )</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1,<span class="at">linfct=</span>c))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f, data = dat)

Linear Hypotheses:
       Estimate Std. Error z value Pr(&gt;|z|)  
1 == 0   0.6517     0.2617    2.49   0.0128 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>We see here that p=0.0128, so we’d reject the null hypothesis that former and current smokers have equal means for the dietary beta-carotene.</p>
</section>
<section id="contrasts-with-cell-means-models" class="level3">
<h3 class="anchored" data-anchor-id="contrasts-with-cell-means-models">Contrasts with Cell Means Models</h3>
<p>One of the natural applications for contrasts is with cell means models for regression:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod1_cellmeans <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data=</span>dat)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1_cellmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = betadiet ~ AK_smoke_f - 1, data = dat)

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
AK_smoke_fNever     2.1934     0.1168   18.77  &lt; 2e-16 ***
AK_smoke_fFormer    2.3552     0.1365   17.25  &lt; 2e-16 ***
AK_smoke_fCurrent   1.7035     0.2233    7.63 2.87e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 2.143603)

    Null deviance: 2186.8  on 315  degrees of freedom
Residual deviance:  668.8  on 312  degrees of freedom
AIC: 1139.1

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>We see in our summary output that all of our means are significantly different from 0, but we haven’t completed any pairwise comparisons. We can specify three contrasts to replicate our results above from the reference cell model:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>c_cellmeans <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span>T ) <span class="co"># specify a matrix with 3 rows (one for each contrast)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pairwise_cellmeans <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1_cellmeans, <span class="at">linfct=</span>c_cellmeans)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_cellmeans, <span class="at">test=</span><span class="fu">adjusted</span>(<span class="st">"none"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f - 1, data = dat)

Linear Hypotheses:
       Estimate Std. Error z value Pr(&gt;|z|)  
1 == 0  -0.1618     0.1797  -0.901   0.3678  
2 == 0   0.4899     0.2520   1.944   0.0519 .
3 == 0   0.6517     0.2617   2.490   0.0128 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- none method)</code></pre>
</div>
</div>
<p>This reflects our results from before!</p>
<p>We can also note that <code>summary.glht</code> includes options to adjust for multiplicity (the default is a “single-step method” adjustment):</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_cellmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f - 1, data = dat)

Linear Hypotheses:
       Estimate Std. Error z value Pr(&gt;|z|)  
1 == 0  -0.1618     0.1797  -0.901   0.6353  
2 == 0   0.4899     0.2520   1.944   0.1233  
3 == 0   0.6517     0.2617   2.490   0.0333 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>With these specific results, we see that our conclusions would not change for each pairwise test even after accounting for multiple testing.</p>
</section>
</section>
<section id="general-linear-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="general-linear-hypothesis-testing">General Linear Hypothesis Testing</h2>
<section id="testing-differences-other-than-0" class="level3">
<h3 class="anchored" data-anchor-id="testing-differences-other-than-0">Testing Differences Other Than 0</h3>
<p>We can generalize contrasts to test for differences that aren’t just 0. For example, we might wish to revise our cell means result to compare to a difference of 0.5 between groups:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>c_cellmeans <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span>T ) <span class="co"># specify a matrix with 3 rows (one for each contrast)</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>pairwise_cellmeans_glht <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1_cellmeans, <span class="at">linfct=</span>c_cellmeans, <span class="at">rhs=</span><span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_cellmeans_glht, <span class="at">test=</span><span class="fu">adjusted</span>(<span class="st">"none"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f - 1, data = dat)

Linear Hypotheses:
         Estimate Std. Error z value Pr(&gt;|z|)    
1 == 0.5  -0.1618     0.1797  -3.683 0.000231 ***
2 == 0.5   0.4899     0.2520  -0.040 0.967883    
3 == 0.5   0.6517     0.2617   0.580 0.562171    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- none method)</code></pre>
</div>
</div>
<p>We can see that the linear hypothesis test is now comparing our estimates to 0.5 instead of 0. It makes sense that the first pairwise difference (Never-Former) is now significant, but the other two are not. However, direction does matter since we aren’t testing if the difference is either positive or negative 0.5, just +0.5.</p>
</section>
<section id="comparisons-with-sum-c_i-neq-0" class="level3">
<h3 class="anchored" data-anchor-id="comparisons-with-sum-c_i-neq-0">Comparisons with <span class="math inline">\(\sum c_i \neq 0\)</span></h3>
<p>With GLHT, we can also compare any combination of interest, even if it doesn’t sum to 0.</p>
<p>For example, we can compare if the means for current smokers is equal to half that of never smokers. This null hypothesis is <span class="math inline">\(\frac{1}{2}\mu_{N} = \mu_{C} \implies \frac{1}{2}\mu_{N} + 0 \mu_F + -1 \mu_{C} = 0\)</span>:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>c3_cellmeans <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.5</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow=</span><span class="dv">1</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1_cellmeans,<span class="at">linfct=</span>c3_cellmeans))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f - 1, data = dat)

Linear Hypotheses:
       Estimate Std. Error z value Pr(&gt;|z|)   
1 == 0  -0.6068     0.2308  -2.629  0.00855 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>We can also specify this in terms of the reference cell model with</p>
<p><span class="math display">\[ \frac{1}{2}\mu_{N} + 0 \mu_F + -1 \mu_{C} = 0 \implies \frac{1}{2}\hat{\beta}_{0} - (\hat{\beta}_{0} + \hat{\beta}_{C}) = 0 \implies -\frac{1}{2}\hat{\beta}_{0} - \hat{\beta}_{C} = 0 \]</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>c3 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow=</span><span class="dv">1</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1,<span class="at">linfct=</span>c3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f, data = dat)

Linear Hypotheses:
       Estimate Std. Error z value Pr(&gt;|z|)   
1 == 0  -0.6068     0.2308  -2.629  0.00855 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>We see the reference cell and cell means model results match, even though our contrasts were:</p>
<p><span class="math display">\[
\begin{matrix} \text{Reference Cell} \\ \text{Cell Means} \end{matrix}
\begin{matrix} = \\ = \end{matrix}
\begin{pmatrix}
-0.5 &amp; 0 &amp; -1 \\
0.5 &amp; 0 &amp; -1
\end{pmatrix}
\]</span></p>
</section>
<section id="more-complex-models" class="level3">
<h3 class="anchored" data-anchor-id="more-complex-models">More Complex Models</h3>
<p>We can also play around with far more complex models and use our GLHT to estimate various effects, combinations of predictors, and/or compare to hypotheses that are equal to 0 or any other value. Consider:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>glm_be_cray <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f <span class="sc">+</span> bmi <span class="sc">+</span> age, <span class="at">data=</span>dat)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_be_cray)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = betadiet ~ AK_smoke_f + bmi + age, data = dat)

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.012354   0.495050   4.065  6.1e-05 ***
AK_smoke_fFormer   0.161407   0.180366   0.895   0.3715    
AK_smoke_fCurrent -0.461002   0.257023  -1.794   0.0738 .  
bmi               -0.003575   0.013861  -0.258   0.7966    
age                0.005400   0.005750   0.939   0.3484    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 2.150732)

    Null deviance: 682.12  on 314  degrees of freedom
Residual deviance: 666.73  on 310  degrees of freedom
AIC: 1142.1

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>If we wanted to compare a 35-year old nonsmoker and 50-year old former smoker with the same BMI, we would have:</p>
<p><span class="math display">\[
\begin{align}
&amp;\hat{\beta}_0 &amp;+ 0 \hat{\beta}_{F} &amp;+ 0 \hat{\beta}_{C} &amp;+ X_{BMI}\hat{\beta}_{BMI} &amp;+ 35 \hat{\beta}_{age} \\
- (&amp;\hat{\beta}_0 &amp;+ 1 \hat{\beta}_{F} &amp;+ 0 \hat{\beta}_{C} &amp;+ X_{BMI}\hat{\beta}_{BMI} &amp;+ 50 \hat{\beta}_{age}) \\
\hline
&amp;0\hat{\beta}_0 &amp; -1 \hat{\beta}_{F} &amp; \;\;\;\;0 \hat{\beta}_{C} &amp; 0 \hat{\beta}_{BMI} &amp; -15 \hat{\beta}_{age}
\end{align}
\]</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>c4 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">15</span>), <span class="at">nrow=</span><span class="dv">1</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(glm_be_cray,<span class="at">linfct=</span>c4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f + bmi + age, data = dat)

Linear Hypotheses:
       Estimate Std. Error z value Pr(&gt;|z|)
1 == 0  -0.2424     0.2012  -1.205    0.228
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>From this test result we see that there is no significant difference between these two combinations based on our regression output.</p>
<p>We could also calculate a confidence interval around our estimate:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">glht</span>(glm_be_cray,<span class="at">linfct=</span>c4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Confidence Intervals

Fit: glm(formula = betadiet ~ AK_smoke_f + bmi + age, data = dat)

Quantile = 1.96
95% family-wise confidence level
 

Linear Hypotheses:
       Estimate lwr     upr    
1 == 0 -0.2424  -0.6367  0.1519</code></pre>
</div>
</div>
<p>Note that it summarize our results as “simultaneous CIs” to control the 95% <em>family-wise</em> confidence level. In other words, if we were testing multiple hypotheses, it would apply a correction to not just our p-value, but also the confidence intervals:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>c4_plus2random <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">15</span>, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">10</span>,<span class="dv">0</span>, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">10</span>,<span class="dv">10</span>), </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span>T)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">glht</span>(glm_be_cray, <span class="at">linfct=</span>c4_plus2random))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Confidence Intervals

Fit: glm(formula = betadiet ~ AK_smoke_f + bmi + age, data = dat)

Quantile = 2.3513
95% family-wise confidence level
 

Linear Hypotheses:
       Estimate lwr     upr    
1 == 0 -0.2424  -0.7155  0.2307
2 == 0  1.9766   1.0396  2.9136
3 == 0 -0.6042  -1.3575  0.1492</code></pre>
</div>
</div>
<p>The first CI is now wider, reflecting the correction for multiple testing to maintain the family-wise type I error rate.</p>
</section>
</section>
<section id="joint-testing" class="level2">
<h2 class="anchored" data-anchor-id="joint-testing">Joint Testing</h2>
<p>One aspect we haven’t covered yet, what if you wish to <em>jointly</em> test multiple hypotheses at the same time (e.g., like an overall <span class="math inline">\(F\)</span>-test)? This would account for the potential of multiple testing and may better reflect specific combinations of hypotheses.</p>
<p>In one case, we might have a specific question of interest that relies on specifying multiple hypotheses. For instance, what if we believed that our dietary beta-carotene should have a linear trend where former smokers have a 0.5 higher level than never smokers, and current smokers are 1.0 higher level than never smokers:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># returning to our simpler reference cell model with just smoking status</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow=</span>T)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>hyp_val <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">1.0</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>joint_test <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1, <span class="at">linfct =</span> K, <span class="at">rhs =</span> hyp_val)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify a joint test with test=Ftest() that conducts an overall F-test for the two hypotheses</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(joint_test, <span class="at">test=</span><span class="fu">Ftest</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     General Linear Hypotheses

Linear Hypotheses:
         Estimate
1 == 0.5   0.1618
2 == 1    -0.4899

Global Test:
      F DF1 DF2    Pr(&gt;F)
1 17.48   2 312 6.366e-08</code></pre>
</div>
</div>
<p>This <span class="math inline">\(F\)</span>-test indicates that we would reject the <em>joint</em> null hypothesis, at least one of the null hypotheses would be rejected.</p>
<p>A natural follow-up question would be, which one(s) do we reject? To correct for multiple comparisons, we see</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For comparison, summarize the family-wise corrected individual tests</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(joint_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: glm(formula = betadiet ~ AK_smoke_f, data = dat)

Linear Hypotheses:
         Estimate Std. Error z value Pr(&gt;|z|)    
1 == 0.5   0.1618     0.1797  -1.882    0.113    
2 == 1    -0.4899     0.2520  -5.912 6.76e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>In other words, we would reject our second null hypothesis that <span class="math inline">\(H_0 \colon \beta_{C} = 1\)</span>, but not the first that <span class="math inline">\(H_0 \colon \beta_{F} = 0.5\)</span>.</p>
<p>In practice, I tend to favor conducting the hypothesis test that directly addresses the question of interest (especially if you end up correcting for multiple comparisons anyway). However, there are likely cases where a global test of a joint hypothesis is most appropriate and efficient.</p>
</section>
<section id="f-tests-with-matrices-versus-anova-and-connections-to-joint-testing" class="level2">
<h2 class="anchored" data-anchor-id="f-tests-with-matrices-versus-anova-and-connections-to-joint-testing">F-tests with Matrices versus <code>anova</code> and Connections to Joint Testing</h2>
<p>The <span class="math inline">\(F\)</span>-test can be used to test the GLH: <span class="math display">\[\begin{equation*}
F = \frac{[(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})^T(\mathbf{c}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}^T)^{-1}(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})/r]}{\hat{\sigma}^2_{Y|X}} \sim F_{r,n-p-1}
\end{equation*}\]</span></p>
<p>where <span class="math inline">\(\hat{\sigma}^2_{Y|X}\)</span> is our MSE from the full model. This reduces to our Partial <span class="math inline">\(F\)</span>-test for testing a group of variables, because</p>
<p><span class="math display">\[\begin{equation*}
(\mathbf{c}\hat{\boldsymbol{\beta}})^T(\mathbf{c}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}^T)^{-1}(\mathbf{c}\hat{\boldsymbol{\beta}}) = SS_{model}(full)-SS_{model}(reduced)
\end{equation*}\]</span></p>
<p>Therefore, a test of a single linear hypothesis for a single parameter also reduces to our <span class="math inline">\(t\)</span>-test.</p>
<p>Note, the above formulas do NOT require us to refit a “reduced” model to compare to our full model. Instead, all of our needed information is contained within our design matrix and our <span class="math inline">\(\mathbf{c}_{r \times p}\)</span> matrix of rank <span class="math inline">\(r\)</span> where <span class="math inline">\(r \leq p\)</span> (i.e., number of rows that are “unique” (i.e., not made up of other combinations of rows)).</p>
<p>Let’s compare the overall F-test for the following model using matrices or by fitting a reduced model and using the <code>anova()</code> function:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Model-based approach</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>glm_be_cray <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f <span class="sc">+</span> bmi <span class="sc">+</span> age, <span class="at">data=</span>dat)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>glm_be_null <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>dat)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(glm_be_cray, glm_be_null, <span class="at">test=</span><span class="st">'F'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: betadiet ~ AK_smoke_f + bmi + age
Model 2: betadiet ~ 1
  Resid. Df Resid. Dev Df Deviance      F Pr(&gt;F)
1       310     666.73                          
2       314     682.12 -4  -15.388 1.7887 0.1309</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Matrix approach</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create indicators for smoking categories</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>AK_smoke_former <span class="ot">&lt;-</span> dat<span class="sc">$</span>smoke<span class="sc">==</span><span class="dv">2</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>AK_smoke_current <span class="ot">&lt;-</span> dat<span class="sc">$</span>smoke<span class="sc">==</span><span class="dv">3</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> dat<span class="sc">$</span>betadiet</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>YtY <span class="ot">&lt;-</span> <span class="fu">t</span>(Y) <span class="sc">%*%</span> Y</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1</span>, dat<span class="sc">$</span>AK_smoke_former, dat<span class="sc">$</span>AK_smoke_current, dat<span class="sc">$</span>bmi, dat<span class="sc">$</span>age)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>Xt <span class="ot">&lt;-</span> <span class="fu">t</span>(X)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>XtX <span class="ot">&lt;-</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> X</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>XtX_inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(XtX)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>beta_vec <span class="ot">&lt;-</span> XtX_inv <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> Y</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>Yhat <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta_vec</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>mse <span class="ot">&lt;-</span> ( YtY <span class="sc">-</span> <span class="fu">t</span>(beta_vec) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> Y ) <span class="sc">/</span> ( <span class="fu">length</span>(Y) <span class="sc">-</span> <span class="fu">ncol</span>(X) )</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ncol=</span><span class="fu">ncol</span>(X), <span class="at">byrow=</span>T)</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">ncol=</span><span class="dv">1</span> )</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>Fstat_num <span class="ot">&lt;-</span> ( <span class="fu">t</span>(c<span class="sc">%*%</span>beta_vec <span class="sc">-</span> d) <span class="sc">%*%</span> <span class="fu">solve</span>(c <span class="sc">%*%</span> XtX_inv <span class="sc">%*%</span> <span class="fu">t</span>(c)) <span class="sc">%*%</span> (c<span class="sc">%*%</span>beta_vec <span class="sc">-</span> d) ) <span class="sc">/</span> <span class="fu">nrow</span>(c)</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>Fstat <span class="ot">&lt;-</span> Fstat_num <span class="sc">/</span> mse</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>Fstat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 1.788729</code></pre>
</div>
</div>
<p>We can see that we’ve arrived at the same result, but without having to fit the reduced model!</p>
<p>The connection between the partial F-test and the GLHT may help us better draw connections between our formulas and the two approaches:</p>
<p><span class="math display">\[ F = \frac{[SS_{model}(full) - SS_{model}(reduced)]/k^{*}}{MS_{error}(full)} \sim F_{k^{*},n-p^{*}-k^{*}-1} \]</span> <span class="math display">\[ F = \frac{[(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})^T(\mathbf{c}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}^T)^{-1}(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})/r]}{\hat{\sigma}^2_{Y|X}} \sim F_{r,n-p-1} \]</span></p>
<p>From our notation we see for the partial F-test that the total number of parameters in the full model is <span class="math inline">\(p^{*}+k^{*}\)</span>; whereas in the GLH F-test it is just <span class="math inline">\(p\)</span>.</p>
<p>Further, for the partial F-test <span class="math inline">\(k^{*}\)</span> is the number of parameters removed from the full model; whereas in the GLH F-test <span class="math inline">\(r\)</span> is the rank of <span class="math inline">\(\mathbf{c}\)</span>:</p>
<span class="math display">\[\begin{bmatrix}
0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; 1
\end{bmatrix}\]</span>
<p>where each column represents a beta coefficient, including the intercept, and each row represents a different hypothesis test being conducted jointly/simultaneously).</p>
<p>For completeness, the null hypothesis the GLH is testing is:</p>
<p><span class="math display">\[ H_0 \colon \; \mathbf{c}\boldsymbol{\beta} = \mathbf{d} \implies \begin{bmatrix}
0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; 1
\end{bmatrix} \begin{bmatrix} \beta_0 \\ \beta_{former} \\ \beta_{current} \\ \beta_{bmi} \\ \beta_{age} \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}  \]</span></p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb34" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "General Linear Hypothesis Testing (GLHT) and Matrices, Contrasts, and F-Tests"</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Alex Kaizer</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co">  roles: "Instructor"</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co">  affiliation: University of Colorado-Anschutz Medical Campus</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc_float:</span><span class="co"> true</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> left</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap </span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=F, message=F, warning=F}</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>This page is part of the University of Colorado-Anschutz Medical Campus' <span class="co">[</span><span class="ot">BIOS 6618 Recitation</span><span class="co">](/recitation/index.qmd)</span> collection. To view other questions, you can view the <span class="co">[</span><span class="ot">BIOS 6618 Recitation</span><span class="co">](/recitation/index.qmd)</span> collection page or use the search bar to look for keywords.</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a><span class="fu"># Contrasts and General Linear Hypothesis Testing</span></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>We've discussed various ways we can compare different variables in our regression model:</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>With categorical variables we can either change the reference category and refit the model to compare two groups if neither is the reference (e.g., never smokers as reference, with former and current smokers as the indicators included in the model). Or we can use the variance-covariance matrix to calculate these differences from the original model.</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>We can calculate the difference for more than a 1-unit change in a continuous predictor (e.g., what if $X$ increases by 5 units).</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>As noted above, we could potentially refit the models the change the reference category or otherwise transform some aspect of the data/model to try and answer hypotheses that may stem from these questions:</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Is there a significant difference between former and heavy smokers?</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Is the change for a 5-unit increase in $X$ significantly different from 0 (or any other null hypothesis)?</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>Let's examine some of these questions with our carotenoids data set:</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>On our homework you are given a dataset on a cross-sectional study was designed to investigate the relationship between personal characteristics, dietary factors, and plasma concentrations of retinol, beta-carotene and other carotenoids:</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=F, message=F}</span></span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp) <span class="co"># package to load for contrasts/general linear hypothesis testing</span></span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"../../.data/carotenoids.dat"</span>)</span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'age'</span>,<span class="st">'sex'</span>,<span class="st">'smoke'</span>,<span class="st">'bmi'</span>,<span class="st">'vitamins'</span>,<span class="st">'calories'</span>,<span class="st">'fat'</span>,</span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'fiber'</span>,<span class="st">'alcohol'</span>,<span class="st">'chol'</span>,<span class="st">'betadiet'</span>,<span class="st">'retdiet'</span>,<span class="st">'betaplas'</span>,<span class="st">'retplas'</span>)</span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>AK_smoke_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Never'</span>,<span class="st">'Former'</span>,<span class="st">'Current'</span>))</span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Contrasts</span></span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a>In the most general sense, contrasts are differences between regression coefficients. Further, the comparison of coefficients must sum to 0: $\sum c_i = 0$.</span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a>For example, if our regression model was comparing some outcome between never, former, and current smokers we might have:</span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a>$$ \hat{Y} = \hat{\beta}_{0} + \hat{\beta}_{\text{former}} I_{F} + \hat{\beta}_{\text{current}} I_{C} $$</span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a>If we wanted to compare (1) never and former or (2) never and current smokers we would be able to simply evaluate our output's regression coefficient table and interpret the $t$-test/p-value provided.</span>
<span id="cb34-61"><a href="#cb34-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-62"><a href="#cb34-62" aria-hidden="true" tabindex="-1"></a>If we wanted to compare if the mean levels were the same between former and current smokers, we could propose a contrast: $(0, 1, -1)$. This would translate to $H_0 \colon \hat{\beta}_{\text{former}} - \hat{\beta}_{\text{current}} = 0$.</span>
<span id="cb34-63"><a href="#cb34-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-64"><a href="#cb34-64" aria-hidden="true" tabindex="-1"></a>We can make a more direct connection to the mean for each group if we recall:</span>
<span id="cb34-65"><a href="#cb34-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-66"><a href="#cb34-66" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\mu_{\text{never}} = \hat{\beta}_{0}$</span>
<span id="cb34-67"><a href="#cb34-67" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\mu_{\text{former}} = \hat{\beta}_{0} + \hat{\beta}_{\text{former}}$</span>
<span id="cb34-68"><a href="#cb34-68" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\mu_{\text{current}} = \hat{\beta}_{0} + \hat{\beta}_{\text{current}}$</span>
<span id="cb34-69"><a href="#cb34-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-70"><a href="#cb34-70" aria-hidden="true" tabindex="-1"></a>Then we can see what is being compared for each pairwise comparison (and a more direct connection to ANOVA):</span>
<span id="cb34-71"><a href="#cb34-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-72"><a href="#cb34-72" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Never vs. Former: $(\hat{\beta}_{0} + \hat{\beta}_{\text{former}}) - \hat{\beta}_{0} = \hat{\beta}_{\text{former}}$</span>
<span id="cb34-73"><a href="#cb34-73" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Never vs. Current: $(\hat{\beta}_{0} + \hat{\beta}_{\text{current}}) - \hat{\beta}_{0} = \hat{\beta}_{\text{current}}$</span>
<span id="cb34-74"><a href="#cb34-74" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Current vs. Former: $(\hat{\beta}_{0} + \hat{\beta}_{\text{former}}) - (\hat{\beta}_{0} + \hat{\beta}_{\text{current}}) = \hat{\beta}_{\text{former}} - \hat{\beta}_{\text{current}}$</span>
<span id="cb34-75"><a href="#cb34-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-76"><a href="#cb34-76" aria-hidden="true" tabindex="-1"></a>Our default hypothesis test for each of these is that there is no difference (e.g., 0).</span>
<span id="cb34-77"><a href="#cb34-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-78"><a href="#cb34-78" aria-hidden="true" tabindex="-1"></a>While this is meant to be a general comparison of regression coefficients, it is restricted in that the contrast must sum to 0. We are also restricted to testing if the difference is 0.</span>
<span id="cb34-79"><a href="#cb34-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-80"><a href="#cb34-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-81"><a href="#cb34-81" aria-hidden="true" tabindex="-1"></a><span class="fu">### Contrasts Example</span></span>
<span id="cb34-82"><a href="#cb34-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-83"><a href="#cb34-83" aria-hidden="true" tabindex="-1"></a>Let's fit a reference cell model first between beta-carotene in the diet as our outcome and smoking status as our predictor:</span>
<span id="cb34-84"><a href="#cb34-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-87"><a href="#cb34-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-88"><a href="#cb34-88" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f, <span class="at">data=</span>dat)</span>
<span id="cb34-89"><a href="#cb34-89" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span>
<span id="cb34-90"><a href="#cb34-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-91"><a href="#cb34-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-92"><a href="#cb34-92" aria-hidden="true" tabindex="-1"></a>We see from our output, that there is no statistically significant difference between never smokers and former or current smokers (p=0.3685, p=0.0528, respectively). However, if we wished to compare the former and current smokers we would need to specify our contrast:</span>
<span id="cb34-93"><a href="#cb34-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-96"><a href="#cb34-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-97"><a href="#cb34-97" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow=</span><span class="dv">1</span> )</span>
<span id="cb34-98"><a href="#cb34-98" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1,<span class="at">linfct=</span>c))</span>
<span id="cb34-99"><a href="#cb34-99" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-100"><a href="#cb34-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-101"><a href="#cb34-101" aria-hidden="true" tabindex="-1"></a>We see here that p=0.0128, so we'd reject the null hypothesis that former and current smokers have equal means for the dietary beta-carotene.</span>
<span id="cb34-102"><a href="#cb34-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-103"><a href="#cb34-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-104"><a href="#cb34-104" aria-hidden="true" tabindex="-1"></a><span class="fu">### Contrasts with Cell Means Models</span></span>
<span id="cb34-105"><a href="#cb34-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-106"><a href="#cb34-106" aria-hidden="true" tabindex="-1"></a>One of the natural applications for contrasts is with cell means models for regression:</span>
<span id="cb34-107"><a href="#cb34-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-110"><a href="#cb34-110" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-111"><a href="#cb34-111" aria-hidden="true" tabindex="-1"></a>mod1_cellmeans <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data=</span>dat)</span>
<span id="cb34-112"><a href="#cb34-112" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1_cellmeans)</span>
<span id="cb34-113"><a href="#cb34-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-114"><a href="#cb34-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-115"><a href="#cb34-115" aria-hidden="true" tabindex="-1"></a>We see in our summary output that all of our means are significantly different from 0, but we haven't completed any pairwise comparisons. We can specify three contrasts to replicate our results above from the reference cell model:</span>
<span id="cb34-116"><a href="#cb34-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-119"><a href="#cb34-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-120"><a href="#cb34-120" aria-hidden="true" tabindex="-1"></a>c_cellmeans <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>, </span>
<span id="cb34-121"><a href="#cb34-121" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>, </span>
<span id="cb34-122"><a href="#cb34-122" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), </span>
<span id="cb34-123"><a href="#cb34-123" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span>T ) <span class="co"># specify a matrix with 3 rows (one for each contrast)</span></span>
<span id="cb34-124"><a href="#cb34-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-125"><a href="#cb34-125" aria-hidden="true" tabindex="-1"></a>pairwise_cellmeans <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1_cellmeans, <span class="at">linfct=</span>c_cellmeans)</span>
<span id="cb34-126"><a href="#cb34-126" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_cellmeans, <span class="at">test=</span><span class="fu">adjusted</span>(<span class="st">"none"</span>))</span>
<span id="cb34-127"><a href="#cb34-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-128"><a href="#cb34-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-129"><a href="#cb34-129" aria-hidden="true" tabindex="-1"></a>This reflects our results from before!</span>
<span id="cb34-130"><a href="#cb34-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-131"><a href="#cb34-131" aria-hidden="true" tabindex="-1"></a>We can also note that <span class="in">`summary.glht`</span> includes options to adjust for multiplicity (the default is a "single-step method" adjustment):</span>
<span id="cb34-132"><a href="#cb34-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-135"><a href="#cb34-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-136"><a href="#cb34-136" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_cellmeans)</span>
<span id="cb34-137"><a href="#cb34-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-138"><a href="#cb34-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-139"><a href="#cb34-139" aria-hidden="true" tabindex="-1"></a>With these specific results, we see that our conclusions would not change for each pairwise test even after accounting for multiple testing.</span>
<span id="cb34-140"><a href="#cb34-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-141"><a href="#cb34-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-142"><a href="#cb34-142" aria-hidden="true" tabindex="-1"></a><span class="fu">## General Linear Hypothesis Testing</span></span>
<span id="cb34-143"><a href="#cb34-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-144"><a href="#cb34-144" aria-hidden="true" tabindex="-1"></a><span class="fu">### Testing Differences Other Than 0</span></span>
<span id="cb34-145"><a href="#cb34-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-146"><a href="#cb34-146" aria-hidden="true" tabindex="-1"></a>We can generalize contrasts to test for differences that aren't just 0. For example, we might wish to revise our cell means result to compare to a difference of 0.5 between groups:</span>
<span id="cb34-147"><a href="#cb34-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-150"><a href="#cb34-150" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-151"><a href="#cb34-151" aria-hidden="true" tabindex="-1"></a>c_cellmeans <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>, </span>
<span id="cb34-152"><a href="#cb34-152" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>, </span>
<span id="cb34-153"><a href="#cb34-153" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), </span>
<span id="cb34-154"><a href="#cb34-154" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span>T ) <span class="co"># specify a matrix with 3 rows (one for each contrast)</span></span>
<span id="cb34-155"><a href="#cb34-155" aria-hidden="true" tabindex="-1"></a>pairwise_cellmeans_glht <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1_cellmeans, <span class="at">linfct=</span>c_cellmeans, <span class="at">rhs=</span><span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb34-156"><a href="#cb34-156" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_cellmeans_glht, <span class="at">test=</span><span class="fu">adjusted</span>(<span class="st">"none"</span>))</span>
<span id="cb34-157"><a href="#cb34-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-158"><a href="#cb34-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-159"><a href="#cb34-159" aria-hidden="true" tabindex="-1"></a>We can see that the linear hypothesis test is now comparing our estimates to 0.5 instead of 0. It makes sense that the first pairwise difference (Never-Former) is now significant, but the other two are not. However, direction does matter since we aren't testing if the difference is either positive or negative 0.5, just +0.5.</span>
<span id="cb34-160"><a href="#cb34-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-161"><a href="#cb34-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-162"><a href="#cb34-162" aria-hidden="true" tabindex="-1"></a><span class="fu">### Comparisons with $\sum c_i \neq 0$</span></span>
<span id="cb34-163"><a href="#cb34-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-164"><a href="#cb34-164" aria-hidden="true" tabindex="-1"></a>With GLHT, we can also compare any combination of interest, even if it doesn't sum to 0.</span>
<span id="cb34-165"><a href="#cb34-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-166"><a href="#cb34-166" aria-hidden="true" tabindex="-1"></a>For example, we can compare if the means for current smokers is equal to half that of never smokers. This null hypothesis is $\frac{1}{2}\mu_{N} = \mu_{C} \implies \frac{1}{2}\mu_{N} + 0 \mu_F + -1 \mu_{C} = 0$:</span>
<span id="cb34-167"><a href="#cb34-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-170"><a href="#cb34-170" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-171"><a href="#cb34-171" aria-hidden="true" tabindex="-1"></a>c3_cellmeans <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.5</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow=</span><span class="dv">1</span>)</span>
<span id="cb34-172"><a href="#cb34-172" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1_cellmeans,<span class="at">linfct=</span>c3_cellmeans))</span>
<span id="cb34-173"><a href="#cb34-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-174"><a href="#cb34-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-175"><a href="#cb34-175" aria-hidden="true" tabindex="-1"></a>We can also specify this in terms of the reference cell model with </span>
<span id="cb34-176"><a href="#cb34-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-177"><a href="#cb34-177" aria-hidden="true" tabindex="-1"></a>$$ \frac{1}{2}\mu_{N} + 0 \mu_F + -1 \mu_{C} = 0 \implies \frac{1}{2}\hat{\beta}_{0} - (\hat{\beta}_{0} + \hat{\beta}_{C}) = 0 \implies -\frac{1}{2}\hat{\beta}_{0} - \hat{\beta}_{C} = 0 $$</span>
<span id="cb34-178"><a href="#cb34-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-181"><a href="#cb34-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-182"><a href="#cb34-182" aria-hidden="true" tabindex="-1"></a>c3 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow=</span><span class="dv">1</span>)</span>
<span id="cb34-183"><a href="#cb34-183" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1,<span class="at">linfct=</span>c3))</span>
<span id="cb34-184"><a href="#cb34-184" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-185"><a href="#cb34-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-186"><a href="#cb34-186" aria-hidden="true" tabindex="-1"></a>We see the reference cell and cell means model results match, even though our contrasts were:</span>
<span id="cb34-187"><a href="#cb34-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-188"><a href="#cb34-188" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-189"><a href="#cb34-189" aria-hidden="true" tabindex="-1"></a>\begin{matrix} \text{Reference Cell} <span class="sc">\\</span> \text{Cell Means} \end{matrix} </span>
<span id="cb34-190"><a href="#cb34-190" aria-hidden="true" tabindex="-1"></a>\begin{matrix} = <span class="sc">\\</span> = \end{matrix}</span>
<span id="cb34-191"><a href="#cb34-191" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb34-192"><a href="#cb34-192" aria-hidden="true" tabindex="-1"></a>-0.5 &amp; 0 &amp; -1 <span class="sc">\\</span></span>
<span id="cb34-193"><a href="#cb34-193" aria-hidden="true" tabindex="-1"></a>0.5 &amp; 0 &amp; -1</span>
<span id="cb34-194"><a href="#cb34-194" aria-hidden="true" tabindex="-1"></a>\end{pmatrix}</span>
<span id="cb34-195"><a href="#cb34-195" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-196"><a href="#cb34-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-197"><a href="#cb34-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-198"><a href="#cb34-198" aria-hidden="true" tabindex="-1"></a><span class="fu">### More Complex Models</span></span>
<span id="cb34-199"><a href="#cb34-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-200"><a href="#cb34-200" aria-hidden="true" tabindex="-1"></a>We can also play around with far more complex models and use our GLHT to estimate various effects, combinations of predictors, and/or compare to hypotheses that are equal to 0 or any other value. Consider:</span>
<span id="cb34-201"><a href="#cb34-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-204"><a href="#cb34-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-205"><a href="#cb34-205" aria-hidden="true" tabindex="-1"></a>glm_be_cray <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f <span class="sc">+</span> bmi <span class="sc">+</span> age, <span class="at">data=</span>dat)</span>
<span id="cb34-206"><a href="#cb34-206" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_be_cray)</span>
<span id="cb34-207"><a href="#cb34-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-208"><a href="#cb34-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-209"><a href="#cb34-209" aria-hidden="true" tabindex="-1"></a>If we wanted to compare a 35-year old nonsmoker and 50-year old former smoker with the same BMI, we would have:</span>
<span id="cb34-210"><a href="#cb34-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-211"><a href="#cb34-211" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-212"><a href="#cb34-212" aria-hidden="true" tabindex="-1"></a>\begin{align}</span>
<span id="cb34-213"><a href="#cb34-213" aria-hidden="true" tabindex="-1"></a>&amp;\hat{\beta}_0 &amp;+ 0 \hat{\beta}_{F} &amp;+ 0 \hat{\beta}_{C} &amp;+ X_{BMI}\hat{\beta}_{BMI} &amp;+ 35 \hat{\beta}_{age} <span class="sc">\\</span></span>
<span id="cb34-214"><a href="#cb34-214" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(&amp;\hat{\beta}_0 &amp;+ 1 \hat{\beta}_{F} &amp;+ 0 \hat{\beta}_{C} &amp;+ X_{BMI}\hat{\beta}_{BMI} &amp;+ 50 \hat{\beta}_{age}) <span class="sc">\\</span></span>
<span id="cb34-215"><a href="#cb34-215" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb34-216"><a href="#cb34-216" aria-hidden="true" tabindex="-1"></a>&amp;0\hat{\beta}_0 &amp; -1 \hat{\beta}_{F} &amp; \;\;\;\;0 \hat{\beta}_{C} &amp; 0 \hat{\beta}_{BMI} &amp; -15 \hat{\beta}_{age}</span>
<span id="cb34-217"><a href="#cb34-217" aria-hidden="true" tabindex="-1"></a>\end{align}</span>
<span id="cb34-218"><a href="#cb34-218" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-219"><a href="#cb34-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-222"><a href="#cb34-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-223"><a href="#cb34-223" aria-hidden="true" tabindex="-1"></a>c4 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">15</span>), <span class="at">nrow=</span><span class="dv">1</span>)</span>
<span id="cb34-224"><a href="#cb34-224" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(glm_be_cray,<span class="at">linfct=</span>c4))</span>
<span id="cb34-225"><a href="#cb34-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-226"><a href="#cb34-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-227"><a href="#cb34-227" aria-hidden="true" tabindex="-1"></a>From this test result we see that there is no significant difference between these two combinations based on our regression output.</span>
<span id="cb34-228"><a href="#cb34-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-229"><a href="#cb34-229" aria-hidden="true" tabindex="-1"></a>We could also calculate a confidence interval around our estimate:</span>
<span id="cb34-230"><a href="#cb34-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-233"><a href="#cb34-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-234"><a href="#cb34-234" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">glht</span>(glm_be_cray,<span class="at">linfct=</span>c4))</span>
<span id="cb34-235"><a href="#cb34-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-236"><a href="#cb34-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-237"><a href="#cb34-237" aria-hidden="true" tabindex="-1"></a>Note that it summarize our results as "simultaneous CIs" to control the 95% *family-wise* confidence level. In other words, if we were testing multiple hypotheses, it would apply a correction to not just our p-value, but also the confidence intervals:</span>
<span id="cb34-238"><a href="#cb34-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-241"><a href="#cb34-241" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-242"><a href="#cb34-242" aria-hidden="true" tabindex="-1"></a>c4_plus2random <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">15</span>, </span>
<span id="cb34-243"><a href="#cb34-243" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">10</span>,<span class="dv">0</span>, </span>
<span id="cb34-244"><a href="#cb34-244" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">10</span>,<span class="dv">10</span>), </span>
<span id="cb34-245"><a href="#cb34-245" aria-hidden="true" tabindex="-1"></a>                         <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span>T)</span>
<span id="cb34-246"><a href="#cb34-246" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">glht</span>(glm_be_cray, <span class="at">linfct=</span>c4_plus2random))</span>
<span id="cb34-247"><a href="#cb34-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-248"><a href="#cb34-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-249"><a href="#cb34-249" aria-hidden="true" tabindex="-1"></a>The first CI is now wider, reflecting the correction for multiple testing to maintain the family-wise type I error rate.</span>
<span id="cb34-250"><a href="#cb34-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-251"><a href="#cb34-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-252"><a href="#cb34-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-253"><a href="#cb34-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## Joint Testing</span></span>
<span id="cb34-254"><a href="#cb34-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-255"><a href="#cb34-255" aria-hidden="true" tabindex="-1"></a>One aspect we haven't covered yet, what if you wish to *jointly* test multiple hypotheses at the same time (e.g., like an overall $F$-test)? This would account for the potential of multiple testing and may better reflect specific combinations of hypotheses.</span>
<span id="cb34-256"><a href="#cb34-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-257"><a href="#cb34-257" aria-hidden="true" tabindex="-1"></a>In one case, we might have a specific question of interest that relies on specifying multiple hypotheses. For instance, what if we believed that our dietary beta-carotene should have a linear trend where former smokers have a 0.5 higher level than never smokers, and current smokers are 1.0 higher level than never smokers:</span>
<span id="cb34-258"><a href="#cb34-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-261"><a href="#cb34-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-262"><a href="#cb34-262" aria-hidden="true" tabindex="-1"></a><span class="co"># returning to our simpler reference cell model with just smoking status</span></span>
<span id="cb34-263"><a href="#cb34-263" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb34-264"><a href="#cb34-264" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb34-265"><a href="#cb34-265" aria-hidden="true" tabindex="-1"></a>             <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow=</span>T)</span>
<span id="cb34-266"><a href="#cb34-266" aria-hidden="true" tabindex="-1"></a>hyp_val <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">1.0</span>)</span>
<span id="cb34-267"><a href="#cb34-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-268"><a href="#cb34-268" aria-hidden="true" tabindex="-1"></a>joint_test <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1, <span class="at">linfct =</span> K, <span class="at">rhs =</span> hyp_val)</span>
<span id="cb34-269"><a href="#cb34-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-270"><a href="#cb34-270" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify a joint test with test=Ftest() that conducts an overall F-test for the two hypotheses</span></span>
<span id="cb34-271"><a href="#cb34-271" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(joint_test, <span class="at">test=</span><span class="fu">Ftest</span>())</span>
<span id="cb34-272"><a href="#cb34-272" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-273"><a href="#cb34-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-274"><a href="#cb34-274" aria-hidden="true" tabindex="-1"></a>This $F$-test indicates that we would reject the *joint* null hypothesis, at least one of the null hypotheses would be rejected.</span>
<span id="cb34-275"><a href="#cb34-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-276"><a href="#cb34-276" aria-hidden="true" tabindex="-1"></a>A natural follow-up question would be, which one(s) do we reject? To correct for multiple comparisons, we see</span>
<span id="cb34-277"><a href="#cb34-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-280"><a href="#cb34-280" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-281"><a href="#cb34-281" aria-hidden="true" tabindex="-1"></a><span class="co"># For comparison, summarize the family-wise corrected individual tests</span></span>
<span id="cb34-282"><a href="#cb34-282" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(joint_test)</span>
<span id="cb34-283"><a href="#cb34-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-284"><a href="#cb34-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-285"><a href="#cb34-285" aria-hidden="true" tabindex="-1"></a>In other words, we would reject our second null hypothesis that $H_0 \colon \beta_{C} = 1$, but not the first that $H_0 \colon \beta_{F} = 0.5$.</span>
<span id="cb34-286"><a href="#cb34-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-287"><a href="#cb34-287" aria-hidden="true" tabindex="-1"></a>In practice, I tend to favor conducting the hypothesis test that directly addresses the question of interest (especially if you end up correcting for multiple comparisons anyway). However, there are likely cases where a global test of a joint hypothesis is most appropriate and efficient.</span>
<span id="cb34-288"><a href="#cb34-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-289"><a href="#cb34-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-290"><a href="#cb34-290" aria-hidden="true" tabindex="-1"></a><span class="fu">## F-tests with Matrices versus `anova` and Connections to Joint Testing</span></span>
<span id="cb34-291"><a href="#cb34-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-292"><a href="#cb34-292" aria-hidden="true" tabindex="-1"></a>The $F$-test can be used to test the GLH:</span>
<span id="cb34-293"><a href="#cb34-293" aria-hidden="true" tabindex="-1"></a>\begin{equation*}</span>
<span id="cb34-294"><a href="#cb34-294" aria-hidden="true" tabindex="-1"></a>F = \frac{<span class="co">[</span><span class="ot">(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})^T(\mathbf{c}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}^T)^{-1}(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})/r</span><span class="co">]</span>}{\hat{\sigma}^2_{Y|X}} \sim F_{r,n-p-1}</span>
<span id="cb34-295"><a href="#cb34-295" aria-hidden="true" tabindex="-1"></a>\end{equation*}</span>
<span id="cb34-296"><a href="#cb34-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-297"><a href="#cb34-297" aria-hidden="true" tabindex="-1"></a>where $\hat{\sigma}^2_{Y|X}$ is our MSE from the full model. This reduces to our Partial $F$-test for testing a group of variables, because</span>
<span id="cb34-298"><a href="#cb34-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-299"><a href="#cb34-299" aria-hidden="true" tabindex="-1"></a>\begin{equation*}</span>
<span id="cb34-300"><a href="#cb34-300" aria-hidden="true" tabindex="-1"></a>(\mathbf{c}\hat{\boldsymbol{\beta}})^T(\mathbf{c}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}^T)^{-1}(\mathbf{c}\hat{\boldsymbol{\beta}}) = SS_{model}(full)-SS_{model}(reduced)</span>
<span id="cb34-301"><a href="#cb34-301" aria-hidden="true" tabindex="-1"></a>\end{equation*}</span>
<span id="cb34-302"><a href="#cb34-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-303"><a href="#cb34-303" aria-hidden="true" tabindex="-1"></a>Therefore, a test of a single linear hypothesis for a single parameter also reduces to our $t$-test.</span>
<span id="cb34-304"><a href="#cb34-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-305"><a href="#cb34-305" aria-hidden="true" tabindex="-1"></a>Note, the above formulas do NOT require us to refit a "reduced" model to compare to our full model. Instead, all of our needed information is contained within our design matrix and our $\mathbf{c}_{r \times p}$ matrix of rank $r$ where $r \leq p$ (i.e., number of rows that are "unique" (i.e., not made up of other combinations of rows)).</span>
<span id="cb34-306"><a href="#cb34-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-307"><a href="#cb34-307" aria-hidden="true" tabindex="-1"></a>Let's compare the overall F-test for the following model using matrices or by fitting a reduced model and using the <span class="in">`anova()`</span> function:</span>
<span id="cb34-308"><a href="#cb34-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-311"><a href="#cb34-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-312"><a href="#cb34-312" aria-hidden="true" tabindex="-1"></a><span class="do">### Model-based approach</span></span>
<span id="cb34-313"><a href="#cb34-313" aria-hidden="true" tabindex="-1"></a>glm_be_cray <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> AK_smoke_f <span class="sc">+</span> bmi <span class="sc">+</span> age, <span class="at">data=</span>dat)</span>
<span id="cb34-314"><a href="#cb34-314" aria-hidden="true" tabindex="-1"></a>glm_be_null <span class="ot">&lt;-</span> <span class="fu">glm</span>(betadiet <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>dat)</span>
<span id="cb34-315"><a href="#cb34-315" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(glm_be_cray, glm_be_null, <span class="at">test=</span><span class="st">'F'</span>)</span>
<span id="cb34-316"><a href="#cb34-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-317"><a href="#cb34-317" aria-hidden="true" tabindex="-1"></a><span class="do">### Matrix approach</span></span>
<span id="cb34-318"><a href="#cb34-318" aria-hidden="true" tabindex="-1"></a><span class="co"># Create indicators for smoking categories</span></span>
<span id="cb34-319"><a href="#cb34-319" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>AK_smoke_former <span class="ot">&lt;-</span> dat<span class="sc">$</span>smoke<span class="sc">==</span><span class="dv">2</span></span>
<span id="cb34-320"><a href="#cb34-320" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>AK_smoke_current <span class="ot">&lt;-</span> dat<span class="sc">$</span>smoke<span class="sc">==</span><span class="dv">3</span></span>
<span id="cb34-321"><a href="#cb34-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-322"><a href="#cb34-322" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> dat<span class="sc">$</span>betadiet</span>
<span id="cb34-323"><a href="#cb34-323" aria-hidden="true" tabindex="-1"></a>YtY <span class="ot">&lt;-</span> <span class="fu">t</span>(Y) <span class="sc">%*%</span> Y</span>
<span id="cb34-324"><a href="#cb34-324" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1</span>, dat<span class="sc">$</span>AK_smoke_former, dat<span class="sc">$</span>AK_smoke_current, dat<span class="sc">$</span>bmi, dat<span class="sc">$</span>age)</span>
<span id="cb34-325"><a href="#cb34-325" aria-hidden="true" tabindex="-1"></a>Xt <span class="ot">&lt;-</span> <span class="fu">t</span>(X)</span>
<span id="cb34-326"><a href="#cb34-326" aria-hidden="true" tabindex="-1"></a>XtX <span class="ot">&lt;-</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> X</span>
<span id="cb34-327"><a href="#cb34-327" aria-hidden="true" tabindex="-1"></a>XtX_inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(XtX)</span>
<span id="cb34-328"><a href="#cb34-328" aria-hidden="true" tabindex="-1"></a>beta_vec <span class="ot">&lt;-</span> XtX_inv <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> Y</span>
<span id="cb34-329"><a href="#cb34-329" aria-hidden="true" tabindex="-1"></a>Yhat <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta_vec</span>
<span id="cb34-330"><a href="#cb34-330" aria-hidden="true" tabindex="-1"></a>mse <span class="ot">&lt;-</span> ( YtY <span class="sc">-</span> <span class="fu">t</span>(beta_vec) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> Y ) <span class="sc">/</span> ( <span class="fu">length</span>(Y) <span class="sc">-</span> <span class="fu">ncol</span>(X) )</span>
<span id="cb34-331"><a href="#cb34-331" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,</span>
<span id="cb34-332"><a href="#cb34-332" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,</span>
<span id="cb34-333"><a href="#cb34-333" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb34-334"><a href="#cb34-334" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ncol=</span><span class="fu">ncol</span>(X), <span class="at">byrow=</span>T)</span>
<span id="cb34-335"><a href="#cb34-335" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">ncol=</span><span class="dv">1</span> )</span>
<span id="cb34-336"><a href="#cb34-336" aria-hidden="true" tabindex="-1"></a>Fstat_num <span class="ot">&lt;-</span> ( <span class="fu">t</span>(c<span class="sc">%*%</span>beta_vec <span class="sc">-</span> d) <span class="sc">%*%</span> <span class="fu">solve</span>(c <span class="sc">%*%</span> XtX_inv <span class="sc">%*%</span> <span class="fu">t</span>(c)) <span class="sc">%*%</span> (c<span class="sc">%*%</span>beta_vec <span class="sc">-</span> d) ) <span class="sc">/</span> <span class="fu">nrow</span>(c)</span>
<span id="cb34-337"><a href="#cb34-337" aria-hidden="true" tabindex="-1"></a>Fstat <span class="ot">&lt;-</span> Fstat_num <span class="sc">/</span> mse</span>
<span id="cb34-338"><a href="#cb34-338" aria-hidden="true" tabindex="-1"></a>Fstat</span>
<span id="cb34-339"><a href="#cb34-339" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-340"><a href="#cb34-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-341"><a href="#cb34-341" aria-hidden="true" tabindex="-1"></a>We can see that we've arrived at the same result, but without having to fit the reduced model!</span>
<span id="cb34-342"><a href="#cb34-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-343"><a href="#cb34-343" aria-hidden="true" tabindex="-1"></a>The connection between the partial F-test and the GLHT may help us better draw connections between our formulas and the two approaches:</span>
<span id="cb34-344"><a href="#cb34-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-345"><a href="#cb34-345" aria-hidden="true" tabindex="-1"></a>$$ F = \frac{<span class="co">[</span><span class="ot">SS_{model}(full) - SS_{model}(reduced)</span><span class="co">]</span>/k^{*}}{MS_{error}(full)} \sim F_{k^{*},n-p^{*}-k^{*}-1} $$</span>
<span id="cb34-346"><a href="#cb34-346" aria-hidden="true" tabindex="-1"></a>$$ F = \frac{<span class="co">[</span><span class="ot">(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})^T(\mathbf{c}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}^T)^{-1}(\mathbf{c}\hat{\boldsymbol{\beta}}-\mathbf{d})/r</span><span class="co">]</span>}{\hat{\sigma}^2_{Y|X}} \sim F_{r,n-p-1} $$</span>
<span id="cb34-347"><a href="#cb34-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-348"><a href="#cb34-348" aria-hidden="true" tabindex="-1"></a>From our notation we see for the partial F-test that the total number of parameters in the full model is $p^{*}+k^{*}$; whereas in the GLH F-test it is just $p$. </span>
<span id="cb34-349"><a href="#cb34-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-350"><a href="#cb34-350" aria-hidden="true" tabindex="-1"></a>Further, for the partial F-test $k^{*}$ is the number of parameters removed from the full model; whereas in the GLH F-test $r$ is the rank of $\mathbf{c}$: </span>
<span id="cb34-351"><a href="#cb34-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-352"><a href="#cb34-352" aria-hidden="true" tabindex="-1"></a>\begin{bmatrix}</span>
<span id="cb34-353"><a href="#cb34-353" aria-hidden="true" tabindex="-1"></a>0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb34-354"><a href="#cb34-354" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb34-355"><a href="#cb34-355" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 <span class="sc">\\</span></span>
<span id="cb34-356"><a href="#cb34-356" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 0 &amp; 1</span>
<span id="cb34-357"><a href="#cb34-357" aria-hidden="true" tabindex="-1"></a>\end{bmatrix} </span>
<span id="cb34-358"><a href="#cb34-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-359"><a href="#cb34-359" aria-hidden="true" tabindex="-1"></a>where each column represents a beta coefficient, including the intercept, and each row represents a different hypothesis test being conducted jointly/simultaneously). </span>
<span id="cb34-360"><a href="#cb34-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-361"><a href="#cb34-361" aria-hidden="true" tabindex="-1"></a>For completeness, the null hypothesis the GLH is testing is:</span>
<span id="cb34-362"><a href="#cb34-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-363"><a href="#cb34-363" aria-hidden="true" tabindex="-1"></a>$$ H_0 \colon \; \mathbf{c}\boldsymbol{\beta} = \mathbf{d} \implies \begin{bmatrix}</span>
<span id="cb34-364"><a href="#cb34-364" aria-hidden="true" tabindex="-1"></a>0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb34-365"><a href="#cb34-365" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb34-366"><a href="#cb34-366" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 <span class="sc">\\</span></span>
<span id="cb34-367"><a href="#cb34-367" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 0 &amp; 1</span>
<span id="cb34-368"><a href="#cb34-368" aria-hidden="true" tabindex="-1"></a>\end{bmatrix} \begin{bmatrix} \beta_0 <span class="sc">\\</span> \beta_{former} <span class="sc">\\</span> \beta_{current} <span class="sc">\\</span> \beta_{bmi} <span class="sc">\\</span> \beta_{age} \end{bmatrix} = \begin{bmatrix} 0 <span class="sc">\\</span> 0 <span class="sc">\\</span> 0 <span class="sc">\\</span> 0 \end{bmatrix}  $$</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>