<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Kaizer">

<title>Alex Kaizer - Interpreting Polynomial Regression Models, Selecting Your Highest Order Polynomial Term, and Calculus in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/size.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/academicons-1.9.1/css/academicons.css" rel="stylesheet">

<link rel="icon" type="image/png" href="./files/favicon.ico">

<script type="text/javascript">
function setBrand() {
document.getElementsByClassName("navbar-brand")[0].href="https://www.alexkaizer.com";
}
window.onload = setBrand;
</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5PBG7BL207"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5PBG7BL207');
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Alex Kaizer</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/research" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/publications" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/teaching" rel="" target="">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6618" rel="" target="">
 <span class="dropdown-text">BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6611" rel="" target="">
 <span class="dropdown-text">BIOS 6611</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/study_design_berd" rel="" target="">
 <span class="dropdown-text">BERD Study Design Short Course</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/adaptivetrials_sc" rel="" target="">
 <span class="dropdown-text">WNAR Adaptive and Bayesian Clinical Trial Design Short Course</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bios-6618" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">BIOS 6618</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bios-6618">    
        <li>
    <a class="dropdown-item" href="../../index.html" rel="" target="">
 <span class="dropdown-text">Home</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../bios_6618_materials" rel="" target="">
 <span class="dropdown-text">Materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../journal_of_bios_6618" rel="" target="">
 <span class="dropdown-text">Journal of BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../recitation" rel="" target="">
 <span class="dropdown-text">Recitation Questions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs" rel="" target="">
 <span class="dropdown-text">Labs and Practice Problems</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:alex.kaizer@cuanschutz.edu" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=ICpH74EAAAAJ&amp;hl=en" rel="" target="">
 <span class="menu-text"><i class="ai  ai-google-scholar ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="http://github.com/alexbiostats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/files/Alex_CV.pdf" rel="" target="">
 <span class="menu-text"><i class="ai  ai-cv ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/alex-kaizer/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link active" data-scroll-target="#polynomial-regression">Polynomial Regression</a>
  <ul class="collapse">
  <li><a href="#interpretation-of-trends" id="toc-interpretation-of-trends" class="nav-link" data-scroll-target="#interpretation-of-trends">Interpretation of Trends</a>
  <ul class="collapse">
  <li><a href="#calculus-in-r" id="toc-calculus-in-r" class="nav-link" data-scroll-target="#calculus-in-r">Calculus in R</a></li>
  </ul></li>
  <li><a href="#polynomial-regression-and-parsimony" id="toc-polynomial-regression-and-parsimony" class="nav-link" data-scroll-target="#polynomial-regression-and-parsimony">Polynomial Regression and Parsimony</a>
  <ul class="collapse">
  <li><a href="#partial-f-test-on-raw-polynomials" id="toc-partial-f-test-on-raw-polynomials" class="nav-link" data-scroll-target="#partial-f-test-on-raw-polynomials">Partial F-test on Raw Polynomials</a></li>
  <li><a href="#lack-of-fit-f-test" id="toc-lack-of-fit-f-test" class="nav-link" data-scroll-target="#lack-of-fit-f-test">Lack-of-Fit F-test</a></li>
  <li><a href="#orthogonal-polynomial-contrasts" id="toc-orthogonal-polynomial-contrasts" class="nav-link" data-scroll-target="#orthogonal-polynomial-contrasts">Orthogonal Polynomial Contrasts</a></li>
  <li><a href="#which-model-to-use" id="toc-which-model-to-use" class="nav-link" data-scroll-target="#which-model-to-use">Which Model to Use?</a></li>
  </ul></li>
  <li><a href="#other-modeling-approaches" id="toc-other-modeling-approaches" class="nav-link" data-scroll-target="#other-modeling-approaches">Other Modeling Approaches</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Interpreting Polynomial Regression Models, Selecting Your Highest Order Polynomial Term, and Calculus in R</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Alex Kaizer </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Colorado-Anschutz Medical Campus
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<p>This page is part of the University of Colorado-Anschutz Medical Campus’ <a href="../../recitation/index.html">BIOS 6618 Recitation</a> collection. To view other questions, you can view the <a href="../../recitation/index.html">BIOS 6618 Recitation</a> collection page or use the search bar to look for keywords.</p>
<section id="polynomial-regression" class="level1">
<h1>Polynomial Regression</h1>
<p>As a motivating example, let’s consider a example from the NHANES 2015-2016 cycle. We are interested in the association between sex hormone binding globulin (SHBG) and age in years for males 6-80 years old from the NHANES 2015-2016 cycle (<span class="math inline">\(n=3390\)</span> with SHBG). Here we will fit our models using the <code>poly()</code> function with <code>raw=T</code> to mimic a model with higher order terms:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r fold-hide code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../.data/nhanes1516_sexhormone.csv'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="fu">which</span>(dat<span class="sc">$</span>MALE<span class="sc">==</span>T),]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="sc">!</span><span class="fu">is.na</span>(dat<span class="sc">$</span>SHBG),]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>dat<span class="sc">$</span>RIDAGEYR, <span class="at">y=</span>dat<span class="sc">$</span>SHBG, <span class="at">xlab=</span><span class="st">'Age (Years)'</span>, <span class="at">ylab=</span><span class="st">'SHBG (nmol/L)'</span>, <span class="at">col=</span><span class="st">'gray85'</span>, <span class="at">cex.lab=</span><span class="fl">0.8</span>, <span class="at">cex.axis=</span><span class="fl">0.8</span>, <span class="at">cex=</span><span class="fl">0.5</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span>RIDAGEYR, <span class="at">data=</span>dat)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>mod_poly2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">2</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>mod_poly3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">3</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>mod_poly4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">4</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="dv">6</span><span class="sc">:</span><span class="dv">80</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_lm, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'black'</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly2, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'orangered2'</span>, <span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly3, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'red4'</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly4, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'orange'</span>, <span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'top'</span>, <span class="at">horiz=</span>T, <span class="at">bty=</span><span class="st">'n'</span>, <span class="at">xpd=</span>T, <span class="at">inset=</span><span class="sc">-</span><span class="fl">0.15</span>, <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">4</span>), <span class="at">lwd=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">legend=</span><span class="fu">c</span>(<span class="st">'Order 1'</span>,<span class="st">'Order 2'</span>,<span class="st">'Order 3'</span>,<span class="st">'Order 4'</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">'black'</span>,<span class="st">'orangered2'</span>,<span class="st">'red4'</span>,<span class="st">'orange'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="interpretation-of-trends" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-trends">Interpretation of Trends</h2>
<p>Let’s examine the model fit for each of the models:</p>
<ol type="1">
<li><span class="math inline">\(\hat{Y} = 55.903 + -0.095 X\)</span></li>
<li><span class="math inline">\(\hat{Y} = 102.362 + -3.351 X + 0.039 X^2\)</span></li>
<li><span class="math inline">\(\hat{Y} = 152.581 + -9.177 X + 0.203 X^2 + -0.001 X^3\)</span></li>
<li><span class="math inline">\(\hat{Y} = 221.308 + -20.371 X + 0.730 X^2 + -0.011 X^3 + 0.00005 X^4\)</span></li>
</ol>
<p>Our simple linear regression model (i.e., a polynomial regression with order 1), is easy to interpret and follows our usual pattern: <em>For a 1 year increase in age, SHBG significantly decreases on average by 0.095 nmol/L (95% CI: 0.042 to 0.148 nmol/L decrease; p&lt;0.001).</em></p>
<p>However, the interpretations of any models with higher order terms is made far more challenging. Now, the expected change in our outcome will also depend on the value of both <span class="math inline">\(X\)</span> and <span class="math inline">\(X^2\)</span> since <span class="math inline">\(X=20 \implies X^2=400\)</span> which is not an equivalent change to <span class="math inline">\(X=60 \implies X^2=3600\)</span>. In other words, a one-unit increase in age will have different effects depending on the starting point given its <em>non-linear</em> trend over age.</p>
<p>Making it a “brief, but complete” interpretation is a little more challenging since we cannot meaningful interpret the beta coefficients and individual p-values are affected by multicollinearity (in this model with raw, not orthogonal, polynomial terms). However, you consider a variety of approaches:</p>
<ul>
<li>One of the easiest ways to interpret these models is to plot the trend and describe the trends.</li>
<li>Evaluate the overall contribution of the polynomials (e.g., with a partial <span class="math inline">\(F\)</span>-test).</li>
<li>Describe the predicted outcome at select predictors (e.g., using GLHT; may be challenging if adjusting for other variables since those would also have an influence).</li>
<li>Calculate the local/global min max, estimate inflection points, or estimate rates of change using calculus.</li>
</ul>
<section id="calculus-in-r" class="level3">
<h3 class="anchored" data-anchor-id="calculus-in-r">Calculus in R</h3>
<p>Consider our quadratic polynomial. We can estimate the min/max point by taking the first order derivative with respect to <span class="math inline">\(X\)</span> of our model and setting it equal to 0, then solving for <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[\begin{align*}
\hat{Y} = f(X) &amp;= 102.362 + -3.351 X + 0.039 X^2 \\
f'(X) &amp;=  -3.351 + 2 \times 0.039 X = -3.351 + 0.078 X \\
0 &amp;= -3.351 + 0.078 X \implies X = \frac{3.351}{0.078} = 42.96
\end{align*}\]</span></p>
<p>If we plug this back into our regression equation we get the predicted minimum: <span class="math inline">\(\hat{Y} = 102.362 + -3.351(42.96) + 0.039(42.96)^2 = 30.38\)</span> nmol/L of SHBG.</p>
<p>R also has the ability to do this calculus for us:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first write our expression</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">expression</span>( <span class="fl">102.362</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">3.351</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.039</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># then use the D() function and specify the variable to derive with respect to</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">D</span>(f, <span class="st">'x'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>0.039 * (2 * x) - 3.351</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uniroot() function calculates where it equals 0 given a range of X values</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>find_root <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">eval</span>( <span class="fu">D</span>(f,<span class="st">'x'</span>) )</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">uniroot</span>(find_root, <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">80</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$root
[1] 42.96154

$f.root
[1] -4.440892e-16

$iter
[1] 2

$init.it
[1] NA

$estim.prec
[1] 6.103516e-05</code></pre>
</div>
</div>
<p>More generally, we can use <code>mosaicCalc::Zeros()</code> to find all candidate points:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaicCalc)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># first write our expressions for the first order derivatives, then findZeros</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>f2 <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fl">102.362</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">3.351</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.039</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">~</span> x )</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f2</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   x
1 43</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>f3 <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fl">152.581</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">9.177</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.203</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.001</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">3</span> <span class="sc">~</span> x )</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f3</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        x
1 28.6824</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>f4 <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fl">221.308</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">20.371</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.730</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.011</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">3</span> <span class="sc">+</span> <span class="fl">0.00005</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">4</span> <span class="sc">~</span> x )</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f4</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>numeric(0)</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># notice that none were found for f4 due to rounding, we can instead use paste0() and pull the coefficients directly:</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>f4_eq <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">coef</span>(mod_poly4)[<span class="dv">1</span>], <span class="st">'+'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">2</span>], <span class="st">'*x +'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">3</span>], <span class="st">'*x^2 +'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">4</span>], <span class="st">'*x^3 +'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">5</span>], <span class="st">'*x^4 ~ x'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>f4_eq <span class="co"># print regression equation with more decimals to check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "221.308434170064+-20.3710021214272*x +0.729584043956372*x^2 +-0.0105089215893748*x^3 +5.36746951571261e-05*x^4 ~ x"</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>f4_coef <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fu">as.formula</span>(f4_eq) )</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f4_coef</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        x
1 25.8878</code></pre>
</div>
</div>
<p>From these models, we could interpret that the minimum SHBG is expected, on average, at 43 (quadratic), 28.7 (cubic), or 25.9 (cuartic) years old. We could also estimate the minimum (and 95% CI) by plugging it into our regression equation.</p>
</section>
</section>
<section id="polynomial-regression-and-parsimony" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-regression-and-parsimony">Polynomial Regression and Parsimony</h2>
<p>When we fit a regression, we want to find a model that avoids under- and over-fitting the data. Further, we also want to consider the parsimony of our model (i.e., does it have to be as complex or could it be simpler?).</p>
<p>Parsimony in the context of polynomial regression means considering models with fewer higher order terms both to avoid overfitting and having extra, potentially unnecessary, coefficients in our model.</p>
<p>The evaluation of parsimony is often more subjective, but we can use quantitative approaches to determine how many polynomial terms are statistically justified as a starting place.</p>
<section id="partial-f-test-on-raw-polynomials" class="level3">
<h3 class="anchored" data-anchor-id="partial-f-test-on-raw-polynomials">Partial F-test on Raw Polynomials</h3>
<p>If we fit models on our raw polynomials, we may have concerns about collinearity, which could make it challenging to identify the appropriate number of terms.</p>
<p>Let’s start by fitting a sequence of models and running partial F-tests:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span>RIDAGEYR, <span class="at">data=</span>dat)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>mod_poly2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">2</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>mod_poly3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">3</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>mod_poly4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">4</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>mod_poly5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">5</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>mod_poly6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">6</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>mod_poly7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">7</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>mod_poly8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">8</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>mod_poly9 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">9</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>mod_poly10 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">10</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>mod_poly11 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">11</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># partial F-tests (i.e., equivalent to observing coefficients and analyzing highest order t-statistic and p-value)</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_lm,mod_poly2,mod_poly3,mod_poly4,mod_poly5,mod_poly6,mod_poly7,mod_poly8,mod_poly9,mod_poly10,mod_poly11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model  1: SHBG ~ RIDAGEYR
Model  2: SHBG ~ poly(RIDAGEYR, 2, raw = T)
Model  3: SHBG ~ poly(RIDAGEYR, 3, raw = T)
Model  4: SHBG ~ poly(RIDAGEYR, 4, raw = T)
Model  5: SHBG ~ poly(RIDAGEYR, 5, raw = T)
Model  6: SHBG ~ poly(RIDAGEYR, 6, raw = T)
Model  7: SHBG ~ poly(RIDAGEYR, 7, raw = T)
Model  8: SHBG ~ poly(RIDAGEYR, 8, raw = T)
Model  9: SHBG ~ poly(RIDAGEYR, 9, raw = T)
Model 10: SHBG ~ poly(RIDAGEYR, 10, raw = T)
Model 11: SHBG ~ poly(RIDAGEYR, 11, raw = T)
   Res.Df     RSS Df Sum of Sq         F    Pr(&gt;F)    
1    3388 4286690                                     
2    3387 3276833  1   1009857 1351.0353 &lt; 2.2e-16 ***
3    3386 2873485  1    403348  539.6180 &lt; 2.2e-16 ***
4    3385 2618205  1    255281  341.5269 &lt; 2.2e-16 ***
5    3384 2573535  1     44670   59.7615 1.403e-14 ***
6    3383 2558283  1     15252   20.4048 6.482e-06 ***
7    3382 2550263  1      8020   10.7289  0.001065 ** 
8    3381 2537447  1     12817   17.1467 3.545e-05 ***
9    3380 2529858  1      7589   10.1524  0.001454 ** 
10   3379 2525059  1      4799    6.4198  0.011330 *  
11   3378 2524950  1       109    0.1465  0.701973    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on these comparisons, it seems that a model with order 10 is considered the “best”.</p>
</section>
<section id="lack-of-fit-f-test" class="level3">
<h3 class="anchored" data-anchor-id="lack-of-fit-f-test">Lack-of-Fit F-test</h3>
<p>When we have replicate observations at each level, we can also estimate the pure versus model error and use it to identify the number of polynomial terms. In the case of our NHANES data, age is only provided as a whole number and we could assume we have lots of categorical data:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit saturated model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mod_pure <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG <span class="sc">~</span> <span class="fu">as.factor</span>(RIDAGEYR), <span class="at">data=</span>dat)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># save p-values from partial F-tests</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_lm)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly2)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly3)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly4)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly5)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly6)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>p7 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly7)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>p8 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly8)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>p9 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly9)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>p10 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly10)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>p11 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly11)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># print p-values</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">'Order 1'</span><span class="ot">=</span>p1, <span class="st">'Order 2'</span><span class="ot">=</span>p2, <span class="st">'Order 3'</span><span class="ot">=</span>p3, <span class="st">'Order 4'</span><span class="ot">=</span>p4, <span class="st">'Order 5'</span><span class="ot">=</span>p5, <span class="st">'Order 6'</span><span class="ot">=</span>p6, <span class="st">'Order 7'</span><span class="ot">=</span>p7, <span class="st">'Order 8'</span><span class="ot">=</span>p8, <span class="st">'Order 9'</span><span class="ot">=</span>p9, <span class="st">'Order 10'</span><span class="ot">=</span>p10, <span class="st">'Order 11'</span><span class="ot">=</span>p11),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Order 1  Order 2  Order 3  Order 4  Order 5  Order 6  Order 7  Order 8 
  0.0000   0.0000   0.0000   0.0000   0.0001   0.0044   0.0234   0.2086 
 Order 9 Order 10 Order 11 
  0.4763   0.6655   0.6374 </code></pre>
</div>
</div>
<p>Our results indicate that an octic (order 8) polynomial regression is not significantly better than a septic (order 7) polynomial regression. However, the septic (order 7) is better than the sextic (order 6).</p>
<p>This differs from our approach using just raw polynomials, where we chose a more complex order 10 model as “best”.</p>
</section>
<section id="orthogonal-polynomial-contrasts" class="level3">
<h3 class="anchored" data-anchor-id="orthogonal-polynomial-contrasts">Orthogonal Polynomial Contrasts</h3>
<p>An approach we alluded to, but didn’t delve into details, is the construction of orthogonal polynomial contrasts which remove the correlation between polynomial terms. While the math behind it is a bit lengthy, it is fairly easy to implement in <code>R</code> by removing our <code>raw=T</code> argument (or setting equal to the default <code>FALSE</code>) from <code>poly()</code>:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mod_orth1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">1</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mod_orth2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">2</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>mod_orth3 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">3</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>mod_orth4 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">4</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>mod_orth5 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">5</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>mod_orth6 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">6</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>mod_orth7 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">7</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>mod_orth8 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">8</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>mod_orth9 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">9</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>mod_orth10 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">10</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>mod_orth11 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">11</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># print summary of Order 11 polynomial regression</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_orth11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SHBG ~ poly(RIDAGEYR, 11, raw = F), data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-100.74  -15.81   -4.69   10.99  254.05 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     52.2391     0.4696 111.250  &lt; 2e-16 ***
poly(RIDAGEYR, 11, raw = F)1  -125.7103    27.3399  -4.598 4.42e-06 ***
poly(RIDAGEYR, 11, raw = F)2  1004.9164    27.3399  36.756  &lt; 2e-16 ***
poly(RIDAGEYR, 11, raw = F)3  -635.0966    27.3399 -23.230  &lt; 2e-16 ***
poly(RIDAGEYR, 11, raw = F)4   505.2531    27.3399  18.480  &lt; 2e-16 ***
poly(RIDAGEYR, 11, raw = F)5  -211.3525    27.3399  -7.731 1.40e-14 ***
poly(RIDAGEYR, 11, raw = F)6   123.4989    27.3399   4.517 6.48e-06 ***
poly(RIDAGEYR, 11, raw = F)7    89.5518    27.3399   3.276  0.00107 ** 
poly(RIDAGEYR, 11, raw = F)8  -113.2105    27.3399  -4.141 3.54e-05 ***
poly(RIDAGEYR, 11, raw = F)9    87.1125    27.3399   3.186  0.00145 ** 
poly(RIDAGEYR, 11, raw = F)10  -69.2721    27.3399  -2.534  0.01133 *  
poly(RIDAGEYR, 11, raw = F)11   10.4627    27.3399   0.383  0.70197    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27.34 on 3378 degrees of freedom
Multiple R-squared:  0.4131,    Adjusted R-squared:  0.4112 
F-statistic: 216.2 on 11 and 3378 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see that the 11th order polynomial is the first to have a p-value &gt;0.05. This agrees with our raw polynomial calculation that Order 10 would be “best”.</p>
<p>With the correlation removed between our predictors, we can also see that a sequence of F-tests for adding each higher order term results in the same p-values:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print ANOVA comparisons adding 1 higher orthogonal term, notice p-values match those from the regression coefficient table for mod_orth11</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_orth1,mod_orth2,mod_orth3,mod_orth4,mod_orth5,mod_orth6,mod_orth7,mod_orth8,mod_orth9,mod_orth10,mod_orth11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model  1: SHBG ~ poly(RIDAGEYR, 1, raw = F)
Model  2: SHBG ~ poly(RIDAGEYR, 2, raw = F)
Model  3: SHBG ~ poly(RIDAGEYR, 3, raw = F)
Model  4: SHBG ~ poly(RIDAGEYR, 4, raw = F)
Model  5: SHBG ~ poly(RIDAGEYR, 5, raw = F)
Model  6: SHBG ~ poly(RIDAGEYR, 6, raw = F)
Model  7: SHBG ~ poly(RIDAGEYR, 7, raw = F)
Model  8: SHBG ~ poly(RIDAGEYR, 8, raw = F)
Model  9: SHBG ~ poly(RIDAGEYR, 9, raw = F)
Model 10: SHBG ~ poly(RIDAGEYR, 10, raw = F)
Model 11: SHBG ~ poly(RIDAGEYR, 11, raw = F)
   Res.Df     RSS Df Sum of Sq         F    Pr(&gt;F)    
1    3388 4286690                                     
2    3387 3276833  1   1009857 1351.0353 &lt; 2.2e-16 ***
3    3386 2873485  1    403348  539.6180 &lt; 2.2e-16 ***
4    3385 2618205  1    255281  341.5269 &lt; 2.2e-16 ***
5    3384 2573535  1     44670   59.7615 1.403e-14 ***
6    3383 2558283  1     15252   20.4048 6.482e-06 ***
7    3382 2550263  1      8020   10.7289  0.001065 ** 
8    3381 2537447  1     12817   17.1467 3.545e-05 ***
9    3380 2529858  1      7589   10.1524  0.001454 ** 
10   3379 2525059  1      4799    6.4198  0.011330 *  
11   3378 2524950  1       109    0.1465  0.701973    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>However, if we did a series of partial F-tests comparing to our saturated pure fit model (<code>mod_pure</code>), we’d arrive at the same conclusion as the lack-of-fit <span class="math inline">\(F\)</span>-test that a model with order 7 is “best”:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>o1 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth1)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>o2 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth2)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>o3 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth3)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>o4 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth4)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>o5 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth5)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>o6 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth6)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>o7 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth7)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>o8 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth8)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>o9 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth9)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>o10 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth10)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>o11 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth11)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">'Order 1'</span><span class="ot">=</span>o1, <span class="st">'Order 2'</span><span class="ot">=</span>o2, <span class="st">'Order 3'</span><span class="ot">=</span>o3, <span class="st">'Order 4'</span><span class="ot">=</span>o4, <span class="st">'Order 5'</span><span class="ot">=</span>o5, <span class="st">'Order 6'</span><span class="ot">=</span>o6, <span class="st">'Order 7'</span><span class="ot">=</span>o7, <span class="st">'Order 8'</span><span class="ot">=</span>o8, <span class="st">'Order 9'</span><span class="ot">=</span>o9, <span class="st">'Order 10'</span><span class="ot">=</span>o10, <span class="st">'Order 11'</span><span class="ot">=</span>o11),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Order 1  Order 2  Order 3  Order 4  Order 5  Order 6  Order 7  Order 8 
  0.0000   0.0000   0.0000   0.0000   0.0001   0.0044   0.0234   0.2086 
 Order 9 Order 10 Order 11 
  0.4763   0.6655   0.6374 </code></pre>
</div>
</div>
<p>Here, since we are comparing to the saturated model, we can be fairly confident that order 7 may be best. If we did not have a saturated model (e.g., no replicates), we may have chosen the order 10 as optimal based on the orthogonal polynomials (and potentially decided a lower order based on parsimony).</p>
</section>
<section id="which-model-to-use" class="level3">
<h3 class="anchored" data-anchor-id="which-model-to-use">Which Model to Use?</h3>
<p>We saw that the raw polynomial approach suggested a model with Order 10, and that both saturated or orthogonal polynomial approaches identified a model with Order 7. Both of these are quite high orders. We may also wish to evaluate other summaries, like the adjusted <span class="math inline">\(R^2\)</span> value:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r fold-hide code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>rawr2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Order 1'</span><span class="ot">=</span><span class="fu">summary</span>(mod_lm)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 2'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly2)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 3'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly3)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 4'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly4)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 5'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly5)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 6'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly6)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 7'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly7)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 8'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly8)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 9'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly9)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 10'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly10)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 11'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly11)<span class="sc">$</span>adj.r.squared)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>ortr2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Orth Order 1'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth1)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 2'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth2)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 3'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth3)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 4'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth4)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 5'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth5)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 6'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth6)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 7'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth7)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 8'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth8)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 9'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth9)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 10'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth10)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 11'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth11)<span class="sc">$</span>adj.r.squared)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="st">'Raw'</span> <span class="ot">=</span> rawr2, <span class="st">'Orthogonal'</span> <span class="ot">=</span> ortr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Order 1   Order 2   Order 3   Order 4   Order 5   Order 6
Raw        0.003378928 0.2379376 0.3315431 0.3907489 0.4009665 0.4043407
Orthogonal 0.003378928 0.2379376 0.3315431 0.3907489 0.4009665 0.4043407
             Order 7   Order 8   Order 9  Order 10  Order 11
Raw        0.4060323 0.4088426 0.4104361 0.4113803 0.4112316
Orthogonal 0.4060323 0.4088426 0.4104361 0.4113803 0.4112316</code></pre>
</div>
</div>
<p>We can note 2 things from these <span class="math inline">\(R^2_{adj}\)</span> results:</p>
<ol type="1">
<li>The estimated percent of variability explained by each raw and orthogonal polynomial model of the same order <em>are identical</em>! This is because while the orthogonal polynomials transform our predictors to remove collinearity, the same data/information is included in the model.</li>
<li>It appears that after Order 4, the jumps in <span class="math inline">\(R^2_{adj}\)</span> get smaller and smaller. This may suggest a model with Order 4 may be sufficient.</li>
</ol>
<p>To evaluate, let’s compare the some models while also illustrating the dangers of extrapolation:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r fold-hide code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>dat<span class="sc">$</span>RIDAGEYR, <span class="at">y=</span>dat<span class="sc">$</span>SHBG, <span class="at">xlab=</span><span class="st">'Age (Years)'</span>, <span class="at">ylab=</span><span class="st">'SHBG (nmol/L)'</span>, <span class="at">col=</span><span class="st">'gray85'</span>, <span class="at">cex.lab=</span><span class="fl">0.8</span>, <span class="at">cex.axis=</span><span class="fl">0.8</span>, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">100</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10</span><span class="sc">:</span><span class="dv">100</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly4, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'black'</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly7, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'orangered2'</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly10, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly11, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'purple'</span>, <span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'top'</span>, <span class="at">horiz=</span>T, <span class="at">bty=</span><span class="st">'n'</span>, <span class="at">xpd=</span>T, <span class="at">inset=</span><span class="sc">-</span><span class="fl">0.15</span>, <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="at">lwd=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">legend=</span><span class="fu">c</span>(<span class="st">'Order 4'</span>,<span class="st">'Order 7'</span>,<span class="st">'Order 10'</span>,<span class="st">'Order 11'</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">'black'</span>,<span class="st">'orangered2'</span>,<span class="st">'blue'</span>,<span class="st">'purple'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>First, note extrapolation beyond our observed data quickly gets crazy and shouldn’t be done for our polynomial models.</p>
<p>Second, I think the choice of “best” Order 4 or Order 7 depends on our own belief of how well it fits the data without being potentially overfit. Further, Orders 10 and 11 are quite similar to Order 7, so even if we had used a method and chosen Order 10, it wouldn’t be wrong (just overly complex).</p>
</section>
</section>
<section id="other-modeling-approaches" class="level2">
<h2 class="anchored" data-anchor-id="other-modeling-approaches">Other Modeling Approaches</h2>
<p>There are also other modeling strategies that may be helpful beyond polynomial regression and are covered in some other lectures:</p>
<ul>
<li>Spline modeling provides more flexibility for the trends (but is still hard to interpret)</li>
<li>Piecewise regression models are more interpretable and identify break/changepoints where the trend changes/shifts</li>
</ul>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb29" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Interpreting Polynomial Regression Models, Selecting Your Highest Order Polynomial Term, and Calculus in R"</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Alex Kaizer</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co">  roles: "Instructor"</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co">  affiliation: University of Colorado-Anschutz Medical Campus</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc_float:</span><span class="co"> true</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> left</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap </span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=F, message=F, warning=F}</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>This page is part of the University of Colorado-Anschutz Medical Campus' <span class="co">[</span><span class="ot">BIOS 6618 Recitation</span><span class="co">](/recitation/index.qmd)</span> collection. To view other questions, you can view the <span class="co">[</span><span class="ot">BIOS 6618 Recitation</span><span class="co">](/recitation/index.qmd)</span> collection page or use the search bar to look for keywords.</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a><span class="fu"># Polynomial Regression</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>As a motivating example, let's consider a example from the NHANES 2015-2016 cycle. We are interested in the association between sex hormone binding globulin (SHBG) and age in years for males 6-80 years old from the NHANES 2015-2016 cycle ($n=3390$ with SHBG). Here we will fit our models using the <span class="in">`poly()`</span> function with <span class="in">`raw=T`</span> to mimic a model with higher order terms:</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-hide'}</span></span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../.data/nhanes1516_sexhormone.csv'</span>)</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="fu">which</span>(dat<span class="sc">$</span>MALE<span class="sc">==</span>T),]</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="sc">!</span><span class="fu">is.na</span>(dat<span class="sc">$</span>SHBG),]</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>dat<span class="sc">$</span>RIDAGEYR, <span class="at">y=</span>dat<span class="sc">$</span>SHBG, <span class="at">xlab=</span><span class="st">'Age (Years)'</span>, <span class="at">ylab=</span><span class="st">'SHBG (nmol/L)'</span>, <span class="at">col=</span><span class="st">'gray85'</span>, <span class="at">cex.lab=</span><span class="fl">0.8</span>, <span class="at">cex.axis=</span><span class="fl">0.8</span>, <span class="at">cex=</span><span class="fl">0.5</span>)</span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span>RIDAGEYR, <span class="at">data=</span>dat)</span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>mod_poly2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">2</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>mod_poly3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">3</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>mod_poly4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">4</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="dv">6</span><span class="sc">:</span><span class="dv">80</span></span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_lm, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'black'</span>)</span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly2, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'orangered2'</span>, <span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly3, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'red4'</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly4, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'orange'</span>, <span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'top'</span>, <span class="at">horiz=</span>T, <span class="at">bty=</span><span class="st">'n'</span>, <span class="at">xpd=</span>T, <span class="at">inset=</span><span class="sc">-</span><span class="fl">0.15</span>, <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">4</span>), <span class="at">lwd=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">legend=</span><span class="fu">c</span>(<span class="st">'Order 1'</span>,<span class="st">'Order 2'</span>,<span class="st">'Order 3'</span>,<span class="st">'Order 4'</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">'black'</span>,<span class="st">'orangered2'</span>,<span class="st">'red4'</span>,<span class="st">'orange'</span>))</span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation of Trends</span></span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a>Let's examine the model fit for each of the models:</span>
<span id="cb29-51"><a href="#cb29-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-52"><a href="#cb29-52" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>$\hat{Y} = 55.903 + -0.095 X$</span>
<span id="cb29-53"><a href="#cb29-53" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>$\hat{Y} = 102.362 + -3.351 X + 0.039 X^2$</span>
<span id="cb29-54"><a href="#cb29-54" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>$\hat{Y} = 152.581 + -9.177 X + 0.203 X^2 + -0.001 X^3$</span>
<span id="cb29-55"><a href="#cb29-55" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>$\hat{Y} = 221.308 + -20.371 X + 0.730 X^2 + -0.011 X^3 + 0.00005 X^4$</span>
<span id="cb29-56"><a href="#cb29-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-57"><a href="#cb29-57" aria-hidden="true" tabindex="-1"></a>Our simple linear regression model (i.e., a polynomial regression with order 1), is easy to interpret and follows our usual pattern: *For a 1 year increase in age, SHBG significantly decreases on average by 0.095 nmol/L (95% CI: 0.042 to 0.148 nmol/L decrease; p&lt;0.001).*</span>
<span id="cb29-58"><a href="#cb29-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-59"><a href="#cb29-59" aria-hidden="true" tabindex="-1"></a>However, the interpretations of any models with higher order terms is made far more challenging. Now, the expected change in our outcome will also depend on the value of both $X$ and $X^2$ since $X=20 \implies X^2=400$ which is not an equivalent change to $X=60 \implies X^2=3600$. In other words, a one-unit increase in age will have different effects depending on the starting point given its *non-linear* trend over age.</span>
<span id="cb29-60"><a href="#cb29-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-61"><a href="#cb29-61" aria-hidden="true" tabindex="-1"></a>Making it a "brief, but complete" interpretation is a little more challenging since we cannot meaningful interpret the beta coefficients and individual p-values are affected by multicollinearity (in this model with raw, not orthogonal, polynomial terms). However, you consider a variety of approaches:</span>
<span id="cb29-62"><a href="#cb29-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-63"><a href="#cb29-63" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>One of the easiest ways to interpret these models is to plot the trend and describe the trends.</span>
<span id="cb29-64"><a href="#cb29-64" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Evaluate the overall contribution of the polynomials (e.g., with a partial $F$-test).</span>
<span id="cb29-65"><a href="#cb29-65" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Describe the predicted outcome at select predictors (e.g., using GLHT; may be challenging if adjusting for other variables since those would also have an influence).</span>
<span id="cb29-66"><a href="#cb29-66" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Calculate the local/global min max, estimate inflection points, or estimate rates of change using calculus.</span>
<span id="cb29-67"><a href="#cb29-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-68"><a href="#cb29-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-69"><a href="#cb29-69" aria-hidden="true" tabindex="-1"></a><span class="fu">### Calculus in R</span></span>
<span id="cb29-70"><a href="#cb29-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-71"><a href="#cb29-71" aria-hidden="true" tabindex="-1"></a>Consider our quadratic polynomial. We can estimate the min/max point by taking the first order derivative with respect to $X$ of our model and setting it equal to 0, then solving for $X$:</span>
<span id="cb29-72"><a href="#cb29-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-73"><a href="#cb29-73" aria-hidden="true" tabindex="-1"></a>$$\begin{align*} </span>
<span id="cb29-74"><a href="#cb29-74" aria-hidden="true" tabindex="-1"></a>\hat{Y} = f(X) &amp;= 102.362 + -3.351 X + 0.039 X^2 <span class="sc">\\</span> </span>
<span id="cb29-75"><a href="#cb29-75" aria-hidden="true" tabindex="-1"></a>f'(X) &amp;=  -3.351 + 2 \times 0.039 X = -3.351 + 0.078 X <span class="sc">\\</span></span>
<span id="cb29-76"><a href="#cb29-76" aria-hidden="true" tabindex="-1"></a>0 &amp;= -3.351 + 0.078 X \implies X = \frac{3.351}{0.078} = 42.96</span>
<span id="cb29-77"><a href="#cb29-77" aria-hidden="true" tabindex="-1"></a>\end{align*}$$</span>
<span id="cb29-78"><a href="#cb29-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-79"><a href="#cb29-79" aria-hidden="true" tabindex="-1"></a>If we plug this back into our regression equation we get the predicted minimum: $\hat{Y} = 102.362 + -3.351(42.96) + 0.039(42.96)^2 = 30.38$ nmol/L of SHBG.</span>
<span id="cb29-80"><a href="#cb29-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-81"><a href="#cb29-81" aria-hidden="true" tabindex="-1"></a>R also has the ability to do this calculus for us:</span>
<span id="cb29-82"><a href="#cb29-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-85"><a href="#cb29-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-86"><a href="#cb29-86" aria-hidden="true" tabindex="-1"></a><span class="co"># first write our expression</span></span>
<span id="cb29-87"><a href="#cb29-87" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">expression</span>( <span class="fl">102.362</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">3.351</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.039</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb29-88"><a href="#cb29-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-89"><a href="#cb29-89" aria-hidden="true" tabindex="-1"></a><span class="co"># then use the D() function and specify the variable to derive with respect to</span></span>
<span id="cb29-90"><a href="#cb29-90" aria-hidden="true" tabindex="-1"></a><span class="fu">D</span>(f, <span class="st">'x'</span>)</span>
<span id="cb29-91"><a href="#cb29-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-92"><a href="#cb29-92" aria-hidden="true" tabindex="-1"></a><span class="co"># uniroot() function calculates where it equals 0 given a range of X values</span></span>
<span id="cb29-93"><a href="#cb29-93" aria-hidden="true" tabindex="-1"></a>find_root <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">eval</span>( <span class="fu">D</span>(f,<span class="st">'x'</span>) )</span>
<span id="cb29-94"><a href="#cb29-94" aria-hidden="true" tabindex="-1"></a><span class="fu">uniroot</span>(find_root, <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">80</span>))</span>
<span id="cb29-95"><a href="#cb29-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-96"><a href="#cb29-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-97"><a href="#cb29-97" aria-hidden="true" tabindex="-1"></a>More generally, we can use <span class="in">`mosaicCalc::Zeros()`</span> to find all candidate points:</span>
<span id="cb29-98"><a href="#cb29-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-99"><a href="#cb29-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=F, message=F}</span></span>
<span id="cb29-100"><a href="#cb29-100" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaicCalc)</span>
<span id="cb29-101"><a href="#cb29-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-102"><a href="#cb29-102" aria-hidden="true" tabindex="-1"></a><span class="co"># first write our expressions for the first order derivatives, then findZeros</span></span>
<span id="cb29-103"><a href="#cb29-103" aria-hidden="true" tabindex="-1"></a>f2 <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fl">102.362</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">3.351</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.039</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">~</span> x )</span>
<span id="cb29-104"><a href="#cb29-104" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f2</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span>
<span id="cb29-105"><a href="#cb29-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-106"><a href="#cb29-106" aria-hidden="true" tabindex="-1"></a>f3 <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fl">152.581</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">9.177</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.203</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.001</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">3</span> <span class="sc">~</span> x )</span>
<span id="cb29-107"><a href="#cb29-107" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f3</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span>
<span id="cb29-108"><a href="#cb29-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-109"><a href="#cb29-109" aria-hidden="true" tabindex="-1"></a>f4 <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fl">221.308</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">20.371</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.730</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.011</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">3</span> <span class="sc">+</span> <span class="fl">0.00005</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">4</span> <span class="sc">~</span> x )</span>
<span id="cb29-110"><a href="#cb29-110" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f4</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span>
<span id="cb29-111"><a href="#cb29-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-112"><a href="#cb29-112" aria-hidden="true" tabindex="-1"></a><span class="co"># notice that none were found for f4 due to rounding, we can instead use paste0() and pull the coefficients directly:</span></span>
<span id="cb29-113"><a href="#cb29-113" aria-hidden="true" tabindex="-1"></a>f4_eq <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">coef</span>(mod_poly4)[<span class="dv">1</span>], <span class="st">'+'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">2</span>], <span class="st">'*x +'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">3</span>], <span class="st">'*x^2 +'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">4</span>], <span class="st">'*x^3 +'</span>, <span class="fu">coef</span>(mod_poly4)[<span class="dv">5</span>], <span class="st">'*x^4 ~ x'</span>)</span>
<span id="cb29-114"><a href="#cb29-114" aria-hidden="true" tabindex="-1"></a>f4_eq <span class="co"># print regression equation with more decimals to check</span></span>
<span id="cb29-115"><a href="#cb29-115" aria-hidden="true" tabindex="-1"></a>f4_coef <span class="ot">&lt;-</span> <span class="fu">D</span>( <span class="fu">as.formula</span>(f4_eq) )</span>
<span id="cb29-116"><a href="#cb29-116" aria-hidden="true" tabindex="-1"></a><span class="fu">findZeros</span>(<span class="fu">f4_coef</span>(x) <span class="sc">~</span> x, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="dv">6</span>, <span class="dv">80</span>))</span>
<span id="cb29-117"><a href="#cb29-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-118"><a href="#cb29-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-119"><a href="#cb29-119" aria-hidden="true" tabindex="-1"></a>From these models, we could interpret that the minimum SHBG is expected, on average, at 43 (quadratic), 28.7 (cubic), or 25.9 (cuartic) years old. We could also estimate the minimum (and 95% CI) by plugging it into our regression equation.</span>
<span id="cb29-120"><a href="#cb29-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-121"><a href="#cb29-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-122"><a href="#cb29-122" aria-hidden="true" tabindex="-1"></a><span class="fu">## Polynomial Regression and Parsimony</span></span>
<span id="cb29-123"><a href="#cb29-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-124"><a href="#cb29-124" aria-hidden="true" tabindex="-1"></a>When we fit a regression, we want to find a model that avoids under- and over-fitting the data. Further, we also want to consider the parsimony of our model (i.e., does it have to be as complex or could it be simpler?).</span>
<span id="cb29-125"><a href="#cb29-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-126"><a href="#cb29-126" aria-hidden="true" tabindex="-1"></a>Parsimony in the context of polynomial regression means considering models with fewer higher order terms both to avoid overfitting and having extra, potentially unnecessary, coefficients in our model.</span>
<span id="cb29-127"><a href="#cb29-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-128"><a href="#cb29-128" aria-hidden="true" tabindex="-1"></a>The evaluation of parsimony is often more subjective, but we can use quantitative approaches to determine how many polynomial terms are statistically justified as a starting place.</span>
<span id="cb29-129"><a href="#cb29-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-130"><a href="#cb29-130" aria-hidden="true" tabindex="-1"></a><span class="fu">### Partial F-test on Raw Polynomials</span></span>
<span id="cb29-131"><a href="#cb29-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-132"><a href="#cb29-132" aria-hidden="true" tabindex="-1"></a>If we fit models on our raw polynomials, we may have concerns about collinearity, which could make it challenging to identify the appropriate number of terms.</span>
<span id="cb29-133"><a href="#cb29-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-134"><a href="#cb29-134" aria-hidden="true" tabindex="-1"></a>Let's start by fitting a sequence of models and running partial F-tests:</span>
<span id="cb29-135"><a href="#cb29-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-138"><a href="#cb29-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-139"><a href="#cb29-139" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span>RIDAGEYR, <span class="at">data=</span>dat)</span>
<span id="cb29-140"><a href="#cb29-140" aria-hidden="true" tabindex="-1"></a>mod_poly2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">2</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-141"><a href="#cb29-141" aria-hidden="true" tabindex="-1"></a>mod_poly3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">3</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-142"><a href="#cb29-142" aria-hidden="true" tabindex="-1"></a>mod_poly4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">4</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-143"><a href="#cb29-143" aria-hidden="true" tabindex="-1"></a>mod_poly5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">5</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-144"><a href="#cb29-144" aria-hidden="true" tabindex="-1"></a>mod_poly6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">6</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-145"><a href="#cb29-145" aria-hidden="true" tabindex="-1"></a>mod_poly7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">7</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-146"><a href="#cb29-146" aria-hidden="true" tabindex="-1"></a>mod_poly8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">8</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-147"><a href="#cb29-147" aria-hidden="true" tabindex="-1"></a>mod_poly9 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">9</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-148"><a href="#cb29-148" aria-hidden="true" tabindex="-1"></a>mod_poly10 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">10</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-149"><a href="#cb29-149" aria-hidden="true" tabindex="-1"></a>mod_poly11 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">11</span>, <span class="at">raw=</span>T), <span class="at">data=</span>dat)</span>
<span id="cb29-150"><a href="#cb29-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-151"><a href="#cb29-151" aria-hidden="true" tabindex="-1"></a><span class="co"># partial F-tests (i.e., equivalent to observing coefficients and analyzing highest order t-statistic and p-value)</span></span>
<span id="cb29-152"><a href="#cb29-152" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_lm,mod_poly2,mod_poly3,mod_poly4,mod_poly5,mod_poly6,mod_poly7,mod_poly8,mod_poly9,mod_poly10,mod_poly11)</span>
<span id="cb29-153"><a href="#cb29-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-154"><a href="#cb29-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-155"><a href="#cb29-155" aria-hidden="true" tabindex="-1"></a>Based on these comparisons, it seems that a model with order 10 is considered the "best".</span>
<span id="cb29-156"><a href="#cb29-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-157"><a href="#cb29-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-158"><a href="#cb29-158" aria-hidden="true" tabindex="-1"></a><span class="fu">### Lack-of-Fit F-test</span></span>
<span id="cb29-159"><a href="#cb29-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-160"><a href="#cb29-160" aria-hidden="true" tabindex="-1"></a>When we have replicate observations at each level, we can also estimate the pure versus model error and use it to identify the number of polynomial terms. In the case of our NHANES data, age is only provided as a whole number and we could assume we have lots of categorical data:</span>
<span id="cb29-161"><a href="#cb29-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-164"><a href="#cb29-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-165"><a href="#cb29-165" aria-hidden="true" tabindex="-1"></a><span class="co"># fit saturated model</span></span>
<span id="cb29-166"><a href="#cb29-166" aria-hidden="true" tabindex="-1"></a>mod_pure <span class="ot">&lt;-</span> <span class="fu">lm</span>(SHBG <span class="sc">~</span> <span class="fu">as.factor</span>(RIDAGEYR), <span class="at">data=</span>dat)</span>
<span id="cb29-167"><a href="#cb29-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-168"><a href="#cb29-168" aria-hidden="true" tabindex="-1"></a><span class="co"># save p-values from partial F-tests</span></span>
<span id="cb29-169"><a href="#cb29-169" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_lm)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-170"><a href="#cb29-170" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly2)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-171"><a href="#cb29-171" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly3)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-172"><a href="#cb29-172" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly4)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-173"><a href="#cb29-173" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly5)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-174"><a href="#cb29-174" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly6)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-175"><a href="#cb29-175" aria-hidden="true" tabindex="-1"></a>p7 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly7)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-176"><a href="#cb29-176" aria-hidden="true" tabindex="-1"></a>p8 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly8)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-177"><a href="#cb29-177" aria-hidden="true" tabindex="-1"></a>p9 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly9)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-178"><a href="#cb29-178" aria-hidden="true" tabindex="-1"></a>p10 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly10)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-179"><a href="#cb29-179" aria-hidden="true" tabindex="-1"></a>p11 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_poly11)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-180"><a href="#cb29-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-181"><a href="#cb29-181" aria-hidden="true" tabindex="-1"></a><span class="co"># print p-values</span></span>
<span id="cb29-182"><a href="#cb29-182" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">'Order 1'</span><span class="ot">=</span>p1, <span class="st">'Order 2'</span><span class="ot">=</span>p2, <span class="st">'Order 3'</span><span class="ot">=</span>p3, <span class="st">'Order 4'</span><span class="ot">=</span>p4, <span class="st">'Order 5'</span><span class="ot">=</span>p5, <span class="st">'Order 6'</span><span class="ot">=</span>p6, <span class="st">'Order 7'</span><span class="ot">=</span>p7, <span class="st">'Order 8'</span><span class="ot">=</span>p8, <span class="st">'Order 9'</span><span class="ot">=</span>p9, <span class="st">'Order 10'</span><span class="ot">=</span>p10, <span class="st">'Order 11'</span><span class="ot">=</span>p11),<span class="dv">4</span>)</span>
<span id="cb29-183"><a href="#cb29-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-184"><a href="#cb29-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-185"><a href="#cb29-185" aria-hidden="true" tabindex="-1"></a>Our results indicate that an octic (order 8) polynomial regression is not significantly better than a septic (order 7) polynomial regression. However, the septic (order 7) is better than the sextic (order 6). </span>
<span id="cb29-186"><a href="#cb29-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-187"><a href="#cb29-187" aria-hidden="true" tabindex="-1"></a>This differs from our approach using just raw polynomials, where we chose a more complex order 10 model as "best".</span>
<span id="cb29-188"><a href="#cb29-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-189"><a href="#cb29-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-190"><a href="#cb29-190" aria-hidden="true" tabindex="-1"></a><span class="fu">### Orthogonal Polynomial Contrasts</span></span>
<span id="cb29-191"><a href="#cb29-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-192"><a href="#cb29-192" aria-hidden="true" tabindex="-1"></a>An approach we alluded to, but didn't delve into details, is the construction of orthogonal polynomial contrasts which remove the correlation between polynomial terms. While the math behind it is a bit lengthy, it is fairly easy to implement in <span class="in">`R`</span> by removing our <span class="in">`raw=T`</span> argument (or setting equal to the default <span class="in">`FALSE`</span>) from <span class="in">`poly()`</span>:</span>
<span id="cb29-193"><a href="#cb29-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-196"><a href="#cb29-196" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-197"><a href="#cb29-197" aria-hidden="true" tabindex="-1"></a>mod_orth1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">1</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-198"><a href="#cb29-198" aria-hidden="true" tabindex="-1"></a>mod_orth2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">2</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-199"><a href="#cb29-199" aria-hidden="true" tabindex="-1"></a>mod_orth3 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">3</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-200"><a href="#cb29-200" aria-hidden="true" tabindex="-1"></a>mod_orth4 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">4</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-201"><a href="#cb29-201" aria-hidden="true" tabindex="-1"></a>mod_orth5 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">5</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-202"><a href="#cb29-202" aria-hidden="true" tabindex="-1"></a>mod_orth6 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">6</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-203"><a href="#cb29-203" aria-hidden="true" tabindex="-1"></a>mod_orth7 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">7</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-204"><a href="#cb29-204" aria-hidden="true" tabindex="-1"></a>mod_orth8 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">8</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-205"><a href="#cb29-205" aria-hidden="true" tabindex="-1"></a>mod_orth9 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">9</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-206"><a href="#cb29-206" aria-hidden="true" tabindex="-1"></a>mod_orth10 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">10</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-207"><a href="#cb29-207" aria-hidden="true" tabindex="-1"></a>mod_orth11 <span class="ot">&lt;-</span> <span class="fu">lm</span>( SHBG<span class="sc">~</span><span class="fu">poly</span>(RIDAGEYR,<span class="dv">11</span>, <span class="at">raw=</span>F), <span class="at">data=</span>dat)</span>
<span id="cb29-208"><a href="#cb29-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-209"><a href="#cb29-209" aria-hidden="true" tabindex="-1"></a><span class="co"># print summary of Order 11 polynomial regression</span></span>
<span id="cb29-210"><a href="#cb29-210" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_orth11)</span>
<span id="cb29-211"><a href="#cb29-211" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-212"><a href="#cb29-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-213"><a href="#cb29-213" aria-hidden="true" tabindex="-1"></a>We see that the 11th order polynomial is the first to have a p-value &gt;0.05. This agrees with our raw polynomial calculation that Order 10 would be "best". </span>
<span id="cb29-214"><a href="#cb29-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-215"><a href="#cb29-215" aria-hidden="true" tabindex="-1"></a>With the correlation removed between our predictors, we can also see that a sequence of F-tests for adding each higher order term results in the same p-values:</span>
<span id="cb29-216"><a href="#cb29-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-219"><a href="#cb29-219" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-220"><a href="#cb29-220" aria-hidden="true" tabindex="-1"></a><span class="co"># print ANOVA comparisons adding 1 higher orthogonal term, notice p-values match those from the regression coefficient table for mod_orth11</span></span>
<span id="cb29-221"><a href="#cb29-221" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_orth1,mod_orth2,mod_orth3,mod_orth4,mod_orth5,mod_orth6,mod_orth7,mod_orth8,mod_orth9,mod_orth10,mod_orth11)</span>
<span id="cb29-222"><a href="#cb29-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-223"><a href="#cb29-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-224"><a href="#cb29-224" aria-hidden="true" tabindex="-1"></a>However, if we did a series of partial F-tests comparing to our saturated pure fit model (<span class="in">`mod_pure`</span>), we'd arrive at the same conclusion as the lack-of-fit $F$-test that a model with order 7 is "best":</span>
<span id="cb29-225"><a href="#cb29-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-228"><a href="#cb29-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-229"><a href="#cb29-229" aria-hidden="true" tabindex="-1"></a>o1 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth1)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-230"><a href="#cb29-230" aria-hidden="true" tabindex="-1"></a>o2 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth2)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-231"><a href="#cb29-231" aria-hidden="true" tabindex="-1"></a>o3 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth3)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-232"><a href="#cb29-232" aria-hidden="true" tabindex="-1"></a>o4 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth4)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-233"><a href="#cb29-233" aria-hidden="true" tabindex="-1"></a>o5 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth5)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-234"><a href="#cb29-234" aria-hidden="true" tabindex="-1"></a>o6 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth6)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-235"><a href="#cb29-235" aria-hidden="true" tabindex="-1"></a>o7 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth7)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-236"><a href="#cb29-236" aria-hidden="true" tabindex="-1"></a>o8 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth8)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-237"><a href="#cb29-237" aria-hidden="true" tabindex="-1"></a>o9 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth9)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-238"><a href="#cb29-238" aria-hidden="true" tabindex="-1"></a>o10 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth10)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-239"><a href="#cb29-239" aria-hidden="true" tabindex="-1"></a>o11 <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pure, mod_orth11)[<span class="st">"Pr(&gt;F)"</span>][<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb29-240"><a href="#cb29-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-241"><a href="#cb29-241" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">'Order 1'</span><span class="ot">=</span>o1, <span class="st">'Order 2'</span><span class="ot">=</span>o2, <span class="st">'Order 3'</span><span class="ot">=</span>o3, <span class="st">'Order 4'</span><span class="ot">=</span>o4, <span class="st">'Order 5'</span><span class="ot">=</span>o5, <span class="st">'Order 6'</span><span class="ot">=</span>o6, <span class="st">'Order 7'</span><span class="ot">=</span>o7, <span class="st">'Order 8'</span><span class="ot">=</span>o8, <span class="st">'Order 9'</span><span class="ot">=</span>o9, <span class="st">'Order 10'</span><span class="ot">=</span>o10, <span class="st">'Order 11'</span><span class="ot">=</span>o11),<span class="dv">4</span>)</span>
<span id="cb29-242"><a href="#cb29-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-243"><a href="#cb29-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-244"><a href="#cb29-244" aria-hidden="true" tabindex="-1"></a>Here, since we are comparing to the saturated model, we can be fairly confident that order 7 may be best. If we did not have a saturated model (e.g., no replicates), we may have chosen the order 10 as optimal based on the orthogonal polynomials (and potentially decided a lower order based on parsimony).</span>
<span id="cb29-245"><a href="#cb29-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-246"><a href="#cb29-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-247"><a href="#cb29-247" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which Model to Use?</span></span>
<span id="cb29-248"><a href="#cb29-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-249"><a href="#cb29-249" aria-hidden="true" tabindex="-1"></a>We saw that the raw polynomial approach suggested a model with Order 10, and that both saturated or orthogonal polynomial approaches identified a model with Order 7. Both of these are quite high orders. We may also wish to evaluate other summaries, like the adjusted $R^2$ value:</span>
<span id="cb29-250"><a href="#cb29-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-251"><a href="#cb29-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-hide'}</span></span>
<span id="cb29-252"><a href="#cb29-252" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb29-253"><a href="#cb29-253" aria-hidden="true" tabindex="-1"></a>rawr2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Order 1'</span><span class="ot">=</span><span class="fu">summary</span>(mod_lm)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 2'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly2)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 3'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly3)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 4'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly4)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 5'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly5)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 6'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly6)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 7'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly7)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 8'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly8)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 9'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly9)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 10'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly10)<span class="sc">$</span>adj.r.squared, <span class="st">'Order 11'</span><span class="ot">=</span><span class="fu">summary</span>(mod_poly11)<span class="sc">$</span>adj.r.squared)</span>
<span id="cb29-254"><a href="#cb29-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-255"><a href="#cb29-255" aria-hidden="true" tabindex="-1"></a>ortr2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Orth Order 1'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth1)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 2'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth2)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 3'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth3)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 4'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth4)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 5'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth5)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 6'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth6)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 7'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth7)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 8'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth8)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 9'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth9)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 10'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth10)<span class="sc">$</span>adj.r.squared, <span class="st">'Orth Order 11'</span><span class="ot">=</span><span class="fu">summary</span>(mod_orth11)<span class="sc">$</span>adj.r.squared)</span>
<span id="cb29-256"><a href="#cb29-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-257"><a href="#cb29-257" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="st">'Raw'</span> <span class="ot">=</span> rawr2, <span class="st">'Orthogonal'</span> <span class="ot">=</span> ortr2)</span>
<span id="cb29-258"><a href="#cb29-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-259"><a href="#cb29-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-260"><a href="#cb29-260" aria-hidden="true" tabindex="-1"></a>We can note 2 things from these $R^2_{adj}$ results:</span>
<span id="cb29-261"><a href="#cb29-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-262"><a href="#cb29-262" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>The estimated percent of variability explained by each raw and orthogonal polynomial model of the same order *are identical*! This is because while the orthogonal polynomials transform our predictors to remove collinearity, the same data/information is included in the model.</span>
<span id="cb29-263"><a href="#cb29-263" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>It appears that after Order 4, the jumps in $R^2_{adj}$ get smaller and smaller. This may suggest a model with Order 4 may be sufficient.</span>
<span id="cb29-264"><a href="#cb29-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-265"><a href="#cb29-265" aria-hidden="true" tabindex="-1"></a>To evaluate, let's compare the some models while also illustrating the dangers of extrapolation:</span>
<span id="cb29-266"><a href="#cb29-266" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb29-267"><a href="#cb29-267" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-hide'}</span></span>
<span id="cb29-268"><a href="#cb29-268" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb29-269"><a href="#cb29-269" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>dat<span class="sc">$</span>RIDAGEYR, <span class="at">y=</span>dat<span class="sc">$</span>SHBG, <span class="at">xlab=</span><span class="st">'Age (Years)'</span>, <span class="at">ylab=</span><span class="st">'SHBG (nmol/L)'</span>, <span class="at">col=</span><span class="st">'gray85'</span>, <span class="at">cex.lab=</span><span class="fl">0.8</span>, <span class="at">cex.axis=</span><span class="fl">0.8</span>, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">100</span>))</span>
<span id="cb29-270"><a href="#cb29-270" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10</span><span class="sc">:</span><span class="dv">100</span></span>
<span id="cb29-271"><a href="#cb29-271" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly4, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'black'</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb29-272"><a href="#cb29-272" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly7, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'orangered2'</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb29-273"><a href="#cb29-273" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly10, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb29-274"><a href="#cb29-274" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>age, <span class="at">y=</span><span class="fu">predict</span>(mod_poly11, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">RIDAGEYR=</span>age)), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'purple'</span>, <span class="at">lty=</span><span class="dv">5</span>)</span>
<span id="cb29-275"><a href="#cb29-275" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'top'</span>, <span class="at">horiz=</span>T, <span class="at">bty=</span><span class="st">'n'</span>, <span class="at">xpd=</span>T, <span class="at">inset=</span><span class="sc">-</span><span class="fl">0.15</span>, <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="at">lwd=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">legend=</span><span class="fu">c</span>(<span class="st">'Order 4'</span>,<span class="st">'Order 7'</span>,<span class="st">'Order 10'</span>,<span class="st">'Order 11'</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">'black'</span>,<span class="st">'orangered2'</span>,<span class="st">'blue'</span>,<span class="st">'purple'</span>))</span>
<span id="cb29-276"><a href="#cb29-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-277"><a href="#cb29-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-278"><a href="#cb29-278" aria-hidden="true" tabindex="-1"></a>First, note extrapolation beyond our observed data quickly gets crazy and shouldn't be done for our polynomial models.</span>
<span id="cb29-279"><a href="#cb29-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-280"><a href="#cb29-280" aria-hidden="true" tabindex="-1"></a>Second, I think the choice of "best" Order 4 or Order 7 depends on our own belief of how well it fits the data without being potentially overfit. Further, Orders 10 and 11 are quite similar to Order 7, so even if we had used a method and chosen Order 10, it wouldn't be wrong (just overly complex).</span>
<span id="cb29-281"><a href="#cb29-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-282"><a href="#cb29-282" aria-hidden="true" tabindex="-1"></a><span class="fu">## Other Modeling Approaches</span></span>
<span id="cb29-283"><a href="#cb29-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-284"><a href="#cb29-284" aria-hidden="true" tabindex="-1"></a>There are also other modeling strategies that may be helpful beyond polynomial regression and are covered in some other lectures:</span>
<span id="cb29-285"><a href="#cb29-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-286"><a href="#cb29-286" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Spline modeling provides more flexibility for the trends (but is still hard to interpret)</span>
<span id="cb29-287"><a href="#cb29-287" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Piecewise regression models are more interpretable and identify break/changepoints where the trend changes/shifts</span>
<span id="cb29-288"><a href="#cb29-288" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>