<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Kaizer">

<title>Alex Kaizer - Categorical Predictors in Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/size.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/academicons-1.9.1/css/academicons.css" rel="stylesheet">

<link rel="icon" type="image/png" href="./files/favicon.ico">

<script type="text/javascript">
function setBrand() {
document.getElementsByClassName("navbar-brand")[0].href="https://www.alexkaizer.com";
}
window.onload = setBrand;
</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5PBG7BL207"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5PBG7BL207');
</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Alex Kaizer</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/research" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/publications" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/teaching" rel="" target="">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6618" rel="" target="">
 <span class="dropdown-text">BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6611" rel="" target="">
 <span class="dropdown-text">BIOS 6611</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/study_design_berd" rel="" target="">
 <span class="dropdown-text">BERD Study Design Short Course</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/adaptivetrials_sc" rel="" target="">
 <span class="dropdown-text">WNAR Adaptive and Bayesian Clinical Trial Design Short Course</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bios-6618" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">BIOS 6618</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bios-6618">    
        <li>
    <a class="dropdown-item" href="../../index.html" rel="" target="">
 <span class="dropdown-text">Home</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../bios_6618_materials" rel="" target="">
 <span class="dropdown-text">Materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../journal_of_bios_6618" rel="" target="">
 <span class="dropdown-text">Journal of BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../recitation" rel="" target="">
 <span class="dropdown-text">Recitation Questions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs" rel="" target="">
 <span class="dropdown-text">Labs and Practice Problems</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:alex.kaizer@cuanschutz.edu" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=ICpH74EAAAAJ&amp;hl=en" rel="" target="">
 <span class="menu-text"><i class="ai  ai-google-scholar ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="http://github.com/alexbiostats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/files/Alex_CV.pdf" rel="" target="">
 <span class="menu-text"><i class="ai  ai-cv ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/alex-kaizer/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#considerations-with-categorical-predictors" id="toc-considerations-with-categorical-predictors" class="nav-link active" data-scroll-target="#considerations-with-categorical-predictors">Considerations with Categorical Predictors</a>
  <ul class="collapse">
  <li><a href="#how-is-the-reference-group-accounted-for" id="toc-how-is-the-reference-group-accounted-for" class="nav-link" data-scroll-target="#how-is-the-reference-group-accounted-for">How is the reference group accounted for?</a></li>
  <li><a href="#what-category-should-be-my-reference" id="toc-what-category-should-be-my-reference" class="nav-link" data-scroll-target="#what-category-should-be-my-reference">What category should be my reference?</a></li>
  <li><a href="#can-i-reduce-the-number-of-groups" id="toc-can-i-reduce-the-number-of-groups" class="nav-link" data-scroll-target="#can-i-reduce-the-number-of-groups">Can I reduce the number of groups?</a></li>
  <li><a href="#cells-means-model-formulation-interpretation-and-use" id="toc-cells-means-model-formulation-interpretation-and-use" class="nav-link" data-scroll-target="#cells-means-model-formulation-interpretation-and-use">Cells means model formulation, interpretation, and use</a>
  <ul class="collapse">
  <li><a href="#an-example-of-using-cell-means" id="toc-an-example-of-using-cell-means" class="nav-link" data-scroll-target="#an-example-of-using-cell-means">An Example of Using Cell Means</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Categorical Predictors in Linear Regression</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Alex Kaizer </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Colorado-Anschutz Medical Campus
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<p>This page is part of the University of Colorado-Anschutz Medical Campus’ <a href="../../recitation/index.html">BIOS 6618 Recitation</a> collection. To view other questions, you can view the <a href="../../recitation/index.html">BIOS 6618 Recitation</a> collection page or use the search bar to look for keywords.</p>
<section id="considerations-with-categorical-predictors" class="level1">
<h1>Considerations with Categorical Predictors</h1>
<p>When working with categorical variables, we have a host of options for how to incorporate them into a statistical model (i.e., how to code them up for their prime time debut in the model):</p>
<ul>
<li>Indicator variables (also known as dummy coding): levels of 0 or 1 for each variable (reference group is generally all 0’s) <em>[What I generally use in practice]</em></li>
<li>Effect coding: levels of -1, 0, or 1 for each variable (reference group is represented by all -1’s) <em>[I have never used this myself in practice]</em></li>
<li>Continuous modeling: treating the “categories” as a continuous predictor (no reference group) <em>[This makes a strong assumption that the difference between levels are “equal”, but sometimes it can be useful for Likert-type variables]</em></li>
</ul>
<p>Indicator variables then have a few formulations, two of the more common ones are:</p>
<ul>
<li>Reference Cell Models</li>
<li>Cell Means Models</li>
</ul>
<p>We’ll walk through a few questions and considerations for each of these.</p>
<section id="how-is-the-reference-group-accounted-for" class="level2">
<h2 class="anchored" data-anchor-id="how-is-the-reference-group-accounted-for">How is the reference group accounted for?</h2>
<p>For this question we will assume we are working with the <em>reference cell model</em> formulation. Let’s use our carotenoids example from HW9 to illustrate how this works for the model with only smoking status.</p>
<p>First, let’s remind ourselves of the mean plasma beta-carotene levels:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doBy)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>carotenoids <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">'../../.data/carotenoids.dat'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(carotenoids) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'age'</span>,<span class="st">'sex'</span>,<span class="st">'smoke'</span>,<span class="st">'bmi'</span>,<span class="st">'vitamins'</span>,<span class="st">'calories'</span>,<span class="st">'fat'</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'fiber'</span>,<span class="st">'alcohol'</span>,<span class="st">'chol'</span>,<span class="st">'betadiet'</span>,<span class="st">'retdiet'</span>,<span class="st">'betaplas'</span>,<span class="st">'retplas'</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>smoke_factor <span class="ot">&lt;-</span> <span class="fu">factor</span>(carotenoids<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Never'</span>,<span class="st">'Former'</span>,<span class="st">'Current'</span>))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryBy</span>( betaplas <span class="sc">~</span> smoke_factor, <span class="at">data=</span>carotenoids )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  smoke_factor betaplas.mean
1        Never      206.0510
2       Former      193.4696
3      Current      121.3256</code></pre>
</div>
</div>
<p>For the reference cell model, we select one of our smoking groups to be the reference, which all other groups are compared to. Let’s use never smokers, like before, as our reference group. The indicator variables in this case would be</p>
<table class="table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: center;"><span class="math inline">\(I_N\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I_F\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I_C\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Never</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td>Former</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td>Current</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<p>The <em>expected</em> regression model is then</p>
<p><span class="math display">\[ E[Y] = \beta_0 + \beta_1 I_{F} + \beta_{2} I_{C} \]</span></p>
<p>where <span class="math inline">\(I_F\)</span> and <span class="math inline">\(I_C\)</span> are indicator variables for being a former smoker or current smoker, respectively. If <span class="math inline">\(I_F = I_C = 0\)</span>, then someone must be in the reference group and is a never smoker.</p>
<p>If we fit the model and look at the coefficients we can make a direct connection to our mean levels within each group:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept)         206.05096   14.48037 14.2296790 9.311836e-36
smoke_factorFormer  -12.58139   22.26974 -0.5649546 5.725106e-01
smoke_factorCurrent -84.72537   31.22916 -2.7130212 7.037481e-03</code></pre>
</div>
</div>
<ol type="1">
<li>We see that <span class="math inline">\(\hat{\beta}_0=206.05096\)</span> is our group mean! This makes sense given our interpretation of the intercept as the expected mean outcome when all predictors are equal to 0.</li>
<li>Our estimated slope coefficients, <span class="math inline">\(\hat{\beta}_{1}\)</span> and <span class="math inline">\(\hat{\beta}_{2}\)</span>, then represent the <em>difference</em> in the mean plasma beta-carotene from the reference category. For example, <span class="math inline">\(\hat{\beta}_0 + \hat{\beta}_1 = 206.05096 + (-12.58139) = 193.4696\)</span>, our estimated mean plasma beta-carotene levels for former smokers! Likewise, <span class="math inline">\(\hat{\beta}_0 + \hat{\beta}_2 = 206.05096 + (-84.72537) = 121.3256\)</span>, the estimated mean for current smokers.</li>
</ol>
</section>
<section id="what-category-should-be-my-reference" class="level2">
<h2 class="anchored" data-anchor-id="what-category-should-be-my-reference">What category should be my reference?</h2>
<p>This question comes up often when working with collaborators, and we may ourselves wonder what makes the most sense. The good news, mathematically we have the same information included regardless of the choice of reference category! Essentially, the <em>perspective</em> of our results is what changes (i.e., beta coefficients, p-values, etc. will change to reflect whatever the reference category is), but changing a reference category won’t affect the actual significance (e.g., if never versus former smokers was not significant in the original model, it won’t be in a subsequent model either).</p>
<p>Let’s fit all the possible combinations, and see the equivalence firsthand:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>smoke_factor2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(carotenoids<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">1</span>),</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Former'</span>,<span class="st">'Current'</span>,<span class="st">'Never'</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>smoke_factor3 <span class="ot">&lt;-</span> <span class="fu">factor</span>(carotenoids<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">1</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Current'</span>,<span class="st">'Former'</span>,<span class="st">'Never'</span>))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>c1 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients,<span class="dv">4</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor2, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients,<span class="dv">4</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>c3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor3, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients,<span class="dv">4</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>c_tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">''</span>,c1, <span class="st">''</span>, c2, <span class="st">''</span>, c3)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(c_tab) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Reference Group: Never'</span>, <span class="fu">rownames</span>(c1), <span class="st">'Reference Group: Former'</span>, <span class="fu">rownames</span>(c2), <span class="st">'Reference Group: Current'</span>, <span class="fu">rownames</span>(c3))</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(c_tab, <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">'Estimate'</span>,<span class="st">'SE'</span>,<span class="st">'t'</span>,<span class="st">'p-value'</span>), <span class="at">align=</span><span class="st">'cccc'</span>, <span class="at">escape=</span>F) <span class="sc">%&gt;%</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">"left"</span>)<span class="co"># print a formatted table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Reference Group: Never</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">206.051</td>
<td style="text-align: center;">14.4804</td>
<td style="text-align: center;">14.2297</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">smoke_factorFormer</td>
<td style="text-align: center;">-12.5814</td>
<td style="text-align: center;">22.2697</td>
<td style="text-align: center;">-0.565</td>
<td style="text-align: center;">0.5725</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke_factorCurrent</td>
<td style="text-align: center;">-84.7254</td>
<td style="text-align: center;">31.2292</td>
<td style="text-align: center;">-2.713</td>
<td style="text-align: center;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reference Group: Former</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">193.4696</td>
<td style="text-align: center;">16.9192</td>
<td style="text-align: center;">11.4349</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">smoke_factor2Current</td>
<td style="text-align: center;">-72.144</td>
<td style="text-align: center;">32.4321</td>
<td style="text-align: center;">-2.2245</td>
<td style="text-align: center;">0.0268</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke_factor2Never</td>
<td style="text-align: center;">12.5814</td>
<td style="text-align: center;">22.2697</td>
<td style="text-align: center;">0.565</td>
<td style="text-align: center;">0.5725</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reference Group: Current</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">121.3256</td>
<td style="text-align: center;">27.6691</td>
<td style="text-align: center;">4.3849</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">smoke_factor3Former</td>
<td style="text-align: center;">72.144</td>
<td style="text-align: center;">32.4321</td>
<td style="text-align: center;">2.2245</td>
<td style="text-align: center;">0.0268</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke_factor3Never</td>
<td style="text-align: center;">84.7254</td>
<td style="text-align: center;">31.2292</td>
<td style="text-align: center;">2.713</td>
<td style="text-align: center;">0.007</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Notice how the point estimates are the the same number (but differ by + or -) across models depending on the reference category. Similarly, the p-values are the same as well for any similar pairwise comparison.</p>
<p>For <em>nominal</em> variables (i.e., categorical with no ordering) and <em>ordinal</em> variables (i.e., categorical with an ordering), your choice of reference will be driven by the question at hand. For ordinal variables, it can be helpful to choose the lowest or highest category since there is (hopefully) a linear trend across categories that will be evident from the regression results.</p>
<p>In future weeks we will also discuss <strong>contrasts</strong> as a method we can use to calculate different summaries, but one nice workaround can be to refit the model with different reference categories to better align with the perspective expected or desired.</p>
</section>
<section id="can-i-reduce-the-number-of-groups" class="level2">
<h2 class="anchored" data-anchor-id="can-i-reduce-the-number-of-groups">Can I reduce the number of groups?</h2>
<p>When we start with a data analysis, we might initially have <span class="math inline">\(G\)</span> groups. With our reference cell model, assuming we include all the initial groups, we would have a regression model including only the group variable with <span class="math inline">\(G-1\)</span> predictors: <span class="math inline">\(\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 I_{g=1} + \hat{\beta}_2 I_{g=2} + ... + \hat{\beta}_{G-1} I_{g=G-1}\)</span>.</p>
<p>But the question remains, do I <em>need</em> all these groups? Here are a few things to consider:</p>
<ol type="1">
<li>First, is it reasonable clinically/biologically/contextually to collapse <em>any</em> of the groups together? For example, with smoking it might sense to collapse “Former” smokers with either group depending on if we are interested in (1) history of any smoking (Never vs.&nbsp;Former/Current) or (2) current behavior (Never/Former vs.&nbsp;Current). If we think the history of smoking, even without being a current smoker, is important we <strong>should not</strong> combine those groups unless there is a very compelling reason.</li>
<li>Do we have “enough” data to use for inference? If a group has a very small sample size, we might need to combine it with a different group to successfully fit certain models or have confidence in our inference. If we keep the small group size and the model, one of the biggest impacts will be a less precise standard error estimate (and therefore a smaller test statistic and p-value since the CLT directly connects the sample size with <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>).</li>
<li>Is there concerns about reducing the degrees of freedom we are “spending” on all our predictors? For example, we know that our <span class="math inline">\(t\)</span>-tests in our regression model for the coefficient table rely on a <span class="math inline">\(t_{n-p-1}\)</span> distribution. Obviously, we cannot have more predictors than <span class="math inline">\(n-1\)</span> since we’d have 0 degrees of freedom, but even if we leave a few degrees of freedom behind, it can still impact our power to detect the results (i.e., <span class="math inline">\(t\)</span>-distributions with fewer degrees of freedom have fatter tails). If we can reduce the number of categories, we have more degrees of freedom to use for either other predictors or to have a more normal-like distribution for reference.</li>
</ol>
<p>Again, one of the most sensible ways to combine groups is to use the scientific/contextual motivation. We can also consider combining groups that we identify as not being significantly different from one another when making a pairwise comparison. HOWEVER:</p>
<ul>
<li>By combining groups it will alter the estimates and comparisons with the other (remaining) groups that are affected by sample size. For example, <span class="math inline">\(n=3\)</span> won’t really impact the mean estimate for a group with <span class="math inline">\(n=1000\)</span>.</li>
<li>If we have small sample sizes, we may be underpowered to detect a group difference and would combine groups just because “<span class="math inline">\(p&gt;0.05\)</span>”.</li>
</ul>
</section>
<section id="cells-means-model-formulation-interpretation-and-use" class="level2">
<h2 class="anchored" data-anchor-id="cells-means-model-formulation-interpretation-and-use">Cells means model formulation, interpretation, and use</h2>
<p>The cell means model makes the connection between the mean levels within a group more explicit. In this approach we would exclude the intercept and include an indicator variable for each group:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cell_means <span class="ot">&lt;-</span> <span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data=</span>carotenoids)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cell_means)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate Std. Error   t value     Pr(&gt;|t|)
smoke_factorNever   206.0510   14.48037 14.229679 9.311836e-36
smoke_factorFormer  193.4696   16.91922 11.434896 1.593885e-25
smoke_factorCurrent 121.3256   27.66911  4.384875 1.588507e-05</code></pre>
</div>
</div>
<p>In the model above, we see that the “reference” category from our reference cell model is now included as one of the predictors. We can also note that all the estimated coefficients represent the means for each smoking group!</p>
<p>The <em>fitted</em> regression model would be <span class="math display">\[ \hat{Y} = 206.0510 I_N + 193.4696 I_F + 121.3256 I_C  \]</span></p>
<p>The cell means model makes a more direct connection to the one-way ANOVA we’ve also seen (since we’re only considering categorical variables here). However, we can also get the same estimates, as we saw before, with a reference cell model by combining our different estimated <span class="math inline">\(\hat{\beta}\)</span>’s.</p>
<section id="an-example-of-using-cell-means" class="level3">
<h3 class="anchored" data-anchor-id="an-example-of-using-cell-means">An Example of Using Cell Means</h3>
<p>In practice, I’ve only recommend a cell means model one time. The investigator wanted to summarize the mean level of response to a hearing test across a combination of gerbil age (young vs.&nbsp;old) and sound setting (three levels) and compare if each response was equal to 0, where in this case the response of 0 indicated a null effect of the combination. The cell means model made this extremely intuitive since it combined the two factors and provided that exact hypothesis test from the <span class="math inline">\(t\)</span>-test.</p>
<p>For example, if we look at our plasma concentration for those under 50 years old vs.&nbsp;over 50 years old with smoking status, we would have:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>AK_age_gte50 <span class="ot">&lt;-</span> carotenoids<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">50</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate means by groups</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryBy</span>( betaplas <span class="sc">~</span> AK_age_gte50<span class="sc">*</span>smoke_factor, <span class="at">data=</span>carotenoids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  AK_age_gte50 smoke_factor betaplas.mean
1        FALSE        Never      194.7229
2        FALSE       Former      209.6349
3        FALSE      Current      123.8387
4         TRUE        Never      218.7568
5         TRUE       Former      173.8846
6         TRUE      Current      114.8333</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit cell means model with all groups</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>( betaplas <span class="sc">~</span> AK_age_gte50<span class="sc">:</span>smoke_factor <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data=</span>carotenoids))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  AK_age_gte50FALSE:smoke_factorNever    AK_age_gte50TRUE:smoke_factorNever 
                             194.7229                              218.7568 
 AK_age_gte50FALSE:smoke_factorFormer   AK_age_gte50TRUE:smoke_factorFormer 
                             209.6349                              173.8846 
AK_age_gte50FALSE:smoke_factorCurrent  AK_age_gte50TRUE:smoke_factorCurrent 
                             123.8387                              114.8333 </code></pre>
</div>
</div>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb12" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Categorical Predictors in Linear Regression"</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Alex Kaizer</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">  roles: "Instructor"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co">  affiliation: University of Colorado-Anschutz Medical Campus</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc_float:</span><span class="co"> true</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> left</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap </span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=F, message=F, warning=F}</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>This page is part of the University of Colorado-Anschutz Medical Campus' <span class="co">[</span><span class="ot">BIOS 6618 Recitation</span><span class="co">](/recitation/index.qmd)</span> collection. To view other questions, you can view the <span class="co">[</span><span class="ot">BIOS 6618 Recitation</span><span class="co">](/recitation/index.qmd)</span> collection page or use the search bar to look for keywords.</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="fu"># Considerations with Categorical Predictors</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>When working with categorical variables, we have a host of options for how to incorporate them into a statistical model (i.e., how to code them up for their prime time debut in the model):</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Indicator variables (also known as dummy coding): levels of 0 or 1 for each variable (reference group is generally all 0's) *[What I generally use in practice]*</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Effect coding: levels of -1, 0, or 1 for each variable (reference group is represented by all -1's) *[I have never used this myself in practice]*</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Continuous modeling: treating the "categories" as a continuous predictor (no reference group) *[This makes a strong assumption that the difference between levels are "equal", but sometimes it can be useful for Likert-type variables]*</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>Indicator variables then have a few formulations, two of the more common ones are:</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Reference Cell Models</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Cell Means Models</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>We'll walk through a few questions and considerations for each of these.</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## How is the reference group accounted for?</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>For this question we will assume we are working with the *reference cell model* formulation. Let's use our carotenoids example from HW9 to illustrate how this works for the model with only smoking status.</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>First, let's remind ourselves of the mean plasma beta-carotene levels:</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, message=F}</span></span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doBy)</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>carotenoids <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">'../../.data/carotenoids.dat'</span>)</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(carotenoids) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'age'</span>,<span class="st">'sex'</span>,<span class="st">'smoke'</span>,<span class="st">'bmi'</span>,<span class="st">'vitamins'</span>,<span class="st">'calories'</span>,<span class="st">'fat'</span>,</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'fiber'</span>,<span class="st">'alcohol'</span>,<span class="st">'chol'</span>,<span class="st">'betadiet'</span>,<span class="st">'retdiet'</span>,<span class="st">'betaplas'</span>,<span class="st">'retplas'</span>)</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>smoke_factor <span class="ot">&lt;-</span> <span class="fu">factor</span>(carotenoids<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Never'</span>,<span class="st">'Former'</span>,<span class="st">'Current'</span>))</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryBy</span>( betaplas <span class="sc">~</span> smoke_factor, <span class="at">data=</span>carotenoids )</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>For the reference cell model, we select one of our smoking groups to be the reference, which all other groups are compared to. Let's use never smokers, like before, as our reference group. The indicator variables in this case would be</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>| Group   | $I_N$ | $I_F$ | $I_C$ |</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>|---------|:--:|:--:|:--:|</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>| Never   |  1 |  0 |  0 |</span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>| Former  |  0 |  1 |  0 |</span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>| Current |  0 |  0 |  1 |</span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>The *expected* regression model is then</span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>$$ E<span class="co">[</span><span class="ot">Y</span><span class="co">]</span> = \beta_0 + \beta_1 I_{F} + \beta_{2} I_{C} $$</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a>where $I_F$ and $I_C$ are indicator variables for being a former smoker or current smoker, respectively. If $I_F = I_C = 0$, then someone must be in the reference group and is a never smoker.</span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a>If we fit the model and look at the coefficients we can make a direct connection to our mean levels within each group:</span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-76"><a href="#cb12-76" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb12-77"><a href="#cb12-77" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients</span>
<span id="cb12-78"><a href="#cb12-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-79"><a href="#cb12-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-80"><a href="#cb12-80" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>We see that $\hat{\beta}_0=206.05096$ is our group mean! This makes sense given our interpretation of the intercept as the expected mean outcome when all predictors are equal to 0.</span>
<span id="cb12-81"><a href="#cb12-81" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Our estimated slope coefficients, $\hat{\beta}_{1}$ and $\hat{\beta}_{2}$, then represent the *difference* in the mean plasma beta-carotene from the reference category. For example, $\hat{\beta}_0 + \hat{\beta}_1 = 206.05096 + (-12.58139) = 193.4696$, our estimated mean plasma beta-carotene levels for former smokers! Likewise, $\hat{\beta}_0 + \hat{\beta}_2 = 206.05096 + (-84.72537) = 121.3256$, the estimated mean for current smokers.</span>
<span id="cb12-82"><a href="#cb12-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-83"><a href="#cb12-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-84"><a href="#cb12-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## What category should be my reference?</span></span>
<span id="cb12-85"><a href="#cb12-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-86"><a href="#cb12-86" aria-hidden="true" tabindex="-1"></a>This question comes up often when working with collaborators, and we may ourselves wonder what makes the most sense. The good news, mathematically we have the same information included regardless of the choice of reference category! Essentially, the *perspective* of our results is what changes (i.e., beta coefficients, p-values, etc. will change to reflect whatever the reference category is), but changing a reference category won't affect the actual significance (e.g., if never versus former smokers was not significant in the original model, it won't be in a subsequent model either).</span>
<span id="cb12-87"><a href="#cb12-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-88"><a href="#cb12-88" aria-hidden="true" tabindex="-1"></a>Let's fit all the possible combinations, and see the equivalence firsthand:</span>
<span id="cb12-89"><a href="#cb12-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-92"><a href="#cb12-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb12-93"><a href="#cb12-93" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>smoke_factor2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(carotenoids<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">1</span>),</span>
<span id="cb12-94"><a href="#cb12-94" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Former'</span>,<span class="st">'Current'</span>,<span class="st">'Never'</span>))</span>
<span id="cb12-95"><a href="#cb12-95" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>smoke_factor3 <span class="ot">&lt;-</span> <span class="fu">factor</span>(carotenoids<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">1</span>),</span>
<span id="cb12-96"><a href="#cb12-96" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels=</span><span class="fu">c</span>(<span class="st">'Current'</span>,<span class="st">'Former'</span>,<span class="st">'Never'</span>))</span>
<span id="cb12-97"><a href="#cb12-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-98"><a href="#cb12-98" aria-hidden="true" tabindex="-1"></a>c1 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients,<span class="dv">4</span>)</span>
<span id="cb12-99"><a href="#cb12-99" aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor2, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients,<span class="dv">4</span>)</span>
<span id="cb12-100"><a href="#cb12-100" aria-hidden="true" tabindex="-1"></a>c3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor3, <span class="at">data=</span>carotenoids))<span class="sc">$</span>coefficients,<span class="dv">4</span>)</span>
<span id="cb12-101"><a href="#cb12-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-102"><a href="#cb12-102" aria-hidden="true" tabindex="-1"></a>c_tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">''</span>,c1, <span class="st">''</span>, c2, <span class="st">''</span>, c3)</span>
<span id="cb12-103"><a href="#cb12-103" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(c_tab) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Reference Group: Never'</span>, <span class="fu">rownames</span>(c1), <span class="st">'Reference Group: Former'</span>, <span class="fu">rownames</span>(c2), <span class="st">'Reference Group: Current'</span>, <span class="fu">rownames</span>(c3))</span>
<span id="cb12-104"><a href="#cb12-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-105"><a href="#cb12-105" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb12-106"><a href="#cb12-106" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(c_tab, <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">'Estimate'</span>,<span class="st">'SE'</span>,<span class="st">'t'</span>,<span class="st">'p-value'</span>), <span class="at">align=</span><span class="st">'cccc'</span>, <span class="at">escape=</span>F) <span class="sc">%&gt;%</span></span>
<span id="cb12-107"><a href="#cb12-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">"left"</span>)<span class="co"># print a formatted table</span></span>
<span id="cb12-108"><a href="#cb12-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-109"><a href="#cb12-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-110"><a href="#cb12-110" aria-hidden="true" tabindex="-1"></a>Notice how the point estimates are the the same number (but differ by + or -) across models depending on the reference category. Similarly, the p-values are the same as well for any similar pairwise comparison.</span>
<span id="cb12-111"><a href="#cb12-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-112"><a href="#cb12-112" aria-hidden="true" tabindex="-1"></a>For *nominal* variables (i.e., categorical with no ordering) and *ordinal* variables (i.e., categorical with an ordering), your choice of reference will be driven by the question at hand. For ordinal variables, it can be helpful to choose the lowest or highest category since there is (hopefully) a linear trend across categories that will be evident from the regression results.</span>
<span id="cb12-113"><a href="#cb12-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-114"><a href="#cb12-114" aria-hidden="true" tabindex="-1"></a>In future weeks we will also discuss **contrasts** as a method we can use to calculate different summaries, but one nice workaround can be to refit the model with different reference categories to better align with the perspective expected or desired.</span>
<span id="cb12-115"><a href="#cb12-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-116"><a href="#cb12-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-117"><a href="#cb12-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## Can I reduce the number of groups?</span></span>
<span id="cb12-118"><a href="#cb12-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-119"><a href="#cb12-119" aria-hidden="true" tabindex="-1"></a>When we start with a data analysis, we might initially have $G$ groups. With our reference cell model, assuming we include all the initial groups, we would have a regression model including only the group variable with $G-1$ predictors: $\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 I_{g=1} + \hat{\beta}_2 I_{g=2} + ... + \hat{\beta}_{G-1} I_{g=G-1}$. </span>
<span id="cb12-120"><a href="#cb12-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-121"><a href="#cb12-121" aria-hidden="true" tabindex="-1"></a>But the question remains, do I *need* all these groups? Here are a few things to consider:</span>
<span id="cb12-122"><a href="#cb12-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-123"><a href="#cb12-123" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>First, is it reasonable clinically/biologically/contextually to collapse *any* of the groups together? For example, with smoking it might sense to collapse "Former" smokers with either group depending on if we are interested in (1) history of any smoking (Never vs. Former/Current) or (2) current behavior (Never/Former vs. Current). If we think the history of smoking, even without being a current smoker, is important we **should not** combine those groups unless there is a very compelling reason.</span>
<span id="cb12-124"><a href="#cb12-124" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Do we have "enough" data to use for inference? If a group has a very small sample size, we might need to combine it with a different group to successfully fit certain models or have confidence in our inference. If we keep the small group size and the model, one of the biggest impacts will be a less precise standard error estimate (and therefore a smaller test statistic and p-value since the CLT directly connects the sample size with $\frac{\sigma}{\sqrt{n}}$).</span>
<span id="cb12-125"><a href="#cb12-125" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Is there concerns about reducing the degrees of freedom we are "spending" on all our predictors? For example, we know that our $t$-tests in our regression model for the coefficient table rely on a $t_{n-p-1}$ distribution. Obviously, we cannot have more predictors than $n-1$ since we'd have 0 degrees of freedom, but even if we leave a few degrees of freedom behind, it can still impact our power to detect the results (i.e., $t$-distributions with fewer degrees of freedom have fatter tails). If we can reduce the number of categories, we have more degrees of freedom to use for either other predictors or to have a more normal-like distribution for reference.</span>
<span id="cb12-126"><a href="#cb12-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-127"><a href="#cb12-127" aria-hidden="true" tabindex="-1"></a>Again, one of the most sensible ways to combine groups is to use the scientific/contextual motivation. We can also consider combining groups that we identify as not being significantly different from one another when making a pairwise comparison. HOWEVER:</span>
<span id="cb12-128"><a href="#cb12-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-129"><a href="#cb12-129" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>By combining groups it will alter the estimates and comparisons with the other (remaining) groups that are affected by sample size. For example, $n=3$ won't really impact the mean estimate for a group with $n=1000$.</span>
<span id="cb12-130"><a href="#cb12-130" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>If we have small sample sizes, we may be underpowered to detect a group difference and would combine groups just because "$p&gt;0.05$".</span>
<span id="cb12-131"><a href="#cb12-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-132"><a href="#cb12-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-133"><a href="#cb12-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cells means model formulation, interpretation, and use</span></span>
<span id="cb12-134"><a href="#cb12-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-135"><a href="#cb12-135" aria-hidden="true" tabindex="-1"></a>The cell means model makes the connection between the mean levels within a group more explicit. In this approach we would exclude the intercept and include an indicator variable for each group:</span>
<span id="cb12-136"><a href="#cb12-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-139"><a href="#cb12-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb12-140"><a href="#cb12-140" aria-hidden="true" tabindex="-1"></a>cell_means <span class="ot">&lt;-</span> <span class="fu">lm</span>(betaplas <span class="sc">~</span> smoke_factor <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data=</span>carotenoids)</span>
<span id="cb12-141"><a href="#cb12-141" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cell_means)<span class="sc">$</span>coefficients</span>
<span id="cb12-142"><a href="#cb12-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-143"><a href="#cb12-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-144"><a href="#cb12-144" aria-hidden="true" tabindex="-1"></a>In the model above, we see that the "reference" category from our reference cell model is now included as one of the predictors. We can also note that all the estimated coefficients represent the means for each smoking group!</span>
<span id="cb12-145"><a href="#cb12-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-146"><a href="#cb12-146" aria-hidden="true" tabindex="-1"></a>The *fitted* regression model would be</span>
<span id="cb12-147"><a href="#cb12-147" aria-hidden="true" tabindex="-1"></a>$$ \hat{Y} = 206.0510 I_N + 193.4696 I_F + 121.3256 I_C  $$</span>
<span id="cb12-148"><a href="#cb12-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-149"><a href="#cb12-149" aria-hidden="true" tabindex="-1"></a>The cell means model makes a more direct connection to the one-way ANOVA we've also seen (since we're only considering categorical variables here). However, we can also get the same estimates, as we saw before, with a reference cell model by combining our different estimated $\hat{\beta}$'s.</span>
<span id="cb12-150"><a href="#cb12-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-151"><a href="#cb12-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-152"><a href="#cb12-152" aria-hidden="true" tabindex="-1"></a><span class="fu">### An Example of Using Cell Means</span></span>
<span id="cb12-153"><a href="#cb12-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-154"><a href="#cb12-154" aria-hidden="true" tabindex="-1"></a>In practice, I've only recommend a cell means model one time. The investigator wanted to summarize the mean level of response to a hearing test across a combination of gerbil age (young vs. old) and sound setting (three levels) and compare if each response was equal to 0, where in this case the response of 0 indicated a null effect of the combination. The cell means model made this extremely intuitive since it combined the two factors and provided that exact hypothesis test from the $t$-test.</span>
<span id="cb12-155"><a href="#cb12-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-156"><a href="#cb12-156" aria-hidden="true" tabindex="-1"></a>For example, if we look at our plasma concentration for those under 50 years old vs. over 50 years old with smoking status, we would have:</span>
<span id="cb12-157"><a href="#cb12-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-160"><a href="#cb12-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb12-161"><a href="#cb12-161" aria-hidden="true" tabindex="-1"></a>carotenoids<span class="sc">$</span>AK_age_gte50 <span class="ot">&lt;-</span> carotenoids<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">50</span></span>
<span id="cb12-162"><a href="#cb12-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-163"><a href="#cb12-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate means by groups</span></span>
<span id="cb12-164"><a href="#cb12-164" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryBy</span>( betaplas <span class="sc">~</span> AK_age_gte50<span class="sc">*</span>smoke_factor, <span class="at">data=</span>carotenoids)</span>
<span id="cb12-165"><a href="#cb12-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-166"><a href="#cb12-166" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit cell means model with all groups</span></span>
<span id="cb12-167"><a href="#cb12-167" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>( betaplas <span class="sc">~</span> AK_age_gte50<span class="sc">:</span>smoke_factor <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data=</span>carotenoids))</span>
<span id="cb12-168"><a href="#cb12-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-169"><a href="#cb12-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-170"><a href="#cb12-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-171"><a href="#cb12-171" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>