---
title: "BIOS 6618 Labs and Practice Problems"
toc: FALSE
format:
  html:
    theme: flatly
---

```{r, echo=F, message=F, warning=F}
library(kableExtra)
library(dplyr)
```

This page includes our class' weekly labs and practice problems relating to the [lecture material](../bios_6618_materials/index.qmd). The practice problems are meant to provide additional examples of methods and coding approaches that can be used in completing the homework assignments and projects. The [BIOS 6618 Recitation page](../recitation/index.qmd) also includes responses to specific questions submitted by students that may provide additional examples and information.

+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| # Week/Topics                                                                               | # Lab and Practice Problem Description                                                                                                                                                                                                                                 | # Links                                                                                                                     |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
| **Week 2** <br>Normal Distribution and Central Limit Theorem                                | Three ways you can create vectors, different examples of using for loops, and the derivation of E(X) for an exponential distribution.                                                                                                                                  | [Lab](/labs/lab2/index.qmd); <br>[Practice Problems](/labs/prac2/index.qmd); <br>[Solutions](/labs/prac2s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems examine estimating the sample mean and sample variance for a Poisson distribution across a range of sample sizes, the theoretical and asymptotic results for some distributions, and the central limit theorem for chi-squared distributed data. |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 3** <br>Hypothesis Testing and Power                                                 | An introduction to writing your own functions in R and using the apply family of functions in place of for loops.                                                                                                                                                      | [Lab](/labs/lab3/index.qmd); <br>[Practice Problems](/labs/prac3/index.qmd); <br>[Solutions](/labs/prac3s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems work on subsetting a data frame of US states by various criteria, as well as an exercise identifying the relationship of how the various quantities in a power calculation change based on our lectures.                                         |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 4** <br>Diagnostic Testing and 2x2 Tables                                            | Exploring power calculations with known and unknown SD and creating plots across a range of scenarios using ggplot2.                                                                                                                                                   | [Lab](/labs/lab4/index.qmd); <br>[Practice Problems](/labs/prac4/index.qmd); <br>[Solutions](/labs/prac4s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | Practice problems examine RD/RR/OR, categorical data hypothesis testing, ROC curves, and sensitivity/specificity.                                                                                                                                                      |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 5** <br>Bootstrap Sampling and Nonparametric Tests                                   | Subsetting data and if/else statements are covered before exploring a simulation study to evaluate the challenges of multiple comparisons.                                                                                                                             | [Lab](/labs/lab5/index.qmd); <br>[Practice Problems](/labs/prac5/index.qmd); <br>[Solutions](/labs/prac5s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems give more exposure to bootstrap and permutation testing.                                                                                                                                                                                         |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 6** <br>Simple Linear Regression Intro and Derivations                               | A visual example of bootstrap and permutation resampling, as well as for the distribution of the ratio of sampling variances.                                                                                                                                          | [Lab](/labs/lab6/index.qmd); <br>[Practice Problems](/labs/prac6/index.qmd); <br>[Solutions](/labs/prac6s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problem focuses on the derivation of the sums of squares for our linear regression model.                                                                                                                                                                 |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 7** <br>SLR Diagnostics, Confidence/Prediction Intervals                             | Lab walks through the Midterm Simulation Project template files.                                                                                                                                                                                                       | [Practice Problems](/labs/prac7/index.qmd); <br>[Solutions](/labs/prac7s/index.qmd)                                         |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | Practice problems relate to simple linear regression modeling and interpretation.                                                                                                                                                                                      |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 8** <br>SLR Examples, Log(Y) Transformation                                          | PROC REG provides a beautiful ANOVA table in its output, but R's lm and glm do not. We discuss the ANOVA table in lab and how to create a function to generate your own.                                                                                               | [Lab](/labs/lab8/index.qmd); <br>[Practice Problems](/labs/prac8/index.qmd); <br>[Solutions](/labs/prac8s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems cover diagnostic plot interpretation and simple linear regression models with different data transformations.                                                                                                                                    |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 9** <br>Multiple Linear Regression and Matrix Approaches                             | Diagnostic plots can be one of the most efficient ways to evaluate if your model assumptions for regression are met. In this lab we dive into some examples of good (and bad) diagnostic plots.                                                                        | [Lab](/labs/lab9/index.qmd); <br>[Practice Problems](/labs/prac9/index.qmd); <br>[Solutions](/labs/prac9s/index.qmd)        |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems focus on a multiple linear regression problem with two binary and one continuous predictors using both existing functions and by coding your own matrices.                                                                                       |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 10** <br>Categorical Predictors and ANOVA                                            | Lab introduces the Final Data Analysis Project.                                                                                                                                                                                                                        | [Practice Problems](/labs/prac10/index.qmd); <br>[Solutions](/labs/prac10s/index.qmd)                                       |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems are on the ANOVA lectures and including categorical variables in your regression models.                                                                                                                                                         |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 11** <br>Confounding, Mediation, Interactions, and Polynomials                       | The partial F-test can be used for both an overall F-test of the model or to evaluate a single predictor (instead of the t-test), in lab we walk through an example contrasting these approaches.                                                                      | [Lab](/labs/lab11/index.qmd); <br>[Practice Problems](/labs/prac11/index.qmd); <br>[Solutions](/labs/prac11s/index.qmd)     |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems touch on special topics relating to this week (confounding, mediation, interactions, polynomials, and GLHT).                                                                                                                                     |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 12** <br>Model and Variable Selection, Outliers/Influential Points                   | Interactions can be tricky to interpret, so we review an example using the FEV data set during lab.                                                                                                                                                                    | [Lab](/labs/lab12/index.qmd); <br>[Practice Problems](/labs/prac12/index.qmd); <br>[Solutions](/labs/prac12s/index.qmd)     |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems examine influential points/outliers, model and variable selection, and a simulation study for model selection approaches.                                                                                                                        |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 13** <br>Segmented Regression, Quantile Regression, Splines, and Advanced Bootstraps | There are so many cool things we can do with extensions to the topics we've covered this semester. This week we explore quantile regression, segmented regression, splines, and advanced bootstrap topics, with a focus on some of these topics during lab.            | [Lab TBD](/labs/lab13/index.qmd); <br>[Practice Problems](/labs/prac13/index.qmd); <br>[Solutions](/labs/prac13s/index.qmd) |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | The practice problems focus on quantile regression, splines, and segmented regression models.                                                                                                                                                                          |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+
| **Week 14** <br>Bayesian Linear Regression                                                  | This week we introduce the Bayesian framework and see a linear regression example.                                                                                                                                                                                     | [Lab TBD](/labs/lab14/index.qmd); <br>[Practice Problems](/labs/prac14/index.qmd); <br>[Solutions](/labs/prac14s/index.qmd) |   |
|                                                                                             |                                                                                                                                                                                                                                                                        |                                                                                                                             |   |
|                                                                                             | Practice problems focus on re-analyzing data from our MLR examples with a Bayesian approach.                                                                                                                                                                           |                                                                                                                             |   |
+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---+

: {tbl-colwidths="\[25,60,15\]"}
