<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Kaizer">

<title>Alex Kaizer - Week 11 Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/size.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/academicons-1.9.1/css/academicons.css" rel="stylesheet">

<link rel="icon" type="image/png" href="./files/favicon.ico">

<script type="text/javascript">
function setBrand() {
document.getElementsByClassName("navbar-brand")[0].href="https://www.alexkaizer.com";
}
window.onload = setBrand;
</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5PBG7BL207"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5PBG7BL207');
</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Alex Kaizer</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/research" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/publications" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/teaching" rel="" target="">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6618" rel="" target="">
 <span class="dropdown-text">BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6611" rel="" target="">
 <span class="dropdown-text">BIOS 6611</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/study_design_berd" rel="" target="">
 <span class="dropdown-text">BERD Study Design Short Course</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/adaptivetrials_sc" rel="" target="">
 <span class="dropdown-text">WNAR Adaptive and Bayesian Clinical Trial Design Short Course</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bios-6618" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">BIOS 6618</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bios-6618">    
        <li>
    <a class="dropdown-item" href="../../index.html" rel="" target="">
 <span class="dropdown-text">Home</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../bios_6618_materials" rel="" target="">
 <span class="dropdown-text">Materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../journal_of_bios_6618" rel="" target="">
 <span class="dropdown-text">Journal of BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../recitation" rel="" target="">
 <span class="dropdown-text">Recitation Questions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs" rel="" target="">
 <span class="dropdown-text">Labs and Practice Problems</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:alex.kaizer@cuanschutz.edu" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=ICpH74EAAAAJ&amp;hl=en" rel="" target="">
 <span class="menu-text"><i class="ai  ai-google-scholar ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="http://github.com/alexbiostats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/files/Alex_CV.pdf" rel="" target="">
 <span class="menu-text"><i class="ai  ai-cv ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/alex-kaizer/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#whats-on-the-docket-this-week" id="toc-whats-on-the-docket-this-week" class="nav-link active" data-scroll-target="#whats-on-the-docket-this-week">What’s on the docket this week?</a></li>
  <li><a href="#motivating-example-and-our-questions-of-interest" id="toc-motivating-example-and-our-questions-of-interest" class="nav-link" data-scroll-target="#motivating-example-and-our-questions-of-interest">Motivating Example and Our Questions of Interest</a></li>
  <li><a href="#overall-test-of-the-model" id="toc-overall-test-of-the-model" class="nav-link" data-scroll-target="#overall-test-of-the-model">Overall Test of the Model</a>
  <ul class="collapse">
  <li><a href="#the-partial-f-test-for-the-overall-model" id="toc-the-partial-f-test-for-the-overall-model" class="nav-link" data-scroll-target="#the-partial-f-test-for-the-overall-model">The Partial F-test for the Overall Model</a></li>
  </ul></li>
  <li><a href="#is-age-significantly-associated-with-ease" id="toc-is-age-significantly-associated-with-ease" class="nav-link" data-scroll-target="#is-age-significantly-associated-with-ease">Is Age Significantly Associated with Ease?</a>
  <ul class="collapse">
  <li><a href="#the-partial-f-test-for-one-variable" id="toc-the-partial-f-test-for-one-variable" class="nav-link" data-scroll-target="#the-partial-f-test-for-one-variable">The Partial F-test for One Variable</a></li>
  </ul></li>
  <li><a href="#is-asa-status-significantly-associated-with-ease" id="toc-is-asa-status-significantly-associated-with-ease" class="nav-link" data-scroll-target="#is-asa-status-significantly-associated-with-ease">Is ASA Status Significantly Associated with Ease?</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Week 11 Lab</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Alex Kaizer </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Colorado-Anschutz Medical Campus
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<p>This page is part of the University of Colorado-Anschutz Medical Campus’ <a href="../../labs/index.html">BIOS 6618 Labs</a> collection, the mini-lecture content delivered at the start of class before breaking out into small groups to work on the homework assignment.</p>
<section id="whats-on-the-docket-this-week" class="level1">
<h1>What’s on the docket this week?</h1>
<p>This week we will present a few examples of how to do inference on different numbers of independent variables in a multiple linear regression model, while also seeing the connections between them. We’ll then break out into small groups to work on homework.</p>
<p>Also of potential use, our ANOVA function (code hidden below):</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r fold-hide code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>linreg_anova_func <span class="ot">&lt;-</span> <span class="cf">function</span>(mod, <span class="at">ndigits=</span><span class="dv">2</span>, <span class="at">p_ndigits=</span><span class="dv">3</span>, <span class="at">format=</span><span class="st">'kable'</span>){</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Function to create an ANOVA table linear regression results from lm or glm</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># mod: an object with the fitted model results</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ndigits: number of digits to round to for most values, default is 2</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># p_digits: number of digits to round the p-value to, default is 3</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># format: desired format output (default is kable):</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># "kable" for kable table</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># "df" for data frame as table</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># extract outcome from the object produced by the glm or lm function</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>( <span class="fu">class</span>(mod)[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">'glm'</span> ){</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    y <span class="ot">&lt;-</span> mod<span class="sc">$</span>y</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>( <span class="fu">class</span>(mod)[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">'lm'</span> ){</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    y <span class="ot">&lt;-</span> mod<span class="sc">$</span>model[,<span class="dv">1</span>] <span class="co"># first column contains outcome data</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  }  </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">length</span>(mod<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  ssm <span class="ot">&lt;-</span> <span class="fu">sum</span>( (yhat<span class="sc">-</span>ybar)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  sse <span class="ot">&lt;-</span> <span class="fu">sum</span>( (y<span class="sc">-</span>yhat)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  sst <span class="ot">&lt;-</span> <span class="fu">sum</span>( (y<span class="sc">-</span>ybar)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  msm <span class="ot">&lt;-</span> ssm<span class="sc">/</span>p</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  mse <span class="ot">&lt;-</span> sse<span class="sc">/</span>(n<span class="sc">-</span>p<span class="dv">-1</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  f_val <span class="ot">&lt;-</span> msm<span class="sc">/</span>mse</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  p_val <span class="ot">&lt;-</span> <span class="fu">pf</span>(f_val, <span class="at">df1=</span>p, <span class="at">df2=</span>n<span class="sc">-</span>p<span class="dv">-1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create an ANOVA table to summarize all our results:</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  p_digits <span class="ot">&lt;-</span> (<span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span>p_ndigits))</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  p_val_tab <span class="ot">&lt;-</span> <span class="cf">if</span>(p_val<span class="sc">&lt;</span>p_digits){<span class="fu">paste0</span>(<span class="st">'&lt;'</span>,p_digits)}<span class="cf">else</span>{<span class="fu">round</span>(p_val,p_ndigits)}</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  anova_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="st">'Source'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'Model'</span>,<span class="st">'Error'</span>,<span class="st">'Total'</span>),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'Sums of Squares'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(ssm,ndigits), <span class="fu">round</span>(sse,ndigits), <span class="fu">round</span>(sst,ndigits)),</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'Degrees of Freedom'</span> <span class="ot">=</span> <span class="fu">c</span>(p, n<span class="sc">-</span>p<span class="dv">-1</span>, n<span class="dv">-1</span>),</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'Mean Square'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(msm,ndigits), <span class="fu">round</span>(mse,ndigits),<span class="st">''</span>),</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'F Value'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(f_val,ndigits),<span class="st">''</span>,<span class="st">''</span>),</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'p-value'</span> <span class="ot">=</span> <span class="fu">c</span>(p_val_tab,<span class="st">''</span>,<span class="st">''</span>))</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>( format <span class="sc">==</span> <span class="st">'kable'</span> ){  </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="fu">library</span>(kableExtra)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(anova_table, <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">'Source'</span>,<span class="st">'Sums of Squares'</span>,<span class="st">'Degrees of Freedom'</span>,<span class="st">'Mean Square'</span>,<span class="st">'F-value'</span>,<span class="st">'p-value'</span>), <span class="at">align=</span><span class="st">'lccccc'</span>, <span class="at">escape=</span>F) <span class="sc">%&gt;%</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">"left"</span>)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  }<span class="cf">else</span>{</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    anova_table</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="motivating-example-and-our-questions-of-interest" class="level1">
<h1>Motivating Example and Our Questions of Interest</h1>
<p>We will work with the “Laryngoscope” dataset from the Teaching of Statistics in the Health Sciences (TSHS) section of the American Statistical Association. It was a randomized trial that enrolled 99 adult patients with a BMI between 30 and 50 who were undergoing elective surgery that required orotracheal intubation. Specifically the trial randomized between the Pentax AWS Video Laryngoscope (intervention) and the Macintosh Laryngoscope (control).</p>
<p>First, let’s read in the data:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../.data/Laryngoscope.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="sc">!</span><span class="fu">is.na</span>(dat<span class="sc">$</span>BMI),] <span class="co"># remove 2 cases with missing BMI for example</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>For our lab today we will use the ease of tracheal intubation (<code>ease</code>) as our outcome (i.e., dependent variable) that ranges from 0 to 100. For predictors in our <em>full</em> multiple regression model we wish to include BMI (<code>BMI</code>), age (<code>age</code>), group (<code>Randomization</code> where 0=Macintosh; 1=Pentax AWS), and ASA status (<code>asa</code>).</p>
<p>The ASA status is the American Society of Anesthesiologists physical status score and ranges from I to VI, with I being a healthy patient and VI being a brain dead patient whose organs are being removed for donor purposes. In our dataset we have scores from II to IV, suggesting mild disease to severe disease that is a threat to life.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's look at a few random rows to get a feel for the data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">19</span>,<span class="dv">80</span>,<span class="dv">97</span>),<span class="fu">c</span>(<span class="st">'ease'</span>,<span class="st">'BMI'</span>,<span class="st">'age'</span>,<span class="st">'Randomization'</span>,<span class="st">'asa'</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   ease   BMI age Randomization asa
3    80 41.60  37             0   3
6     2 44.00  39             0   3
19   10 46.65  67             0   4
80   10 35.63  34             1   2
99   15 36.81  52             1   2</code></pre>
</div>
</div>
<p>We will create our own indicator variables to help illustrate the different tests, but we will briefly show they are equivalent to a model where we let <code>R</code> do the coding for us behind the scenes:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>intervention <span class="ot">&lt;-</span> dat<span class="sc">$</span>Randomization<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>asa2 <span class="ot">&lt;-</span> dat<span class="sc">$</span>asa<span class="sc">==</span><span class="dv">2</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>asa3 <span class="ot">&lt;-</span> dat<span class="sc">$</span>asa<span class="sc">==</span><span class="dv">3</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>asa4 <span class="ot">&lt;-</span> dat<span class="sc">$</span>asa<span class="sc">==</span><span class="dv">4</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the full model with our indicator variables:</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>mod_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> intervention <span class="sc">+</span> asa3 <span class="sc">+</span> asa4, <span class="at">data=</span>dat)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the full model with R creating our indicator variables (note we need to tell R we want asa as a factor since it is currently a numeric variable)</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>mod_full_alt <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> Randomization <span class="sc">+</span> <span class="fu">as.factor</span>(asa), <span class="at">data=</span>dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>First let’s compare the coefficients tables from each model:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   Estimate Std. Error    t value   Pr(&gt;|t|)
(Intercept)      23.0525163 29.9243068  0.7703609 0.44308121
BMI              -0.3914850  0.5976937 -0.6549927 0.51412476
age               0.3961627  0.2334288  1.6971460 0.09308691
interventionTRUE 15.6814488  6.0557118  2.5895302 0.01119017
asa3TRUE         15.1790840  7.4266343  2.0438712 0.04385677
asa4TRUE          3.9915053 14.4022460  0.2771446 0.78229763</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full_alt)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate Std. Error    t value   Pr(&gt;|t|)
(Intercept)     23.0525163 29.9243068  0.7703609 0.44308121
BMI             -0.3914850  0.5976937 -0.6549927 0.51412476
age              0.3961627  0.2334288  1.6971460 0.09308691
Randomization   15.6814488  6.0557118  2.5895302 0.01119017
as.factor(asa)3 15.1790840  7.4266343  2.0438712 0.04385677
as.factor(asa)4  3.9915053 14.4022460  0.2771446 0.78229763</code></pre>
</div>
</div>
<p>Notice we have the same results, just with different labels based on if we used our coded indicator variable or let <code>R</code> do it for us. <strong>This does lead us to one aspect we have to be careful with…mistakenly treating categorical variables as continuous:</strong></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What happens if we forget to tell R asa is categorical</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> Randomization <span class="sc">+</span> asa, <span class="at">data=</span>dat))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error    t value   Pr(&gt;|t|)
(Intercept)    4.5166335 32.7571056  0.1378826 0.89063457
BMI           -0.2577513  0.5970688 -0.4316945 0.66697348
age            0.4264885  0.2346937  1.8172137 0.07243999
Randomization 14.1862614  6.0364689  2.3500927 0.02090637
asa            8.2613846  6.1183169  1.3502708 0.18024157</code></pre>
</div>
</div>
<p>Now our ASA status is treated as a continuous predictor, which likely does not make much sense given how it is defined.</p>
<p>Let’s now explore 3 different questions:</p>
<ol type="1">
<li>Are any of our variables significantly associated with ease of intubation?</li>
<li>Is age significantly associated with ease of intubation (over and above the contribution of other variables in the model)?</li>
<li>Is ASA significantly associated with ease of intubation (over and above the contribution of other variables in the model)?</li>
</ol>
</section>
<section id="overall-test-of-the-model" class="level1">
<h1>Overall Test of the Model</h1>
<p>To test if any of our <span class="math inline">\(\beta_{p} \neq 0\)</span> (<span class="math inline">\(p=1,2,3,4,5\)</span>), we can use the overall <span class="math inline">\(F\)</span>-test. This test result could come from our ANOVA table, using the <code>anova</code> function to compare the full and null (i.e., reduced model with no predictors) models, or by fitting an <code>lm</code> model and examining the summary output:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the ANOVA table to evaluate</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linreg_anova_func</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Sums of Squares</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Degrees of Freedom</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean Square</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">F-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model</td>
<td style="text-align: center;">12209.82</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2441.96</td>
<td style="text-align: center;">2.9</td>
<td style="text-align: center;">0.018</td>
</tr>
<tr class="even">
<td style="text-align: left;">Error</td>
<td style="text-align: center;">76538.67</td>
<td style="text-align: center;">91</td>
<td style="text-align: center;">841.08</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">88748.49</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>


</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the anova function to run the overall F-test</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>mod_null <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>dat) <span class="co"># fit the null/reduced model with no predictors</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full, mod_null, <span class="at">test=</span><span class="st">'F'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: ease ~ BMI + age + intervention + asa3 + asa4
Model 2: ease ~ 1
  Resid. Df Resid. Dev Df Deviance      F  Pr(&gt;F)  
1        91      76539                             
2        96      88748 -5   -12210 2.9034 0.01773 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the lm function summary</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> intervention <span class="sc">+</span> asa3 <span class="sc">+</span> asa4, <span class="at">data=</span>dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ease ~ BMI + age + intervention + asa3 + asa4, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-47.349 -24.566  -7.802  24.200  60.012 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)       23.0525    29.9243   0.770   0.4431  
BMI               -0.3915     0.5977  -0.655   0.5141  
age                0.3962     0.2334   1.697   0.0931 .
interventionTRUE  15.6814     6.0557   2.590   0.0112 *
asa3TRUE          15.1791     7.4266   2.044   0.0439 *
asa4TRUE           3.9915    14.4022   0.277   0.7823  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 29 on 91 degrees of freedom
Multiple R-squared:  0.1376,    Adjusted R-squared:  0.09019 
F-statistic: 2.903 on 5 and 91 DF,  p-value: 0.01773</code></pre>
</div>
</div>
<p>We arrive at the same answer with either approach: <span class="math inline">\(p=0.018\)</span>, which is less than 0.05, so we reject <span class="math inline">\(H_0\)</span> and conclude that at least one <span class="math inline">\(\beta_p\)</span> is significantly different from 0.</p>
<section id="the-partial-f-test-for-the-overall-model" class="level2">
<h2 class="anchored" data-anchor-id="the-partial-f-test-for-the-overall-model">The Partial F-test for the Overall Model</h2>
<p>We can also use the partial <span class="math inline">\(F\)</span>-test to address this question. It will be equivalent to our overall <span class="math inline">\(F\)</span>-test because <span class="math inline">\(SS_{model} = \sum_{i=1}^{n} (\hat{Y} - \overline{Y})^2\)</span>, but with no predictors <span class="math inline">\(\hat{Y} = \overline{Y} \implies \sum_{i=1}^{n} (\hat{Y} - \overline{Y})^2 = 0\)</span>.</p>
<p>For notation, let</p>
<ul>
<li><span class="math inline">\(n\)</span> be the number of observations</li>
<li><span class="math inline">\(p\)</span> be the number of IVs in the <em>reduced model</em></li>
<li><span class="math inline">\(k\)</span> the number of IVs <em>removed</em> from the full model</li>
<li><span class="math inline">\(p+k\)</span> the number of IVs in the <em>full model</em></li>
</ul>
<p>The partial <span class="math inline">\(F\)</span>-test is <span class="math display">\[ F = \frac{[SS_{model}(full) - SS_{model}(reduced)]/k}{MS_{error}(full)} \sim F_{k,n-p-k-1} \]</span></p>
<p>Therefore, our partial <span class="math inline">\(F\)</span>-test for the overall model becomes <span class="math display">\[ F = \frac{[SS_{model}(full) - 0]/k}{MS_{error}(full)} = \frac{MS_{model}(full)}{MS_{error}(full)}\sim F_{k,n-k-1} \]</span></p>
</section>
</section>
<section id="is-age-significantly-associated-with-ease" class="level1">
<h1>Is Age Significantly Associated with Ease?</h1>
<p>When evaluating if a single covariate of interest contributes above and beyond all other variables in the model we can use a <span class="math inline">\(t\)</span>-test to evaluate the significance. Often this information is also included in the regression table’s output:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   Estimate Std. Error    t value   Pr(&gt;|t|)
(Intercept)      23.0525163 29.9243068  0.7703609 0.44308121
BMI              -0.3914850  0.5976937 -0.6549927 0.51412476
age               0.3961627  0.2334288  1.6971460 0.09308691
interventionTRUE 15.6814488  6.0557118  2.5895302 0.01119017
asa3TRUE         15.1790840  7.4266343  2.0438712 0.04385677
asa4TRUE          3.9915053 14.4022460  0.2771446 0.78229763</code></pre>
</div>
</div>
<p>Here we are specifically testing if <span class="math inline">\(H_0\colon \beta_{Age} = 0\)</span> versus <span class="math inline">\(H_1\colon \beta_{Age} \neq 0\)</span>. From the output we see that <span class="math inline">\(t=1.697\)</span> and <span class="math inline">\(p=0.093\)</span> for age Since <span class="math inline">\(p &gt; 0.05 = \alpha\)</span>, we fail to reject <span class="math inline">\(H_0\)</span>. We cannot conclude that age is significantly associated with ease of intubation when adjusting for the contribution of all other covariates in the model.</p>
<p>In practice we may wish to remove age from the model since it would be more parsimonious. But there may also be clinical, biologic, or scientific reasons for keeping it in the model (e.g., confounding, etc.).</p>
<section id="the-partial-f-test-for-one-variable" class="level2">
<h2 class="anchored" data-anchor-id="the-partial-f-test-for-one-variable">The Partial F-test for One Variable</h2>
<p>We could also use the partial <span class="math inline">\(F\)</span>-test to evaluate if age on its own contributes to the explanation of the variability observed in our outcome above and beyond BMI, the study arm, or ASA status. In this case we’d fit our <em>reduced</em> model which excludes age and calculate the difference either by hand or using the <code>anova</code> function:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the reduced model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mod_red1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> intervention <span class="sc">+</span> asa3 <span class="sc">+</span> asa4, <span class="at">data=</span>dat)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Partial F-test with anova</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full, mod_red1, <span class="at">test=</span><span class="st">'F'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: ease ~ BMI + age + intervention + asa3 + asa4
Model 2: ease ~ BMI + intervention + asa3 + asa4
  Resid. Df Resid. Dev Df Deviance      F  Pr(&gt;F)  
1        91      76539                             
2        92      78961 -1  -2422.6 2.8803 0.09309 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA table to calculate partial F by hand</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linreg_anova_func</span>(mod_red1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Sums of Squares</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Degrees of Freedom</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean Square</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">F-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model</td>
<td style="text-align: center;">9787.24</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2446.81</td>
<td style="text-align: center;">2.85</td>
<td style="text-align: center;">0.028</td>
</tr>
<tr class="even">
<td style="text-align: left;">Error</td>
<td style="text-align: center;">78961.25</td>
<td style="text-align: center;">92</td>
<td style="text-align: center;">858.27</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">88748.49</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Based on our ANOVA tables we would have:</p>
<p><span class="math display">\[ F = \frac{[SS_{model}(full) - SS_{model}(reduced)]/k}{MS_{error}(full)} = \frac{[12209.82 - 9787.24]/1}{841.08} = 2.88 \]</span></p>
<p>Here we have <span class="math inline">\(n=97\)</span>, <span class="math inline">\(k=1\)</span>, and <span class="math inline">\(p=4\)</span>. So we would reference an <span class="math inline">\(F_{k,n-p-k-1} = F_{1,97-4-1-1} = F_{1,91}\)</span> distribution, where our critical value is <code>qf(0.95,1,91)</code>=3.946 and our p-value is <code>pf(2.88,1,91,lower.tail=F)</code>=0.093.</p>
<p>These estimates match our <code>anova</code> function results and the estimate from the table of coefficients. We can also note that our partial <span class="math inline">\(F\)</span> statistic is equal to <span class="math inline">\(t^2\)</span> for the variable being considered.</p>
</section>
</section>
<section id="is-asa-status-significantly-associated-with-ease" class="level1">
<h1>Is ASA Status Significantly Associated with Ease?</h1>
<p>Finally, we arrive at our third question: is ASA status significantly associated with ease of intubation above and beyond the other variables in the model?</p>
<p>When we have a categorical independent variable with more than 2 categories we have a natural application of the partial <span class="math inline">\(F\)</span>-test. With three ASA categories, if we drop one of the indicator variables we’d be changing the information included in the model! For example, dropping <code>asa3</code> and only keeping <code>asa4</code> would now transform our interpretation of <code>asa4</code> from being a comparison of ASA IV with the reference category of ASA II, to a comparison of ASA IV to the reference category of ASA III or IV.</p>
<p>For this reason, we generally evaluate the contribution of a categorical variable with &gt;2 categories using the partial <span class="math inline">\(F\)</span>-test. We want to know if the variable overall contributes to the model, not necessarily a single category. <em>That being said, we are many times interested in interpreting the effect of each category with respect to the reference category or between categories.</em></p>
<p>For the partial <span class="math inline">\(F\)</span>-test, we can again use <code>anova</code> or do the calculation by hand:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the reduced model</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mod_red2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> intervention, <span class="at">data=</span>dat)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Partial F-test with anova</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full, mod_red2, <span class="at">test=</span><span class="st">'F'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: ease ~ BMI + age + intervention + asa3 + asa4
Model 2: ease ~ BMI + age + intervention
  Resid. Df Resid. Dev Df Deviance      F Pr(&gt;F)
1        91      76539                          
2        93      80291 -2  -3752.1 2.2305 0.1133</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA table to calculate partial F by hand</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linreg_anova_func</span>(mod_red2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Sums of Squares</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Degrees of Freedom</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean Square</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">F-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model</td>
<td style="text-align: center;">8457.71</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2819.24</td>
<td style="text-align: center;">3.27</td>
<td style="text-align: center;">0.025</td>
</tr>
<tr class="even">
<td style="text-align: left;">Error</td>
<td style="text-align: center;">80290.78</td>
<td style="text-align: center;">93</td>
<td style="text-align: center;">863.34</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">88748.49</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Based on our ANOVA tables we would have:</p>
<p><span class="math display">\[ F = \frac{[SS_{model}(full) - SS_{model}(reduced)]/k}{MS_{error}(full)} = \frac{[12209.82 - 8457.71]/2}{841.08} = 2.2305 \]</span></p>
<p>Here we have <span class="math inline">\(n=97\)</span>, <span class="math inline">\(k=2\)</span>, and <span class="math inline">\(p=3\)</span>. So we would reference an <span class="math inline">\(F_{k,n-p-k-1} = F_{2,97-3-2-1} = F_{2,91}\)</span> distribution, where our critical value is <code>qf(0.95,2,91)</code>=3.097 and our p-value is <code>pf(2.2305,2,91,lower.tail=F)</code>=0.113.</p>
<p>In this case, we would fail to reject our <span class="math inline">\(H_0\)</span> that <span class="math inline">\(\beta_{ASA-III} = \beta_{ASA-IV} = 0\)</span>, because <span class="math inline">\(F=2.2305 &lt; 3.097\)</span> or <span class="math inline">\(p=0.113 &gt; 0.05\)</span>. Therefore, we <em>cannot</em> conclude that ASA status significantly contributes above and beyond age, BMI, and randomized group to the prediction of ease of intubation.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb25" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Week 11 Lab"</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Alex Kaizer</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co">  roles: "Instructor"</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co">  affiliation: University of Colorado-Anschutz Medical Campus</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc_float:</span><span class="co"> true</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> left</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap </span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=F, message=F, warning=F}</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>This page is part of the University of Colorado-Anschutz Medical Campus' <span class="co">[</span><span class="ot">BIOS 6618 Labs</span><span class="co">](/labs/index.qmd)</span> collection, the mini-lecture content delivered at the start of class before breaking out into small groups to work on the homework assignment.</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="fu"># What's on the docket this week?</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>This week we will present a few examples of how to do inference on different numbers of independent variables in a multiple linear regression model, while also seeing the connections between them. We'll then break out into small groups to work on homework.</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>Also of potential use, our ANOVA function (code hidden below):</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-hide'}</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>linreg_anova_func <span class="ot">&lt;-</span> <span class="cf">function</span>(mod, <span class="at">ndigits=</span><span class="dv">2</span>, <span class="at">p_ndigits=</span><span class="dv">3</span>, <span class="at">format=</span><span class="st">'kable'</span>){</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a><span class="do">## Function to create an ANOVA table linear regression results from lm or glm</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="co"># mod: an object with the fitted model results</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="co"># ndigits: number of digits to round to for most values, default is 2</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="co"># p_digits: number of digits to round the p-value to, default is 3</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="co"># format: desired format output (default is kable):</span></span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a><span class="co"># "kable" for kable table</span></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a><span class="co"># "df" for data frame as table</span></span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># extract outcome from the object produced by the glm or lm function</span></span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>( <span class="fu">class</span>(mod)[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">'glm'</span> ){</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>    y <span class="ot">&lt;-</span> mod<span class="sc">$</span>y</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>( <span class="fu">class</span>(mod)[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">'lm'</span> ){</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>    y <span class="ot">&lt;-</span> mod<span class="sc">$</span>model[,<span class="dv">1</span>] <span class="co"># first column contains outcome data</span></span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>  }  </span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>  ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod)</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">length</span>(mod<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb25-52"><a href="#cb25-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-53"><a href="#cb25-53" aria-hidden="true" tabindex="-1"></a>  ssm <span class="ot">&lt;-</span> <span class="fu">sum</span>( (yhat<span class="sc">-</span>ybar)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb25-54"><a href="#cb25-54" aria-hidden="true" tabindex="-1"></a>  sse <span class="ot">&lt;-</span> <span class="fu">sum</span>( (y<span class="sc">-</span>yhat)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb25-55"><a href="#cb25-55" aria-hidden="true" tabindex="-1"></a>  sst <span class="ot">&lt;-</span> <span class="fu">sum</span>( (y<span class="sc">-</span>ybar)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb25-56"><a href="#cb25-56" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-57"><a href="#cb25-57" aria-hidden="true" tabindex="-1"></a>  msm <span class="ot">&lt;-</span> ssm<span class="sc">/</span>p</span>
<span id="cb25-58"><a href="#cb25-58" aria-hidden="true" tabindex="-1"></a>  mse <span class="ot">&lt;-</span> sse<span class="sc">/</span>(n<span class="sc">-</span>p<span class="dv">-1</span>)</span>
<span id="cb25-59"><a href="#cb25-59" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-60"><a href="#cb25-60" aria-hidden="true" tabindex="-1"></a>  f_val <span class="ot">&lt;-</span> msm<span class="sc">/</span>mse</span>
<span id="cb25-61"><a href="#cb25-61" aria-hidden="true" tabindex="-1"></a>  p_val <span class="ot">&lt;-</span> <span class="fu">pf</span>(f_val, <span class="at">df1=</span>p, <span class="at">df2=</span>n<span class="sc">-</span>p<span class="dv">-1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb25-62"><a href="#cb25-62" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-63"><a href="#cb25-63" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create an ANOVA table to summarize all our results:</span></span>
<span id="cb25-64"><a href="#cb25-64" aria-hidden="true" tabindex="-1"></a>  p_digits <span class="ot">&lt;-</span> (<span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span>p_ndigits))</span>
<span id="cb25-65"><a href="#cb25-65" aria-hidden="true" tabindex="-1"></a>  p_val_tab <span class="ot">&lt;-</span> <span class="cf">if</span>(p_val<span class="sc">&lt;</span>p_digits){<span class="fu">paste0</span>(<span class="st">'&lt;'</span>,p_digits)}<span class="cf">else</span>{<span class="fu">round</span>(p_val,p_ndigits)}</span>
<span id="cb25-66"><a href="#cb25-66" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-67"><a href="#cb25-67" aria-hidden="true" tabindex="-1"></a>  anova_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="st">'Source'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'Model'</span>,<span class="st">'Error'</span>,<span class="st">'Total'</span>),</span>
<span id="cb25-68"><a href="#cb25-68" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'Sums of Squares'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(ssm,ndigits), <span class="fu">round</span>(sse,ndigits), <span class="fu">round</span>(sst,ndigits)),</span>
<span id="cb25-69"><a href="#cb25-69" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'Degrees of Freedom'</span> <span class="ot">=</span> <span class="fu">c</span>(p, n<span class="sc">-</span>p<span class="dv">-1</span>, n<span class="dv">-1</span>),</span>
<span id="cb25-70"><a href="#cb25-70" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'Mean Square'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(msm,ndigits), <span class="fu">round</span>(mse,ndigits),<span class="st">''</span>),</span>
<span id="cb25-71"><a href="#cb25-71" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'F Value'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(f_val,ndigits),<span class="st">''</span>,<span class="st">''</span>),</span>
<span id="cb25-72"><a href="#cb25-72" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'p-value'</span> <span class="ot">=</span> <span class="fu">c</span>(p_val_tab,<span class="st">''</span>,<span class="st">''</span>))</span>
<span id="cb25-73"><a href="#cb25-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-74"><a href="#cb25-74" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>( format <span class="sc">==</span> <span class="st">'kable'</span> ){  </span>
<span id="cb25-75"><a href="#cb25-75" aria-hidden="true" tabindex="-1"></a>    <span class="fu">library</span>(kableExtra)</span>
<span id="cb25-76"><a href="#cb25-76" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(anova_table, <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">'Source'</span>,<span class="st">'Sums of Squares'</span>,<span class="st">'Degrees of Freedom'</span>,<span class="st">'Mean Square'</span>,<span class="st">'F-value'</span>,<span class="st">'p-value'</span>), <span class="at">align=</span><span class="st">'lccccc'</span>, <span class="at">escape=</span>F) <span class="sc">%&gt;%</span></span>
<span id="cb25-77"><a href="#cb25-77" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">"left"</span>)</span>
<span id="cb25-78"><a href="#cb25-78" aria-hidden="true" tabindex="-1"></a>  }<span class="cf">else</span>{</span>
<span id="cb25-79"><a href="#cb25-79" aria-hidden="true" tabindex="-1"></a>    anova_table</span>
<span id="cb25-80"><a href="#cb25-80" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-81"><a href="#cb25-81" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-82"><a href="#cb25-82" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-83"><a href="#cb25-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-84"><a href="#cb25-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-85"><a href="#cb25-85" aria-hidden="true" tabindex="-1"></a><span class="fu"># Motivating Example and Our Questions of Interest</span></span>
<span id="cb25-86"><a href="#cb25-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-87"><a href="#cb25-87" aria-hidden="true" tabindex="-1"></a>We will work with the "Laryngoscope" dataset from the Teaching of Statistics in the Health Sciences (TSHS) section of the American Statistical Association. It was a randomized trial that enrolled 99 adult patients with a BMI between 30 and 50 who were undergoing elective surgery that required orotracheal intubation. Specifically the trial randomized between the Pentax AWS Video Laryngoscope (intervention) and the Macintosh Laryngoscope (control).</span>
<span id="cb25-88"><a href="#cb25-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-89"><a href="#cb25-89" aria-hidden="true" tabindex="-1"></a>First, let's read in the data:</span>
<span id="cb25-90"><a href="#cb25-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-91"><a href="#cb25-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-show'}</span></span>
<span id="cb25-92"><a href="#cb25-92" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../.data/Laryngoscope.csv'</span>)</span>
<span id="cb25-93"><a href="#cb25-93" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="sc">!</span><span class="fu">is.na</span>(dat<span class="sc">$</span>BMI),] <span class="co"># remove 2 cases with missing BMI for example</span></span>
<span id="cb25-94"><a href="#cb25-94" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-95"><a href="#cb25-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-96"><a href="#cb25-96" aria-hidden="true" tabindex="-1"></a>For our lab today we will use the ease of tracheal intubation (<span class="in">`ease`</span>) as our outcome (i.e., dependent variable) that ranges from 0 to 100. For predictors in our *full* multiple regression model we wish to include BMI (<span class="in">`BMI`</span>), age (<span class="in">`age`</span>), group (<span class="in">`Randomization`</span> where 0=Macintosh; 1=Pentax AWS), and ASA status (<span class="in">`asa`</span>). </span>
<span id="cb25-97"><a href="#cb25-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-98"><a href="#cb25-98" aria-hidden="true" tabindex="-1"></a>The ASA status is the American Society of Anesthesiologists physical status score and ranges from I to VI, with I being a healthy patient and VI being a brain dead patient whose organs are being removed for donor purposes. In our dataset we have scores from II to IV, suggesting mild disease to severe disease that is a threat to life.</span>
<span id="cb25-99"><a href="#cb25-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-100"><a href="#cb25-100" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-show'}</span></span>
<span id="cb25-101"><a href="#cb25-101" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's look at a few random rows to get a feel for the data</span></span>
<span id="cb25-102"><a href="#cb25-102" aria-hidden="true" tabindex="-1"></a>dat[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">19</span>,<span class="dv">80</span>,<span class="dv">97</span>),<span class="fu">c</span>(<span class="st">'ease'</span>,<span class="st">'BMI'</span>,<span class="st">'age'</span>,<span class="st">'Randomization'</span>,<span class="st">'asa'</span>)]</span>
<span id="cb25-103"><a href="#cb25-103" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-104"><a href="#cb25-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-105"><a href="#cb25-105" aria-hidden="true" tabindex="-1"></a>We will create our own indicator variables to help illustrate the different tests, but we will briefly show they are equivalent to a model where we let <span class="in">`R`</span> do the coding for us behind the scenes:</span>
<span id="cb25-106"><a href="#cb25-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-107"><a href="#cb25-107" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-show'}</span></span>
<span id="cb25-108"><a href="#cb25-108" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>intervention <span class="ot">&lt;-</span> dat<span class="sc">$</span>Randomization<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb25-109"><a href="#cb25-109" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>asa2 <span class="ot">&lt;-</span> dat<span class="sc">$</span>asa<span class="sc">==</span><span class="dv">2</span></span>
<span id="cb25-110"><a href="#cb25-110" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>asa3 <span class="ot">&lt;-</span> dat<span class="sc">$</span>asa<span class="sc">==</span><span class="dv">3</span></span>
<span id="cb25-111"><a href="#cb25-111" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>asa4 <span class="ot">&lt;-</span> dat<span class="sc">$</span>asa<span class="sc">==</span><span class="dv">4</span></span>
<span id="cb25-112"><a href="#cb25-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-113"><a href="#cb25-113" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the full model with our indicator variables:</span></span>
<span id="cb25-114"><a href="#cb25-114" aria-hidden="true" tabindex="-1"></a>mod_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> intervention <span class="sc">+</span> asa3 <span class="sc">+</span> asa4, <span class="at">data=</span>dat)</span>
<span id="cb25-115"><a href="#cb25-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-116"><a href="#cb25-116" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the full model with R creating our indicator variables (note we need to tell R we want asa as a factor since it is currently a numeric variable)</span></span>
<span id="cb25-117"><a href="#cb25-117" aria-hidden="true" tabindex="-1"></a>mod_full_alt <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> Randomization <span class="sc">+</span> <span class="fu">as.factor</span>(asa), <span class="at">data=</span>dat)</span>
<span id="cb25-118"><a href="#cb25-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-119"><a href="#cb25-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-120"><a href="#cb25-120" aria-hidden="true" tabindex="-1"></a>First let's compare the coefficients tables from each model:</span>
<span id="cb25-121"><a href="#cb25-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-122"><a href="#cb25-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-show'}</span></span>
<span id="cb25-123"><a href="#cb25-123" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)<span class="sc">$</span>coefficients</span>
<span id="cb25-124"><a href="#cb25-124" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full_alt)<span class="sc">$</span>coefficients</span>
<span id="cb25-125"><a href="#cb25-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-126"><a href="#cb25-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-127"><a href="#cb25-127" aria-hidden="true" tabindex="-1"></a>Notice we have the same results, just with different labels based on if we used our coded indicator variable or let <span class="in">`R`</span> do it for us. **This does lead us to one aspect we have to be careful with...mistakenly treating categorical variables as continuous:**</span>
<span id="cb25-128"><a href="#cb25-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-129"><a href="#cb25-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-show'}</span></span>
<span id="cb25-130"><a href="#cb25-130" aria-hidden="true" tabindex="-1"></a><span class="co"># What happens if we forget to tell R asa is categorical</span></span>
<span id="cb25-131"><a href="#cb25-131" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> Randomization <span class="sc">+</span> asa, <span class="at">data=</span>dat))<span class="sc">$</span>coefficients</span>
<span id="cb25-132"><a href="#cb25-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-133"><a href="#cb25-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-134"><a href="#cb25-134" aria-hidden="true" tabindex="-1"></a>Now our ASA status is treated as a continuous predictor, which likely does not make much sense given how it is defined.</span>
<span id="cb25-135"><a href="#cb25-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-136"><a href="#cb25-136" aria-hidden="true" tabindex="-1"></a>Let's now explore 3 different questions:</span>
<span id="cb25-137"><a href="#cb25-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-138"><a href="#cb25-138" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Are any of our variables significantly associated with ease of intubation?</span>
<span id="cb25-139"><a href="#cb25-139" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Is age significantly associated with ease of intubation (over and above the contribution of other variables in the model)?</span>
<span id="cb25-140"><a href="#cb25-140" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Is ASA significantly associated with ease of intubation (over and above the contribution of other variables in the model)?</span>
<span id="cb25-141"><a href="#cb25-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-142"><a href="#cb25-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-143"><a href="#cb25-143" aria-hidden="true" tabindex="-1"></a><span class="fu"># Overall Test of the Model</span></span>
<span id="cb25-144"><a href="#cb25-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-145"><a href="#cb25-145" aria-hidden="true" tabindex="-1"></a>To test if any of our $\beta_{p} \neq 0$ ($p=1,2,3,4,5$), we can use the overall $F$-test. This test result could come from our ANOVA table, using the <span class="in">`anova`</span> function to compare the full and null (i.e., reduced model with no predictors) models, or by fitting an <span class="in">`lm`</span> model and examining the summary output:</span>
<span id="cb25-146"><a href="#cb25-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-147"><a href="#cb25-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source = 'fold-show'}</span></span>
<span id="cb25-148"><a href="#cb25-148" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the ANOVA table to evaluate</span></span>
<span id="cb25-149"><a href="#cb25-149" aria-hidden="true" tabindex="-1"></a><span class="fu">linreg_anova_func</span>(mod_full)</span>
<span id="cb25-150"><a href="#cb25-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-151"><a href="#cb25-151" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the anova function to run the overall F-test</span></span>
<span id="cb25-152"><a href="#cb25-152" aria-hidden="true" tabindex="-1"></a>mod_null <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>dat) <span class="co"># fit the null/reduced model with no predictors</span></span>
<span id="cb25-153"><a href="#cb25-153" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full, mod_null, <span class="at">test=</span><span class="st">'F'</span>)</span>
<span id="cb25-154"><a href="#cb25-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-155"><a href="#cb25-155" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the lm function summary</span></span>
<span id="cb25-156"><a href="#cb25-156" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> intervention <span class="sc">+</span> asa3 <span class="sc">+</span> asa4, <span class="at">data=</span>dat))</span>
<span id="cb25-157"><a href="#cb25-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-158"><a href="#cb25-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-159"><a href="#cb25-159" aria-hidden="true" tabindex="-1"></a>We arrive at the same answer with either approach: $p=0.018$, which is less than 0.05, so we reject $H_0$ and conclude that at least one $\beta_p$ is significantly different from 0.</span>
<span id="cb25-160"><a href="#cb25-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-161"><a href="#cb25-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-162"><a href="#cb25-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Partial F-test for the Overall Model</span></span>
<span id="cb25-163"><a href="#cb25-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-164"><a href="#cb25-164" aria-hidden="true" tabindex="-1"></a>We can also use the partial $F$-test to address this question. It will be equivalent to our overall $F$-test because $SS_{model} = \sum_{i=1}^{n} (\hat{Y} - \overline{Y})^2$, but with no predictors $\hat{Y} = \overline{Y} \implies \sum_{i=1}^{n} (\hat{Y} - \overline{Y})^2 = 0$. </span>
<span id="cb25-165"><a href="#cb25-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-166"><a href="#cb25-166" aria-hidden="true" tabindex="-1"></a>For notation, let </span>
<span id="cb25-167"><a href="#cb25-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-168"><a href="#cb25-168" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$n$ be the number of observations</span>
<span id="cb25-169"><a href="#cb25-169" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$p$ be the number of IVs in the *reduced model*</span>
<span id="cb25-170"><a href="#cb25-170" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$k$ the number of IVs *removed* from the full model</span>
<span id="cb25-171"><a href="#cb25-171" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$p+k$ the number of IVs in the *full model*</span>
<span id="cb25-172"><a href="#cb25-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-173"><a href="#cb25-173" aria-hidden="true" tabindex="-1"></a>The partial $F$-test is</span>
<span id="cb25-174"><a href="#cb25-174" aria-hidden="true" tabindex="-1"></a>$$ F = \frac{<span class="co">[</span><span class="ot">SS_{model}(full) - SS_{model}(reduced)</span><span class="co">]</span>/k}{MS_{error}(full)} \sim F_{k,n-p-k-1} $$</span>
<span id="cb25-175"><a href="#cb25-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-176"><a href="#cb25-176" aria-hidden="true" tabindex="-1"></a>Therefore, our partial $F$-test for the overall model becomes</span>
<span id="cb25-177"><a href="#cb25-177" aria-hidden="true" tabindex="-1"></a>$$ F = \frac{<span class="co">[</span><span class="ot">SS_{model}(full) - 0</span><span class="co">]</span>/k}{MS_{error}(full)} = \frac{MS_{model}(full)}{MS_{error}(full)}\sim F_{k,n-k-1} $$</span>
<span id="cb25-178"><a href="#cb25-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-179"><a href="#cb25-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-180"><a href="#cb25-180" aria-hidden="true" tabindex="-1"></a><span class="fu"># Is Age Significantly Associated with Ease?</span></span>
<span id="cb25-181"><a href="#cb25-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-182"><a href="#cb25-182" aria-hidden="true" tabindex="-1"></a>When evaluating if a single covariate of interest contributes above and beyond all other variables in the model we can use a $t$-test to evaluate the significance. Often this information is also included in the regression table's output:</span>
<span id="cb25-183"><a href="#cb25-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-186"><a href="#cb25-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-187"><a href="#cb25-187" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)<span class="sc">$</span>coefficients</span>
<span id="cb25-188"><a href="#cb25-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-189"><a href="#cb25-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-190"><a href="#cb25-190" aria-hidden="true" tabindex="-1"></a>Here we are specifically testing if $H_0\colon \beta_{Age} = 0$ versus $H_1\colon \beta_{Age} \neq 0$. From the output we see that $t=1.697$ and $p=0.093$ for age Since $p &gt; 0.05 = \alpha$, we fail to reject $H_0$. We cannot conclude that age is significantly associated with ease of intubation when adjusting for the contribution of all other covariates in the model.</span>
<span id="cb25-191"><a href="#cb25-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-192"><a href="#cb25-192" aria-hidden="true" tabindex="-1"></a>In practice we may wish to remove age from the model since it would be more parsimonious. But there may also be clinical, biologic, or scientific reasons for keeping it in the model (e.g., confounding, etc.).</span>
<span id="cb25-193"><a href="#cb25-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-194"><a href="#cb25-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-195"><a href="#cb25-195" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Partial F-test for One Variable</span></span>
<span id="cb25-196"><a href="#cb25-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-197"><a href="#cb25-197" aria-hidden="true" tabindex="-1"></a>We could also use the partial $F$-test to evaluate if age on its own contributes to the explanation of the variability observed in our outcome above and beyond BMI, the study arm, or ASA status. In this case we'd fit our *reduced* model which excludes age and calculate the difference either by hand or using the <span class="in">`anova`</span> function:</span>
<span id="cb25-198"><a href="#cb25-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-199"><a href="#cb25-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source='fold-show'}</span></span>
<span id="cb25-200"><a href="#cb25-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the reduced model</span></span>
<span id="cb25-201"><a href="#cb25-201" aria-hidden="true" tabindex="-1"></a>mod_red1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> intervention <span class="sc">+</span> asa3 <span class="sc">+</span> asa4, <span class="at">data=</span>dat)</span>
<span id="cb25-202"><a href="#cb25-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-203"><a href="#cb25-203" aria-hidden="true" tabindex="-1"></a><span class="co"># Partial F-test with anova</span></span>
<span id="cb25-204"><a href="#cb25-204" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full, mod_red1, <span class="at">test=</span><span class="st">'F'</span>)</span>
<span id="cb25-205"><a href="#cb25-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-206"><a href="#cb25-206" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA table to calculate partial F by hand</span></span>
<span id="cb25-207"><a href="#cb25-207" aria-hidden="true" tabindex="-1"></a><span class="fu">linreg_anova_func</span>(mod_red1)</span>
<span id="cb25-208"><a href="#cb25-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-209"><a href="#cb25-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-210"><a href="#cb25-210" aria-hidden="true" tabindex="-1"></a>Based on our ANOVA tables we would have:</span>
<span id="cb25-211"><a href="#cb25-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-212"><a href="#cb25-212" aria-hidden="true" tabindex="-1"></a>$$ F = \frac{<span class="co">[</span><span class="ot">SS_{model}(full) - SS_{model}(reduced)</span><span class="co">]</span>/k}{MS_{error}(full)} = \frac{<span class="co">[</span><span class="ot">12209.82 - 9787.24</span><span class="co">]</span>/1}{841.08} = 2.88 $$</span>
<span id="cb25-213"><a href="#cb25-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-214"><a href="#cb25-214" aria-hidden="true" tabindex="-1"></a>Here we have $n=97$, $k=1$, and $p=4$. So we would reference an $F_{k,n-p-k-1} = F_{1,97-4-1-1} = F_{1,91}$ distribution, where our critical value is <span class="in">`qf(0.95,1,91)`</span>=<span class="in">`r round(qf(0.95,1,91),3)`</span> and our p-value is <span class="in">`pf(2.88,1,91,lower.tail=F)`</span>=<span class="in">`r round(pf(2.88,1,91,lower.tail=F),3)`</span>. </span>
<span id="cb25-215"><a href="#cb25-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-216"><a href="#cb25-216" aria-hidden="true" tabindex="-1"></a>These estimates match our <span class="in">`anova`</span> function results and the estimate from the table of coefficients. We can also note that our partial $F$ statistic is equal to $t^2$ for the variable being considered.</span>
<span id="cb25-217"><a href="#cb25-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-218"><a href="#cb25-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-219"><a href="#cb25-219" aria-hidden="true" tabindex="-1"></a><span class="fu"># Is ASA Status Significantly Associated with Ease?</span></span>
<span id="cb25-220"><a href="#cb25-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-221"><a href="#cb25-221" aria-hidden="true" tabindex="-1"></a>Finally, we arrive at our third question: is ASA status significantly associated with ease of intubation above and beyond the other variables in the model?</span>
<span id="cb25-222"><a href="#cb25-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-223"><a href="#cb25-223" aria-hidden="true" tabindex="-1"></a>When we have a categorical independent variable with more than 2 categories we have a natural application of the partial $F$-test. With three ASA categories, if we drop one of the indicator variables we'd be changing the information included in the model! For example, dropping <span class="in">`asa3`</span> and only keeping <span class="in">`asa4`</span> would now transform our interpretation of <span class="in">`asa4`</span> from being a comparison of ASA IV with the reference category of ASA II, to a comparison of ASA IV to the reference category of ASA III or IV.</span>
<span id="cb25-224"><a href="#cb25-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-225"><a href="#cb25-225" aria-hidden="true" tabindex="-1"></a>For this reason, we generally evaluate the contribution of a categorical variable with &gt;2 categories using the partial $F$-test. We want to know if the variable overall contributes to the model, not necessarily a single category. *That being said, we are many times interested in interpreting the effect of each category with respect to the reference category or between categories.*</span>
<span id="cb25-226"><a href="#cb25-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-227"><a href="#cb25-227" aria-hidden="true" tabindex="-1"></a>For the partial $F$-test, we can again use <span class="in">`anova`</span> or do the calculation by hand:</span>
<span id="cb25-228"><a href="#cb25-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-229"><a href="#cb25-229" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source='fold-show'}</span></span>
<span id="cb25-230"><a href="#cb25-230" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the reduced model</span></span>
<span id="cb25-231"><a href="#cb25-231" aria-hidden="true" tabindex="-1"></a>mod_red2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ease <span class="sc">~</span> BMI <span class="sc">+</span> age <span class="sc">+</span> intervention, <span class="at">data=</span>dat)</span>
<span id="cb25-232"><a href="#cb25-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-233"><a href="#cb25-233" aria-hidden="true" tabindex="-1"></a><span class="co"># Partial F-test with anova</span></span>
<span id="cb25-234"><a href="#cb25-234" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full, mod_red2, <span class="at">test=</span><span class="st">'F'</span>)</span>
<span id="cb25-235"><a href="#cb25-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-236"><a href="#cb25-236" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA table to calculate partial F by hand</span></span>
<span id="cb25-237"><a href="#cb25-237" aria-hidden="true" tabindex="-1"></a><span class="fu">linreg_anova_func</span>(mod_red2)</span>
<span id="cb25-238"><a href="#cb25-238" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-239"><a href="#cb25-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-240"><a href="#cb25-240" aria-hidden="true" tabindex="-1"></a>Based on our ANOVA tables we would have:</span>
<span id="cb25-241"><a href="#cb25-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-242"><a href="#cb25-242" aria-hidden="true" tabindex="-1"></a>$$ F = \frac{<span class="co">[</span><span class="ot">SS_{model}(full) - SS_{model}(reduced)</span><span class="co">]</span>/k}{MS_{error}(full)} = \frac{<span class="co">[</span><span class="ot">12209.82 - 8457.71</span><span class="co">]</span>/2}{841.08} = 2.2305 $$</span>
<span id="cb25-243"><a href="#cb25-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-244"><a href="#cb25-244" aria-hidden="true" tabindex="-1"></a>Here we have $n=97$, $k=2$, and $p=3$. So we would reference an $F_{k,n-p-k-1} = F_{2,97-3-2-1} = F_{2,91}$ distribution, where our critical value is <span class="in">`qf(0.95,2,91)`</span>=<span class="in">`r round(qf(0.95,2,91),3)`</span> and our p-value is <span class="in">`pf(2.2305,2,91,lower.tail=F)`</span>=<span class="in">`r round(pf(2.2305,2,91,lower.tail=F),3)`</span>. </span>
<span id="cb25-245"><a href="#cb25-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-246"><a href="#cb25-246" aria-hidden="true" tabindex="-1"></a>In this case, we would fail to reject our $H_0$ that $\beta_{ASA-III} = \beta_{ASA-IV} = 0$, because $F=2.2305 &lt; 3.097$ or $p=0.113 &gt; 0.05$. Therefore, we *cannot* conclude that ASA status significantly contributes above and beyond age, BMI, and randomized group to the prediction of ease of intubation.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>