<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Kaizer">

<title>Alex Kaizer - Week 12 Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/academicons-1.9.2/size.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/academicons-1.9.1/css/academicons.css" rel="stylesheet">

<link rel="icon" type="image/png" href="./files/favicon.ico">

<script type="text/javascript">
function setBrand() {
document.getElementsByClassName("navbar-brand")[0].href="https://www.alexkaizer.com";
}
window.onload = setBrand;
</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5PBG7BL207"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5PBG7BL207');
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Alex Kaizer</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/research" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/publications" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/teaching" rel="" target="">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6618" rel="" target="">
 <span class="dropdown-text">BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/bios_6611" rel="" target="">
 <span class="dropdown-text">BIOS 6611</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/study_design_berd" rel="" target="">
 <span class="dropdown-text">BERD Study Design Short Course</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.alexkaizer.com/adaptivetrials_sc" rel="" target="">
 <span class="dropdown-text">WNAR Adaptive and Bayesian Clinical Trial Design Short Course</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bios-6618" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">BIOS 6618</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bios-6618">    
        <li>
    <a class="dropdown-item" href="../../index.html" rel="" target="">
 <span class="dropdown-text">Home</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../bios_6618_materials" rel="" target="">
 <span class="dropdown-text">Materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../journal_of_bios_6618" rel="" target="">
 <span class="dropdown-text">Journal of BIOS 6618</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../recitation" rel="" target="">
 <span class="dropdown-text">Recitation Questions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs" rel="" target="">
 <span class="dropdown-text">Labs and Practice Problems</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:alex.kaizer@cuanschutz.edu" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=ICpH74EAAAAJ&amp;hl=en" rel="" target="">
 <span class="menu-text"><i class="ai  ai-google-scholar ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="http://github.com/alexbiostats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.alexkaizer.com/files/Alex_CV.pdf" rel="" target="">
 <span class="menu-text"><i class="ai  ai-cv ai-large"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/alex-kaizer/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#whats-on-the-docket-this-week" id="toc-whats-on-the-docket-this-week" class="nav-link active" data-scroll-target="#whats-on-the-docket-this-week">What’s on the docket this week?</a></li>
  <li><a href="#interactions-definition" id="toc-interactions-definition" class="nav-link" data-scroll-target="#interactions-definition">Interactions: Definition</a></li>
  <li><a href="#interactions-example-from-fev-dataset" id="toc-interactions-example-from-fev-dataset" class="nav-link" data-scroll-target="#interactions-example-from-fev-dataset">Interactions Example from FEV Dataset</a>
  <ul class="collapse">
  <li><a href="#the-regression-equation-for-smokers-vs.-non-smokers" id="toc-the-regression-equation-for-smokers-vs.-non-smokers" class="nav-link" data-scroll-target="#the-regression-equation-for-smokers-vs.-non-smokers">The Regression Equation for Smokers vs.&nbsp;Non-smokers</a></li>
  <li><a href="#interpreting-the-beta-coefficients" id="toc-interpreting-the-beta-coefficients" class="nav-link" data-scroll-target="#interpreting-the-beta-coefficients">Interpreting the Beta Coefficients</a></li>
  <li><a href="#inference-for-non-smokers-i.e.-the-reference-category" id="toc-inference-for-non-smokers-i.e.-the-reference-category" class="nav-link" data-scroll-target="#inference-for-non-smokers-i.e.-the-reference-category">Inference for Non-Smokers (i.e., the Reference Category)</a></li>
  <li><a href="#inference-for-smokers" id="toc-inference-for-smokers" class="nav-link" data-scroll-target="#inference-for-smokers">Inference for Smokers</a></li>
  <li><a href="#option-1-use-the-variance-covariance-matrix" id="toc-option-1-use-the-variance-covariance-matrix" class="nav-link" data-scroll-target="#option-1-use-the-variance-covariance-matrix">Option 1: Use the Variance-Covariance Matrix</a></li>
  <li><a href="#option-2-use-general-linear-hypothesis-tests" id="toc-option-2-use-general-linear-hypothesis-tests" class="nav-link" data-scroll-target="#option-2-use-general-linear-hypothesis-tests">Option 2: Use General Linear Hypothesis Tests</a></li>
  <li><a href="#option-3-use-reverse-coding-of-the-categorical-predictor" id="toc-option-3-use-reverse-coding-of-the-categorical-predictor" class="nav-link" data-scroll-target="#option-3-use-reverse-coding-of-the-categorical-predictor">Option 3: Use Reverse Coding of the Categorical Predictor</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Week 12 Lab</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Alex Kaizer </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Colorado-Anschutz Medical Campus
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<p>This page is part of the University of Colorado-Anschutz Medical Campus’ <a href="../../labs/index.html">BIOS 6618 Labs</a> collection, the mini-lecture content delivered at the start of class before breaking out into small groups to work on the homework assignment.</p>
<section id="whats-on-the-docket-this-week" class="level1">
<h1>What’s on the docket this week?</h1>
<p>We are diving into some examples of interactions and how to conduct inference on them (a notoriously tricky topic!). We’ll then spend the rest of time breaking out into groups to work on homework.</p>
</section>
<section id="interactions-definition" class="level1">
<h1>Interactions: Definition</h1>
<p>Effect modification or interaction is when the relationship between our outcome, <span class="math inline">\(Y\)</span>, and primary explanatory variable (PEV), <span class="math inline">\(X\)</span>, varies by some other covariate, <span class="math inline">\(C\)</span>. Specifically the terms are defined as:</p>
<ul>
<li><p><strong>Effect Modification:</strong> non-quantitative clinical or biological attribute of <em>population</em></p></li>
<li><p><strong>Interaction:</strong> quantitative attribute of a <em>dataset</em>, may be scale dependent</p></li>
</ul>
<p>An <strong>effect modifier</strong> or <strong>moderator</strong> is the variable that “causes” the effect modification. If a variable is an effect modifier, the role as a possible confounder is secondary.</p>
</section>
<section id="interactions-example-from-fev-dataset" class="level1">
<h1>Interactions Example from FEV Dataset</h1>
<p>In our slide deck on effect modification we examined Rosner’s FEV dataset for the outcome of FEV predicted by smoking status (smoker vs.&nbsp;non-smoker), age (from 3 to 19), and their interaction. The fitted regression model was</p>
<p><span class="math inline">\(\begin{aligned} \hat{Y} =&amp; \hat\beta_0 + \hat\beta_1 X_1 + \hat\beta_2 X_2 + \hat\beta_3 X_1 X_2 \\ =&amp; 0.25 + 1.94 \times \text{Smoker} + 0.24 \times \text{Age} + (-0.16 \times \text{Smoker} \times \text{Age} ) \end{aligned}\)</span></p>
<section id="the-regression-equation-for-smokers-vs.-non-smokers" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-equation-for-smokers-vs.-non-smokers">The Regression Equation for Smokers vs.&nbsp;Non-smokers</h2>
<p>Given that smoking status is a categorical predictor, we may be interested in using the fitted regression model above and simplifying it to be from the perspective of nonsmokers and smokers. This can help us more clearly identify the intercept and slope(s) for the two groups.</p>
<p>For <em>non-smokers</em> we can think of this as taking our fitted regression equation from above, plugging in “0” for “Smoker”, and focusing on simplified regression equation:</p>
<p><span class="math inline">\(\begin{aligned} \hat{Y}_{nonsmk} =&amp; 0.25 + 1.94 \times 0 + 0.24 \times \text{Age} + (-0.16 \times 0 \times \text{Age} ) \\ =&amp; 0.25 + 0.24 \times \text{Age} \end{aligned}\)</span></p>
<p>Likewise, for <em>smokers</em> we can think of this as plugging in “1” for “Smoker”:</p>
<p><span class="math inline">\(\begin{aligned} \hat{Y}_{smk} =&amp; 0.25 + 1.94 \times 1 + 0.24 \times \text{Age} + (-0.16 \times 1 \times \text{Age} ) \\ =&amp; (0.25+1.94) + (0.24-0.16) \times \text{Age} \\ =&amp; 2.19 + 0.08 \times \text{Age} \end{aligned}\)</span></p>
<p>With these two regression equations, we can see that smokers and nonsmokers have different intercepts and slopes for age. We can also see that the intercept and slope for <em>smokers</em> is based on the sum of different <span class="math inline">\(\hat\beta\)</span>’s. Visually this would look something like:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>fev <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../.data/FEV_rosner.csv'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>fev<span class="sc">$</span>pch <span class="ot">&lt;-</span> <span class="dv">0</span>; fev<span class="sc">$</span>pch[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)] <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>fev<span class="sc">$</span>col <span class="ot">&lt;-</span> <span class="st">'green3'</span>; fev<span class="sc">$</span>col[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)] <span class="ot">&lt;-</span> <span class="st">'blue'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Code to generate picture</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#FEV figure with regression lines for FEV ~ smoking status + age + smoke*age (slide 11)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>lmfi <span class="ot">&lt;-</span> <span class="fu">lm</span>( fev <span class="sc">~</span> smoke <span class="sc">*</span> age, <span class="at">data=</span>fev)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>fev<span class="sc">$</span>age, <span class="at">y=</span>fev<span class="sc">$</span>fev, <span class="at">pch=</span>fev<span class="sc">$</span>pch,<span class="at">col=</span>fev<span class="sc">$</span>col,<span class="at">cex=</span><span class="fl">0.8</span>, <span class="at">xlab=</span><span class="st">'Age (years)'</span>, <span class="at">ylab=</span><span class="st">'FEV (liters)'</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x=</span>fev<span class="sc">$</span>age[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)], <span class="at">y=</span>fev<span class="sc">$</span>fev[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)], <span class="at">pch=</span>fev<span class="sc">$</span>pch[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)],<span class="at">col=</span>fev<span class="sc">$</span>col[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)],<span class="at">cex=</span><span class="fl">0.8</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>) ), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'green4'</span> )</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>) <span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">4</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>) ) , <span class="at">lty=</span><span class="dv">2</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'blue4'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>) ), <span class="at">lty=</span><span class="dv">4</span>, <span class="at">col=</span><span class="st">'green4'</span> )</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">4</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>) ) , <span class="at">lty=</span><span class="dv">4</span>, <span class="at">col=</span><span class="st">'blue4'</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, <span class="at">col=</span><span class="st">'gray65'</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'topleft'</span>,<span class="at">inset=</span><span class="fl">0.005</span>,<span class="at">bg=</span><span class="st">'white'</span>,<span class="at">box.col=</span><span class="st">'white'</span>,<span class="at">pch=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">15</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="st">'green3'</span>,<span class="st">'blue'</span>),<span class="at">legend=</span><span class="fu">c</span>(<span class="st">'Non-Smoker'</span>,<span class="st">'Smoker'</span>))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(  <span class="fu">expression</span>(<span class="fu">hat</span>(Y) <span class="sc">==</span> <span class="fu">hat</span>(beta)[<span class="dv">0</span>] <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">1</span>] <span class="sc">*</span> Smoke <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">2</span>] <span class="sc">*</span> Age <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">3</span>] <span class="sc">*</span> Smoke <span class="sc">%*%</span> Age) )</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">15</span>, <span class="at">y =</span> <span class="dv">1</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(Y)[nonsmk] <span class="sc">==</span> (<span class="fu">hat</span>(beta)[<span class="dv">0</span>]<span class="sc">+</span><span class="dv">0</span>) <span class="sc">+</span> (<span class="fu">hat</span>(beta)[<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">0</span>) <span class="sc">%*%</span> Age), <span class="at">col=</span><span class="st">'green4'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">5.5</span>, <span class="at">y =</span> <span class="fl">4.4</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(Y)[smk] <span class="sc">==</span> (<span class="fu">hat</span>(beta)[<span class="dv">0</span>]<span class="sc">+</span><span class="fu">hat</span>(beta)[<span class="dv">1</span>]) <span class="sc">+</span> (<span class="fu">hat</span>(beta)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">3</span>]) <span class="sc">%*%</span> Age), <span class="at">col=</span><span class="st">'blue4'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">y=</span><span class="fu">c</span>(<span class="fu">coef</span>(lmfi)[<span class="dv">1</span>],<span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>]), <span class="at">col=</span><span class="st">'purple'</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="sc">-</span>.<span class="dv">25</span>, <span class="at">y=</span><span class="fl">1.3</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>]), <span class="at">col=</span><span class="st">'purple'</span>, <span class="at">pos=</span><span class="dv">4</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="sc">-</span>.<span class="dv">1</span>, <span class="at">y=</span><span class="fl">0.15</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">0</span>]), <span class="at">col=</span><span class="st">'green3'</span>, <span class="at">pos=</span><span class="dv">4</span>, <span class="at">cex=</span><span class="fl">1.2</span>); <span class="fu">points</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">y=</span><span class="fu">coef</span>(lmfi)[<span class="dv">1</span>], <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">'green3'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="sc">-</span>.<span class="dv">1</span>, <span class="at">y=</span><span class="dv">2</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">0</span>] <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">1</span>]), <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">pos=</span><span class="dv">4</span>, <span class="at">cex=</span><span class="fl">1.2</span>); <span class="fu">points</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">y=</span><span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>], <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpreting-the-beta-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-beta-coefficients">Interpreting the Beta Coefficients</h2>
<p>The meaning of each <span class="math inline">\(\hat{\beta}\)</span> is:</p>
<ul>
<li><p><span class="math inline">\(\hat\beta_0\)</span>: estimated average FEV for non-smokers at age 0 (i.e., all <span class="math inline">\(X=0\)</span>)</p></li>
<li><p><span class="math inline">\(\hat\beta_1\)</span>: estimated difference in FEV at age 0 between smokers and non-smokers (i.e., difference in intercepts)</p></li>
<li><p><span class="math inline">\(\hat\beta_2\)</span>: estimated slope for age for <em>non-smokers</em> (increase in FEV per year of age for non-smokers)</p></li>
<li><p><span class="math inline">\(\hat\beta_3\)</span>: estimated <em>difference</em> in slope between smokers and non-smokers</p></li>
<li><p><span class="math inline">\(\hat\beta_0 + \hat\beta_1\)</span>: estimated average FEV for smokers at age 0 (i.e., here <span class="math inline">\(X_1=1\)</span>, but <span class="math inline">\(X_1=0\)</span> still)</p></li>
<li><p><span class="math inline">\(\hat\beta_2 + \hat\beta_3\)</span>: estimated slope for age for <em>smokers</em> (increase in FEV per year of age for smokers)</p></li>
</ul>
<p>Based on our interpretation above, we may be interested in formally testing the hypothesis that any one of our estimates is significantly different from 0. Fortunately, if we wish to test any of the <span class="math inline">\(\hat\beta\)</span>’s on their own (i.e., not <span class="math inline">\(\hat\beta_i + \hat\beta_j\)</span>), we can simply use the regression output:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( fev <span class="sc">~</span> smoke <span class="sc">*</span> age, <span class="at">data=</span>fev)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate Std. Error   t value      Pr(&gt;|t|)
(Intercept)      0.2533955 0.08265075  3.065859  2.260474e-03
smokesmoker      1.9435707 0.41428463  4.691390  3.309624e-06
age              0.2425584 0.00833154 29.113274 6.504859e-120
smokesmoker:age -0.1627027 0.03073753 -5.293290  1.645078e-07</code></pre>
</div>
</div>
</section>
<section id="inference-for-non-smokers-i.e.-the-reference-category" class="level2">
<h2 class="anchored" data-anchor-id="inference-for-non-smokers-i.e.-the-reference-category">Inference for Non-Smokers (i.e., the Reference Category)</h2>
<p>For example, for <span class="math inline">\(\hat\beta_2\)</span> we would be testing if the estimated slope for age for <em>non-smokers</em> is significantly different from 0. We see that <span class="math inline">\(p&lt;0.001\)</span>, so we would reject <span class="math inline">\(H_0\)</span> and conclude that the slope for age for non-smokers is significantly different from 0.</p>
<p>The point estimate, interval estimate, and uncertainty for the association between FEV and age for <em>non-smokers</em> is:</p>
<ul>
<li><p>Point Estimate: <span class="math inline">\(\hat{\beta}_2=\)</span> 0.24256 liters/year</p></li>
<li><p>Interval Estimate (95% CI): <span class="math inline">\(\hat{\beta}_2 \pm t_{n-p-1,\alpha/2} SE(\hat{\beta}_2) = 0.24256 \pm 1.96(0.00833) = (0.2262, 0.2589)\)</span>, where <span class="math inline">\(t_{650,0.975}=1.96\)</span></p></li>
<li><p>Uncertainty: <span class="math inline">\(t=29.11\)</span> with <span class="math inline">\(p&lt;0.001\)</span></p></li>
</ul>
<p>On average, FEV increases by 0.24 liters for a one year increase in age (95% CI: 0.23, 0.26 L) for non-smokers, which is significantly different from 0 (p&lt;0.001).</p>
</section>
<section id="inference-for-smokers" class="level2">
<h2 class="anchored" data-anchor-id="inference-for-smokers">Inference for Smokers</h2>
<p><strong>But if we are interested in testing the slope for age for smokers we need to do a little more work!</strong> There are 3 approaches that may be of use depending on the information you have available:</p>
<ol type="1">
<li>Calculate the standard error for <span class="math inline">\(\hat\beta_2 + \hat\beta_3\)</span> by hand from the variance-covariance matrix to use in calculating 95% CI, p-values, etc.</li>
<li>Use some form of general linear hypothesis testing to do this work of combining beta coefficients.</li>
<li>Reverse code the categorical variable so that “Age” is now the estimated slope for age for <em>smokers</em>.</li>
</ol>
</section>
<section id="option-1-use-the-variance-covariance-matrix" class="level2">
<h2 class="anchored" data-anchor-id="option-1-use-the-variance-covariance-matrix">Option 1: Use the Variance-Covariance Matrix</h2>
<p>Recall, the variance for two random variables that are added together is <span class="math inline">\(Var(X+Y) = Var(X) + Var(Y) + 2 \times Cov(X,Y)\)</span>. The standard error is then the square root of this: <span class="math inline">\(SE(X+Y) = \sqrt{Var(X+Y)}\)</span>.</p>
<p>We can replace <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> with our <span class="math inline">\(\hat\beta\)</span>’s of interest and calculate the standard error by extracting the relevant information from the variance-covariance matrix. The <em>variance-covariance</em> matrix is a square matrix (i.e., same number of rows and columns) which has the variances along the main diagonal (i.e., from upper left to lower right) and the covariances between any two beta coefficients on the off-diagonal:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)   smokesmoker           age smokesmoker:age
(Intercept)      0.0068311473 -0.0068311473 -6.618543e-04    6.618543e-04
smokesmoker     -0.0068311473  0.1716317529  6.618543e-04   -1.249970e-02
age             -0.0006618543  0.0006618543  6.941456e-05   -6.941456e-05
smokesmoker:age  0.0006618543 -0.0124997012 -6.941456e-05    9.447957e-04</code></pre>
</div>
</div>
<p>From this matrix we see that</p>
<ul>
<li><span class="math inline">\(Var(\hat\beta_2)=6.941456e-05=0.0000694146\)</span></li>
<li><span class="math inline">\(Var(\hat\beta_3)=9.447957e-04=0.0009447957\)</span></li>
<li><span class="math inline">\(Cov(\hat\beta_2,\hat\beta_3)=Cov(\hat\beta_3,\hat\beta_2)=-6.941456e-05=−0.000069415\)</span></li>
</ul>
<p>Plugging these values into our equation for the standard error results in:</p>
<p><span class="math inline">\(\begin{aligned} SE(\hat{\beta}_2+\hat{\beta}_3) =&amp; \sqrt{Var(\hat{\beta}_2) + Var(\hat{\beta}_3) + 2\times Cov(\hat{\beta}_2,\hat{\beta}_3)} \\ =&amp; \sqrt{0.0000694146 + 0.0009447957 + 2(-0.000069415)} \\ =&amp; \sqrt{0.0008753803} \\ =&amp; 0.029587 \end{aligned}\)</span></p>
<p>The point estimate, interval estimate, and uncertainty for the association between FEV and age for <em>smokers</em> is:</p>
<ul>
<li><p>Point Estimate: <span class="math inline">\(\hat{\beta}_2 + \hat{\beta}_3=0.24256+(-0.16270)=\)</span> 0.07986 liters/year</p></li>
<li><p>Interval Estimate (95% CI): <span class="math inline">\(0.07986 \pm 1.96(0.029587) = (0.0219, 0.1378)\)</span></p></li>
<li><p>Uncertainty: <span class="math inline">\(t=\frac{0.07986}{0.029587}=2.699\)</span> with <span class="math inline">\(p=\)</span><code>2*pt(2.699,650,lower.tail=F)</code><span class="math inline">\(=0.007\)</span></p></li>
</ul>
<p>On average, FEV increases by 0.08 liters for a one year increase in age (95% CI: 0.02, 0.14 L) for smokers, which is significantly different from 0 (p=0.007).</p>
</section>
<section id="option-2-use-general-linear-hypothesis-tests" class="level2">
<h2 class="anchored" data-anchor-id="option-2-use-general-linear-hypothesis-tests">Option 2: Use General Linear Hypothesis Tests</h2>
<p>We can also use the <code>glht</code> function in the <code>multcomp</code> package in <code>R</code> to calculate the interval estimate and uncertainty:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">nrow=</span><span class="dv">1</span>) <span class="co">#beta2+beta3</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1, <span class="at">linfct=</span>K))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: lm(formula = fev ~ smoke * age, data = fev)

Linear Hypotheses:
       Estimate Std. Error t value Pr(&gt;|t|)   
1 == 0  0.07986    0.02959   2.699  0.00713 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>We see that the results match those of Option 1.</p>
<p><strong>NOTE:</strong> For <code>glm</code> models the normal approximation is used, whereas for <code>lm</code> models the t-distribution is used.</p>
</section>
<section id="option-3-use-reverse-coding-of-the-categorical-predictor" class="level2">
<h2 class="anchored" data-anchor-id="option-3-use-reverse-coding-of-the-categorical-predictor">Option 3: Use Reverse Coding of the Categorical Predictor</h2>
<p>Our third option is to reverse the coding for <code>smoke</code>, then evaluate the estimate of the new <span class="math inline">\(\hat\beta_2^*\)</span>:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r fold-show code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fev<span class="sc">$</span>nonsmoke <span class="ot">&lt;-</span> <span class="fu">factor</span>(fev<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">'smoker'</span>,<span class="st">'nonsmoker'</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>mod1_reverse <span class="ot">&lt;-</span> <span class="fu">lm</span>( fev <span class="sc">~</span> nonsmoke<span class="sc">*</span>age, <span class="at">data=</span>fev )</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1_reverse)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                         Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)            2.19696626 0.40595641  5.411828 8.782811e-08
nonsmokenonsmoker     -1.94357074 0.41428463 -4.691390 3.309624e-06
age                    0.07985574 0.02958684  2.699029 7.134971e-03
nonsmokenonsmoker:age  0.16270267 0.03073753  5.293290 1.645078e-07</code></pre>
</div>
</div>
<p>We see based on these results that the estimate, standard error, t-value, and p-value for <code>age</code> match our estimates from Options 1 and 2 above.</p>
<p>The caveat with this approach is that we would still have to fit the “original” model to estimate the effect for non-smokers without extra work, <em>or</em> we could do Option 1 or Option 2 for non-smokers with this model.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb10" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Week 12 Lab"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Alex Kaizer</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">  roles: "Instructor"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">  affiliation: University of Colorado-Anschutz Medical Campus</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc_float:</span><span class="co"> true</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> left</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap </span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=F, message=F, warning=F}</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>This page is part of the University of Colorado-Anschutz Medical Campus' <span class="co">[</span><span class="ot">BIOS 6618 Labs</span><span class="co">](/labs/index.qmd)</span> collection, the mini-lecture content delivered at the start of class before breaking out into small groups to work on the homework assignment.</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="fu"># What's on the docket this week?</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>We are diving into some examples of interactions and how to conduct inference on them (a notoriously tricky topic!). We'll then spend the rest of time breaking out into groups to work on homework.</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="fu"># Interactions: Definition</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>Effect modification or interaction is when the relationship between our outcome, $Y$, and primary explanatory variable (PEV), $X$, varies by some other covariate, $C$. Specifically the terms are defined as:</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Effect Modification:** non-quantitative clinical or biological attribute of *population*</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Interaction:** quantitative attribute of a *dataset*, may be scale dependent</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>An **effect modifier** or **moderator** is the variable that "causes" the effect modification. If a variable is an effect modifier, the role as a possible confounder is secondary.</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a><span class="fu"># Interactions Example from FEV Dataset</span></span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>In our slide deck on effect modification we examined Rosner's FEV dataset for the outcome of FEV predicted by smoking status (smoker vs. non-smoker), age (from 3 to 19), and their interaction. The fitted regression model was</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>$\begin{aligned} </span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>\hat{Y} =&amp; \hat\beta_0 + \hat\beta_1 X_1 + \hat\beta_2 X_2 + \hat\beta_3 X_1 X_2 <span class="sc">\\</span></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>=&amp; 0.25 + 1.94 \times \text{Smoker} + 0.24 \times \text{Age} + (-0.16 \times \text{Smoker} \times \text{Age} ) </span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>\end{aligned}$</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Regression Equation for Smokers vs. Non-smokers</span></span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>Given that smoking status is a categorical predictor, we may be interested in using the fitted regression model above and simplifying it to be from the perspective of nonsmokers and smokers. This can help us more clearly identify the intercept and slope(s) for the two groups.</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>For *non-smokers* we can think of this as taking our fitted regression equation from above, plugging in "0" for "Smoker", and focusing on simplified regression equation:</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>$\begin{aligned}</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>\hat{Y}_{nonsmk} =&amp; 0.25 + 1.94 \times 0 + 0.24 \times \text{Age} + (-0.16 \times 0 \times \text{Age} ) <span class="sc">\\</span></span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>=&amp; 0.25 + 0.24 \times \text{Age}</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>\end{aligned}$</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a>Likewise, for *smokers* we can think of this as plugging in "1" for "Smoker":</span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>$\begin{aligned}</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a>\hat{Y}_{smk} =&amp; 0.25 + 1.94 \times 1 + 0.24 \times \text{Age} + (-0.16 \times 1 \times \text{Age} ) <span class="sc">\\</span></span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>=&amp; (0.25+1.94) + (0.24-0.16) \times \text{Age} <span class="sc">\\</span> </span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>=&amp; 2.19 + 0.08 \times \text{Age}</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a>\end{aligned}$</span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>With these two regression equations, we can see that smokers and nonsmokers have different intercepts and slopes for age. We can also see that the intercept and slope for *smokers* is based on the sum of different $\hat\beta$'s. Visually this would look something like:</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, eval=T}</span></span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a>fev <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../.data/FEV_rosner.csv'</span>)</span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a>fev<span class="sc">$</span>pch <span class="ot">&lt;-</span> <span class="dv">0</span>; fev<span class="sc">$</span>pch[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)] <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a>fev<span class="sc">$</span>col <span class="ot">&lt;-</span> <span class="st">'green3'</span>; fev<span class="sc">$</span>col[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)] <span class="ot">&lt;-</span> <span class="st">'blue'</span></span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Code to generate picture</span></span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a><span class="co">#FEV figure with regression lines for FEV ~ smoking status + age + smoke*age (slide 11)</span></span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a>lmfi <span class="ot">&lt;-</span> <span class="fu">lm</span>( fev <span class="sc">~</span> smoke <span class="sc">*</span> age, <span class="at">data=</span>fev)</span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>fev<span class="sc">$</span>age, <span class="at">y=</span>fev<span class="sc">$</span>fev, <span class="at">pch=</span>fev<span class="sc">$</span>pch,<span class="at">col=</span>fev<span class="sc">$</span>col,<span class="at">cex=</span><span class="fl">0.8</span>, <span class="at">xlab=</span><span class="st">'Age (years)'</span>, <span class="at">ylab=</span><span class="st">'FEV (liters)'</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>))</span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x=</span>fev<span class="sc">$</span>age[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)], <span class="at">y=</span>fev<span class="sc">$</span>fev[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)], <span class="at">pch=</span>fev<span class="sc">$</span>pch[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)],<span class="at">col=</span>fev<span class="sc">$</span>col[<span class="fu">which</span>(fev<span class="sc">$</span>smoke<span class="sc">==</span><span class="st">'smoker'</span>)],<span class="at">cex=</span><span class="fl">0.8</span>)</span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>) ), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'green4'</span> )</span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>) <span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">4</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">19</span>) ) , <span class="at">lty=</span><span class="dv">2</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'blue4'</span>)</span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>) ), <span class="at">lty=</span><span class="dv">4</span>, <span class="at">col=</span><span class="st">'green4'</span> )</span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>), <span class="at">y=</span>( <span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(lmfi)[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">4</span>]<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>) ) , <span class="at">lty=</span><span class="dv">4</span>, <span class="at">col=</span><span class="st">'blue4'</span>)</span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, <span class="at">col=</span><span class="st">'gray65'</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'topleft'</span>,<span class="at">inset=</span><span class="fl">0.005</span>,<span class="at">bg=</span><span class="st">'white'</span>,<span class="at">box.col=</span><span class="st">'white'</span>,<span class="at">pch=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">15</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="st">'green3'</span>,<span class="st">'blue'</span>),<span class="at">legend=</span><span class="fu">c</span>(<span class="st">'Non-Smoker'</span>,<span class="st">'Smoker'</span>))</span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(  <span class="fu">expression</span>(<span class="fu">hat</span>(Y) <span class="sc">==</span> <span class="fu">hat</span>(beta)[<span class="dv">0</span>] <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">1</span>] <span class="sc">*</span> Smoke <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">2</span>] <span class="sc">*</span> Age <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">3</span>] <span class="sc">*</span> Smoke <span class="sc">%*%</span> Age) )</span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">15</span>, <span class="at">y =</span> <span class="dv">1</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(Y)[nonsmk] <span class="sc">==</span> (<span class="fu">hat</span>(beta)[<span class="dv">0</span>]<span class="sc">+</span><span class="dv">0</span>) <span class="sc">+</span> (<span class="fu">hat</span>(beta)[<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">0</span>) <span class="sc">%*%</span> Age), <span class="at">col=</span><span class="st">'green4'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">5.5</span>, <span class="at">y =</span> <span class="fl">4.4</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(Y)[smk] <span class="sc">==</span> (<span class="fu">hat</span>(beta)[<span class="dv">0</span>]<span class="sc">+</span><span class="fu">hat</span>(beta)[<span class="dv">1</span>]) <span class="sc">+</span> (<span class="fu">hat</span>(beta)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">3</span>]) <span class="sc">%*%</span> Age), <span class="at">col=</span><span class="st">'blue4'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">y=</span><span class="fu">c</span>(<span class="fu">coef</span>(lmfi)[<span class="dv">1</span>],<span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>]), <span class="at">col=</span><span class="st">'purple'</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="sc">-</span>.<span class="dv">25</span>, <span class="at">y=</span><span class="fl">1.3</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>]), <span class="at">col=</span><span class="st">'purple'</span>, <span class="at">pos=</span><span class="dv">4</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="sc">-</span>.<span class="dv">1</span>, <span class="at">y=</span><span class="fl">0.15</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">0</span>]), <span class="at">col=</span><span class="st">'green3'</span>, <span class="at">pos=</span><span class="dv">4</span>, <span class="at">cex=</span><span class="fl">1.2</span>); <span class="fu">points</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">y=</span><span class="fu">coef</span>(lmfi)[<span class="dv">1</span>], <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">'green3'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="sc">-</span>.<span class="dv">1</span>, <span class="at">y=</span><span class="dv">2</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">0</span>] <span class="sc">+</span> <span class="fu">hat</span>(beta)[<span class="dv">1</span>]), <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">pos=</span><span class="dv">4</span>, <span class="at">cex=</span><span class="fl">1.2</span>); <span class="fu">points</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">y=</span><span class="fu">coef</span>(lmfi)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(lmfi)[<span class="dv">2</span>], <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">cex=</span><span class="fl">1.2</span>)</span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpreting the Beta Coefficients</span></span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a>The meaning of each $\hat{\beta}$ is:</span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\hat\beta_0$: estimated average FEV for non-smokers at age 0 (i.e., all $X=0$)</span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\hat\beta_1$: estimated difference in FEV at age 0 between smokers and non-smokers (i.e., difference in intercepts)</span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\hat\beta_2$: estimated slope for age for *non-smokers* (increase in FEV per year of age for non-smokers)</span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\hat\beta_3$: estimated *difference* in slope between smokers and non-smokers</span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\hat\beta_0 + \hat\beta_1$: estimated average FEV for smokers at age 0 (i.e., here $X_1=1$, but $X_1=0$ still)</span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$\hat\beta_2 + \hat\beta_3$: estimated slope for age for *smokers* (increase in FEV per year of age for smokers)</span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a>Based on our interpretation above, we may be interested in formally testing the hypothesis that any one of our estimates is significantly different from 0. Fortunately, if we wish to test any of the $\hat\beta$'s on their own (i.e., not $\hat\beta_i + \hat\beta_j$), we can simply use the regression output:</span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source='fold-show'}</span></span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( fev <span class="sc">~</span> smoke <span class="sc">*</span> age, <span class="at">data=</span>fev)</span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)<span class="sc">$</span>coefficients</span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inference for Non-Smokers (i.e., the Reference Category)</span></span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a>For example, for $\hat\beta_2$ we would be testing if the estimated slope for age for *non-smokers* is significantly different from 0. We see that $p&lt;0.001$, so we would reject $H_0$ and conclude that the slope for age for non-smokers is significantly different from 0.</span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a>The point estimate, interval estimate, and uncertainty for the association between FEV and age for *non-smokers* is:</span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Point Estimate: $\hat{\beta}_2=$ 0.24256 liters/year</span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Interval Estimate (95% CI): $\hat{\beta}_2 \pm t_{n-p-1,\alpha/2} SE(\hat{\beta}_2) = 0.24256 \pm 1.96(0.00833) = (0.2262, 0.2589)$, where $t_{650,0.975}=1.96$</span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Uncertainty: $t=29.11$ with $p&lt;0.001$</span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a>On average, FEV increases by 0.24 liters for a one year increase in age (95% CI: 0.23, 0.26 L) for non-smokers, which is significantly different from 0 (p&lt;0.001).</span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inference for Smokers</span></span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a>**But if we are interested in testing the slope for age for smokers we need to do a little more work!** There are 3 approaches that may be of use depending on the information you have available:</span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Calculate the standard error for $\hat\beta_2 + \hat\beta_3$ by hand from the variance-covariance matrix to use in calculating 95% CI, p-values, etc.</span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Use some form of general linear hypothesis testing to do this work of combining beta coefficients.</span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Reverse code the categorical variable so that "Age" is now the estimated slope for age for *smokers*.</span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a><span class="fu">## Option 1: Use the Variance-Covariance Matrix</span></span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a>Recall, the variance for two random variables that are added together is $Var(X+Y) = Var(X) + Var(Y) + 2 \times Cov(X,Y)$. The standard error is then the square root of this: $SE(X+Y) = \sqrt{Var(X+Y)}$.</span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a>We can replace $X$ and $Y$ with our $\hat\beta$'s of interest and calculate the standard error by extracting the relevant information from the variance-covariance matrix. The *variance-covariance* matrix is a square matrix (i.e., same number of rows and columns) which has the variances along the main diagonal (i.e., from upper left to lower right) and the covariances between any two beta coefficients on the off-diagonal:</span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source='fold-show'}</span></span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(mod1)</span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a>From this matrix we see that </span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$Var(\hat\beta_2)=6.941456e-05=0.0000694146$</span>
<span id="cb10-162"><a href="#cb10-162" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$Var(\hat\beta_3)=9.447957e-04=0.0009447957$</span>
<span id="cb10-163"><a href="#cb10-163" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>$Cov(\hat\beta_2,\hat\beta_3)=Cov(\hat\beta_3,\hat\beta_2)=-6.941456e-05=−0.000069415$</span>
<span id="cb10-164"><a href="#cb10-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-165"><a href="#cb10-165" aria-hidden="true" tabindex="-1"></a>Plugging these values into our equation for the standard error results in:</span>
<span id="cb10-166"><a href="#cb10-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-167"><a href="#cb10-167" aria-hidden="true" tabindex="-1"></a>$\begin{aligned}</span>
<span id="cb10-168"><a href="#cb10-168" aria-hidden="true" tabindex="-1"></a>SE(\hat{\beta}_2+\hat{\beta}_3) =&amp; \sqrt{Var(\hat{\beta}_2) + Var(\hat{\beta}_3) + 2\times Cov(\hat{\beta}_2,\hat{\beta}_3)} <span class="sc">\\</span></span>
<span id="cb10-169"><a href="#cb10-169" aria-hidden="true" tabindex="-1"></a>=&amp; \sqrt{0.0000694146 + 0.0009447957 + 2(-0.000069415)} <span class="sc">\\</span></span>
<span id="cb10-170"><a href="#cb10-170" aria-hidden="true" tabindex="-1"></a>=&amp; \sqrt{0.0008753803} <span class="sc">\\</span></span>
<span id="cb10-171"><a href="#cb10-171" aria-hidden="true" tabindex="-1"></a>=&amp; 0.029587</span>
<span id="cb10-172"><a href="#cb10-172" aria-hidden="true" tabindex="-1"></a>\end{aligned}$</span>
<span id="cb10-173"><a href="#cb10-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-174"><a href="#cb10-174" aria-hidden="true" tabindex="-1"></a>The point estimate, interval estimate, and uncertainty for the association between FEV and age for *smokers* is:</span>
<span id="cb10-175"><a href="#cb10-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-176"><a href="#cb10-176" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Point Estimate: $\hat{\beta}_2 + \hat{\beta}_3=0.24256+(-0.16270)=$ 0.07986 liters/year</span>
<span id="cb10-177"><a href="#cb10-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-178"><a href="#cb10-178" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Interval Estimate (95% CI): $0.07986 \pm 1.96(0.029587) = (0.0219, 0.1378)$</span>
<span id="cb10-179"><a href="#cb10-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-180"><a href="#cb10-180" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Uncertainty: $t=\frac{0.07986}{0.029587}=2.699$ with $p=$<span class="in">`2*pt(2.699,650,lower.tail=F)`</span>$=0.007$</span>
<span id="cb10-181"><a href="#cb10-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-182"><a href="#cb10-182" aria-hidden="true" tabindex="-1"></a>On average, FEV increases by 0.08 liters for a one year increase in age (95% CI: 0.02, 0.14 L) for smokers, which is significantly different from 0 (p=0.007).</span>
<span id="cb10-183"><a href="#cb10-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-184"><a href="#cb10-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-185"><a href="#cb10-185" aria-hidden="true" tabindex="-1"></a><span class="fu">## Option 2: Use General Linear Hypothesis Tests</span></span>
<span id="cb10-186"><a href="#cb10-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-187"><a href="#cb10-187" aria-hidden="true" tabindex="-1"></a>We can also use the <span class="in">`glht`</span> function in the <span class="in">`multcomp`</span> package in <span class="in">`R`</span> to calculate the interval estimate and uncertainty:</span>
<span id="cb10-188"><a href="#cb10-188" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=T, message=F, class.source='fold-show'}</span></span>
<span id="cb10-189"><a href="#cb10-189" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb10-190"><a href="#cb10-190" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">nrow=</span><span class="dv">1</span>) <span class="co">#beta2+beta3</span></span>
<span id="cb10-191"><a href="#cb10-191" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(mod1, <span class="at">linfct=</span>K))</span>
<span id="cb10-192"><a href="#cb10-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-193"><a href="#cb10-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-194"><a href="#cb10-194" aria-hidden="true" tabindex="-1"></a>We see that the results match those of Option 1.</span>
<span id="cb10-195"><a href="#cb10-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-196"><a href="#cb10-196" aria-hidden="true" tabindex="-1"></a>**NOTE:** For <span class="in">`glm`</span> models the normal approximation is used, whereas for <span class="in">`lm`</span> models the t-distribution is used.</span>
<span id="cb10-197"><a href="#cb10-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-198"><a href="#cb10-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-199"><a href="#cb10-199" aria-hidden="true" tabindex="-1"></a><span class="fu">## Option 3: Use Reverse Coding of the Categorical Predictor</span></span>
<span id="cb10-200"><a href="#cb10-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-201"><a href="#cb10-201" aria-hidden="true" tabindex="-1"></a>Our third option is to reverse the coding for <span class="in">`smoke`</span>, then evaluate the estimate of the new $\hat\beta_2^*$:</span>
<span id="cb10-202"><a href="#cb10-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-203"><a href="#cb10-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, class.source='fold-show'}</span></span>
<span id="cb10-204"><a href="#cb10-204" aria-hidden="true" tabindex="-1"></a>fev<span class="sc">$</span>nonsmoke <span class="ot">&lt;-</span> <span class="fu">factor</span>(fev<span class="sc">$</span>smoke, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">'smoker'</span>,<span class="st">'nonsmoker'</span>))</span>
<span id="cb10-205"><a href="#cb10-205" aria-hidden="true" tabindex="-1"></a>mod1_reverse <span class="ot">&lt;-</span> <span class="fu">lm</span>( fev <span class="sc">~</span> nonsmoke<span class="sc">*</span>age, <span class="at">data=</span>fev )</span>
<span id="cb10-206"><a href="#cb10-206" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1_reverse)<span class="sc">$</span>coefficients</span>
<span id="cb10-207"><a href="#cb10-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-208"><a href="#cb10-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-209"><a href="#cb10-209" aria-hidden="true" tabindex="-1"></a>We see based on these results that the estimate, standard error, t-value, and p-value for <span class="in">`age`</span> match our estimates from Options 1 and 2 above.</span>
<span id="cb10-210"><a href="#cb10-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-211"><a href="#cb10-211" aria-hidden="true" tabindex="-1"></a>The caveat with this approach is that we would still have to fit the "original" model to estimate the effect for non-smokers without extra work, *or* we could do Option 1 or Option 2 for non-smokers with this model.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>